### ISSUE TITLE
module:create fails when the path to module includes a subdirectory

### ISSUE THREAD

**Issue by morne** [ThrowTheSwitch/Ceedling#111]
When calling for example:
rake module:create[tools/test]  
with tools being a sub directory, the module files are created correctly, but the test files creation is failing.

If you look at the trace below, it seems that 'Test' is appended in the wrong place, i.e. 
test/Testtools/test.c 
instead of 
test/tools/Testtest.c

(in this case the directory 'test' holds all the tests, 'tools' is a sub directory under 'src' and a sub directory under 'test', and 'Test' is the prefix)

```
rake module:create[tools/test]  
File src/tools/test.c created
File src/tools/test.h created
rake aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - test/Testtools/test.c
home/.gem/ruby/2.3.0/gems/ceedling-0.24.0/vendor/unity/auto/generate_module.rb:160:in `initialize'
home/.gem/ruby/2.3.0/gems/ceedling-0.24.0/vendor/unity/auto/generate_module.rb:160:in `open'
home/.gem/ruby/2.3.0/gems/ceedling-0.24.0/vendor/unity/auto/generate_module.rb:160:in `block in generate'
/home/.gem/ruby/2.3.0/gems/ceedling-0.24.0/vendor/unity/auto/generate_module.rb:159:in `each'
/home/.gem/ruby/2.3.0/gems/ceedling-0.24.0/vendor/unity/auto/generate_module.rb:159:in `each_with_index'
/home/.gem/ruby/2.3.0/gems/ceedling-0.24.0/vendor/unity/auto/generate_module.rb:159:in `generate'
/home/.gem/ruby/2.3.0/gems/ceedling-0.24.0/plugins/module_generator/lib/module_generator.rb:17:in `create'
/home/.gem/ruby/2.3.0/gems/ceedling-0.24.0/plugins/module_generator/module_generator.rake:12:in `block (3 levels) in <top (required)>'
/home/.gem/ruby/2.3.0/gems/ceedling-0.24.0/plugins/module_generator/module_generator.rake:12:in `each'
/home/.gem/ruby/2.3.0/gems/ceedling-0.24.0/plugins/module_generator/module_generator.rake:12:in `block (2 levels) in <top (required)>'
/home/.gem/ruby/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => module:create
```

**Comment by mvandervoord** [comment]
Fixed :)

**Comment by morne** [comment]
Tested it, works great.

Thanks a lot !
