### ISSUE TITLE
ceedling paths:* not working

### ISSUE THREAD

**Issue by hmijail** [ThrowTheSwitch/Ceedling#119]
`ceedling paths:include` (for example) does work, but not the asterisk version.

```
$ ceedling paths:* --trace
rake aborted!
Don't know how to build task 'paths:*' (see --tasks)
/Users/mija/.gem/ruby/2.0.0/gems/rake-11.1.2/lib/rake/task_manager.rb:71:in `[]'
/Users/mija/.gem/ruby/2.0.0/gems/rake-11.1.2/lib/rake/application.rb:149:in `invoke_task'
/Users/mija/.gem/ruby/2.0.0/gems/rake-11.1.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/mija/.gem/ruby/2.0.0/gems/rake-11.1.2/lib/rake/application.rb:106:in `each'
/Users/mija/.gem/ruby/2.0.0/gems/rake-11.1.2/lib/rake/application.rb:106:in `block in top_level'
/Users/mija/.gem/ruby/2.0.0/gems/rake-11.1.2/lib/rake/application.rb:115:in `run_with_threads'
/Users/mija/.gem/ruby/2.0.0/gems/rake-11.1.2/lib/rake/application.rb:100:in `top_level'
/Users/mija/.gem/ruby/2.0.0/gems/rake-11.1.2/lib/rake/application.rb:78:in `block in run'
/Users/mija/.gem/ruby/2.0.0/gems/rake-11.1.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/mija/.gem/ruby/2.0.0/gems/rake-11.1.2/lib/rake/application.rb:75:in `run'
/Users/mija/.gem/ruby/2.0.0/gems/rake-11.1.2/bin/rake:33:in `<top (required)>'
/Users/mija/.gem/ruby/2.0.0/bin/rake:23:in `load'
/Users/mija/.gem/ruby/2.0.0/bin/rake:23:in `<main>'
```

**Comment by mvandervoord** [comment]
There isn't a paths:* option. Is there one listed in the docs somewhere that needs to be removed?

**Comment by hmijail** [comment]
Yes, it's mentioned twice in CeedlingPacket.md

**Comment by mvandervoord** [comment]
Thanks! I'll see if we lost this behavior at some point or if we never implemented or what. :)

**Comment by hmijail** [comment]
Reading carefully, maybe it's just that I took it too literally, and I should use the particular names of the path types instead of the asterisk. 

... but maybe it could be just a bit clearer?

**Comment by mvandervoord** [comment]
Yeah. I'm thinking it's a poor-documentation issue... but I'll verify. Either way, it should be fixed. I'm sure you're not the only person to wonder what it means.

**Comment by mvandervoord** [comment]
Thanks. Fixed
