### ISSUE TITLE
Test files with the word "setup" crash on Windows

### ISSUE THREAD

**Issue by shahokun** [ThrowTheSwitch/Ceedling#146]
Test files with the word "setup" somewhere in the filename (e.g. test_setup.c) cause a Windows dialog to pop-up with the standard message "Windows can't open this file...To open this file, Windows needs to know what program you want to use to open it." The test runner then fails with the following output:

Test 'test_setup.c'
-------------------
Compiling test_setup_runner.c...
Compiling test_setup.c...
Compiling unity.c...
Compiling foo.c...
Compiling cmock.c...
Linking test_setup.out...
Running test_setup.out...

ERROR: Test executable "test_setup.out" failed.
> Produced no output to $stdout.
> And exited with status: [0] (count of failed tests).
> This is often a symptom of a bad memory access in source or test code.

rake aborted!

C:/sandbox/191-008/ceedling_validation/test_ceedling/vendor/ceedling/lib/ceedling/generator_helper.rb:36:in `test_results_error_handler'
C:/sandbox/191-008/ceedling_validation/test_ceedling/vendor/ceedling/lib/ceedling/generator.rb:153:in `generate_test_results'
C:/sandbox/191-008/ceedling_validation/test_ceedling/vendor/ceedling/lib/ceedling/rules_tests.rake:42:in `block in <top (required)>'
C:/sandbox/191-008/ceedling_validation/test_ceedling/vendor/ceedling/lib/ceedling/task_invoker.rb:74:in `invoke_test_results'
C:/sandbox/191-008/ceedling_validation/test_ceedling/vendor/ceedling/lib/ceedling/test_invoker.rb:68:in `block in setup_and_invoke'
C:/sandbox/191-008/ceedling_validation/test_ceedling/vendor/ceedling/lib/ceedling/test_invoker.rb:32:in `each'
C:/sandbox/191-008/ceedling_validation/test_ceedling/vendor/ceedling/lib/ceedling/test_invoker.rb:32:in `setup_and_invoke'
C:/sandbox/191-008/ceedling_validation/test_ceedling/vendor/ceedling/lib/ceedling/rules_tests.rake:57:in `block (2 levels) in <top (required)>'
Tasks: TOP => build/test/results/test_setup.pass
(See full trace by running task with --trace)

--------------------
OVERALL TEST SUMMARY
--------------------

No tests executed.

___
Changing the filename causes the test to run with no issues.

**Comment by dpostorivo** [comment]
It sounds like a similar issue to #116 . I'm not sure if there is a simple fix for this the only thing I can think of is prevent Ceedling from creating an executable that contains `setup` (or `patch` for the other case).

**Comment by shahokun** [comment]
Thanks for pointing out that link. It's useful to know that there are multiple keywords that need to be avoided. Seems like there isn't necessarily a simple solution, but it would be useful to have this documented in the manual (couldn't find it if it's already there).

**Comment by rasup** [comment]
I had the same problem, but solved it by getting this Group Policy setting disabled: "User Account Control: Detect application installations and prompt for elevation".

**Comment by DouweVanNijnatten** [comment]
Hi guys. I seem to have a similar issue with the word "update" somewhere in the test file name.  Can you confirm that it is in fact the same issue?
