### ISSUE TITLE
Error: Encoding::CompatibilityError: incompatible character encodings: UTF-8 and CP850

### ISSUE THREAD

**Issue by sgessler** [ThrowTheSwitch/Ceedling#165]
I installed Ceedling in Windows using the gem installer.

If I generate one of the examples and run the the tests they always fail with the error:
> Encoding::CompatibilityError: incompatible character encodings: UTF-8 and CP850

Anyone an idea on what is wrong?

The complete console log:
`C:\Users\sge\Documents\CeedlingProjects>ceedling example temp_sensor
Welcome to Ceedling!

...

Example project 'temp_sensor' created!
 - Tool documentation is located in vendor/ceedling/docs
 - Execute 'rake -T' to view available test & build tasks

C:\Users\sge\Documents\CeedlingProjects>cd temp_sensor

C:\Users\sge\Documents\CeedlingProjects\temp_sensor>rake test:all

Test 'TestAdcConductor.c'
-------------------------
rake aborted!
Encoding::CompatibilityError: incompatible character encodings: UTF-8 and CP850
C:/Users/sge/Documents/CeedlingProjects/temp_sensor/vendor/ceedling/lib/ceedling/tool_executor_helper.rb:91:in `print_happy_results'
C:/Users/sge/Documents/CeedlingProjects/temp_sensor/vendor/ceedling/lib/ceedling/tool_executor.rb:74:in `exec'
C:/Users/sge/Documents/CeedlingProjects/temp_sensor/vendor/ceedling/lib/ceedling/preprocessinator_includes_handler.rb:40:in `form_shallow_dependencies_rule'
C:/Users/sge/Documents/CeedlingProjects/temp_sensor/vendor/ceedling/lib/ceedling/preprocessinator.rb:31:in `preprocess_shallow_includes'
C:/Users/sge/Documents/CeedlingProjects/temp_sensor/vendor/ceedling/lib/ceedling/preprocessinator.rb:11:in `block in setup'
C:/Users/sge/Documents/CeedlingProjects/temp_sensor/vendor/ceedling/lib/ceedling/preprocessinator_helper.rb:11:in `preprocess_includes'
C:/Users/sge/Documents/CeedlingProjects/temp_sensor/vendor/ceedling/lib/ceedling/preprocessinator.rb:17:in `preprocess_test_and_invoke_test_mocks'
C:/Users/sge/Documents/CeedlingProjects/temp_sensor/vendor/ceedling/lib/ceedling/test_invoker.rb:73:in `block in setup_and_invoke'
C:/Users/sge/Documents/CeedlingProjects/temp_sensor/vendor/ceedling/lib/ceedling/test_invoker.rb:63:in `setup_and_invoke'
C:/Users/sge/Documents/CeedlingProjects/temp_sensor/vendor/ceedling/lib/ceedling/tasks_tests.rake:11:in `block (2 levels) in <top (required)>'
Tasks: TOP => test:all
(See full trace by running task with --trace)

--------------------
OVERALL TEST SUMMARY
--------------------

No tests executed.`

**Comment by dpostorivo** [comment]
Out of curiosity, what version of ruby are you using and what version of ceedling are you using? Does it also happen in the other sample project (blinky)? I'm going to start looking into it and this information would be very useful.

**Comment by dpostorivo** [comment]
@mvandervoord after playing around with app veyor which is specifically for testing applications for windows,  [it seems like 5 of the system tests fail](https://ci.appveyor.com/project/dpostorivo/ceedling-m50qh/build/job/pxrwmqdog8bwia1d). I'm assuming this issue and #170 are tied to this issue.

**Comment by mvandervoord** [comment]
Is someone able to retest this issue on Windows with 0.28.1. Don't forget to do a "ceedling update PROJECTNAME" from the folder outside your project after you install the latest gem.

**Comment by Letme** [comment]
I can confirm this issue in Linux version on a master branch 314fa4bd54f61db5d1ad9019d114d12ccc6724f 

Issue was CopyRight symbol (STM32 CMSIS) . When it is removed, everything works nicely.

**Comment by duanyp1991** [comment]
Hi, I have the same issue when I use Chinese characters in the assert message. Any solution on this?

Thanks a lot!

**Comment by art-of-dom** [comment]
Is this still an issue? testing against master I can't reproduce with the symbol @Letme used to reproduce it.

**Comment by mkarlesky** [comment]
Most encoding issues were resolved a while ago. 1.1.0-pre.3 adds even more resilience for encoding and locale issues. I will close this very old issue out now.
