### ISSUE TITLE
ceedling:test all - ERROR: Test executable failed.- rake aborted

### ISSUE THREAD

**Issue by Neroone** [ThrowTheSwitch/Ceedling#217]
[test_lights.zip](https://github.com/ThrowTheSwitch/Ceedling/files/1462398/test_lights.zip)
Hi,
I am trying to do a simple unit test project for a PIC18 microcontroller using XC8 compiler. When I run ceedling test:all I get the following errors.

Running test_lights.out...
> Shell executed command:
'build/test/out/test_lights.out 2>&1'
> Produced output:
sh: 1: build/test/out/test_lights.out: not found
> And exited with status: [127].

ERROR: Test executable "test_lights.out" failed.
> Produced no final test result counts in $stdout:
sh: 1: build/test/out/test_lights.out: not found
> And exited with status: [0] (count of failed tests).
> This is often a symptom of a bad memory access in source or test code.

rake aborted!

/home/usha/Software/Test5/vendor/ceedling/lib/ceedling/generator_helper.rb:36:in `test_results_error_handler'
/home/usha/Software/Test5/vendor/ceedling/lib/ceedling/generator.rb:162:in `generate_test_results'
/home/usha/Software/Test5/vendor/ceedling/lib/ceedling/rules_tests.rake:47:in `block in <top (required)>'
/home/usha/Software/Test5/vendor/ceedling/lib/ceedling/task_invoker.rb:74:in `invoke_test_results'
/home/usha/Software/Test5/vendor/ceedling/lib/ceedling/test_invoker.rb:104:in `block in setup_and_invoke'
/home/usha/Software/Test5/vendor/ceedling/lib/ceedling/test_invoker.rb:63:in `setup_and_invoke'
/home/usha/Software/Test5/vendor/ceedling/lib/ceedling/tasks_tests.rake:11:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/ceedling-0.28.2/bin/ceedling:287:in `block in <top (required)>'
/var/lib/gems/2.3.0/gems/ceedling-0.28.2/bin/ceedling:274:in `<top (required)>'
/usr/local/bin/ceedling:23:in `load'
/usr/local/bin/ceedling:23:in `<main>'
Tasks: TOP => build/test/results/test_lights.pass
(See full trace by running task with --trace)

--------------------
OVERALL TEST SUMMARY
--------------------

No tests executed.

I am not sure what I am missing. Any help would be appreciated. Thanks,
R

**Comment by MichaelBMiner** [comment]
I am having a similar issue in which my runner.o is not being created. Would like to find a solution for this.
