### ISSUE TITLE
Custom 'build_root' folder is not created

### ISSUE THREAD

**Issue by carlolars** [ThrowTheSwitch/Ceedling#247]
If changing the `build_root` path from the default _build_ then when trying to run tests the custom build root will not be created and the test fails.
Imo the tool should always be responsible for creating the build root no matter the path used.
  
```
$ ceedling test:all
ERROR: Config filepath [:project][:build_root]['custom_build'] does not exist on disk.
R:/test/vendor/ceedling/lib/ceedling/configurator.rb:284:in `validate': unhandled exception
        from R:/test/vendor/ceedling/lib/ceedling/setupinator.rb:32:in `do_setup'
        from vendor/ceedling/lib/../lib/ceedling/rakefile.rb:48:in `<top (required)>'
        from vendor/ceedling/lib/ceedling.rb:66:in `load'
        from vendor/ceedling/lib/ceedling.rb:66:in `load_project'
        from C:/msys64/mingw64/lib/ruby/gems/2.5.0/gems/ceedling-0.28.2/bin/ceedling:271:in `<top (required)>'
        from C:/msys64/mingw64/bin/ceedling:23:in `load'
        from C:/msys64/mingw64/bin/ceedling:23:in `<main>'

```

**Comment by carlolars** [comment]
Fixed in #257.
