### ISSUE TITLE
ceedling command suddenly not working. 

### ISSUE THREAD

**Issue by tada1765** [ThrowTheSwitch/Ceedling#276]
sorry to ask what happening with the command "ceedling".After i create a project through the command call "ceedling module:create[myProject]" and i type "ceedling" is work fine, i having 1 ignore test. But when i type "ceedling" again, it show as follow:  (i really no ideal, can someone help me pls.)
______________________________________________________________________________________________
$ ceedling

Test 'test_OtherCreate.c'
-------------------------
Linking test_OtherCreate.exe...
collect2.exe: fatal error: cannot find 'ld'
compilation terminated.
ERROR: Shell command failed.
> Shell executed command:
'gcc.exe "build/test/out/test_OtherCreate_runner.o" "build/test/out/test_OtherCreate.o" "build/test/out/unity.o" "build/test/out/OtherCreate.o" "build/test/out/cmock.o" -o "build/test/out/test_OtherCreate.exe"'
> And exited with status: [1].

NOTICE: If the linker reports missing symbols, the following may be to blame:
  1. Test lacks #include statements corresponding to needed source files.
  2. Project search paths do not contain source files corresponding to #include statements in the test.
  3. Test does not #include needed mocks.

rake aborted!

C:/Student/createOtherProject/vendor/ceedling/lib/ceedling/generator.rb:143:in `rescue in generate_executable_file'
C:/Student/createOtherProject/vendor/ceedling/lib/ceedling/generator.rb:147:in `generate_executable_file'
C:/Student/createOtherProject/vendor/ceedling/lib/ceedling/rules_tests.rake:32:in `block in <top (required)>'
C:/Student/createOtherProject/vendor/ceedling/lib/ceedling/task_invoker.rb:74:in `invoke_test_results'
C:/Student/createOtherProject/vendor/ceedling/lib/ceedling/test_invoker.rb:104:in `block in setup_and_invoke'
C:/Student/createOtherProject/vendor/ceedling/lib/ceedling/test_invoker.rb:63:in `setup_and_invoke'
C:/Student/createOtherProject/vendor/ceedling/lib/ceedling/tasks_tests.rake:11:in `block (2 levels) in <top (required)>'
C:/ProgramFiles/Ruby24-x64/bin/ceedling:22:in `load'
C:/ProgramFiles/Ruby24-x64/bin/ceedling:22:in `<main>'
ShellExecutionException: ShellExecutionException
C:/Student/createOtherProject/vendor/ceedling/lib/ceedling/tool_executor.rb:78:in `exec'
C:/Student/createOtherProject/vendor/ceedling/lib/ceedling/generator.rb:128:in `generate_executable_file'
C:/Student/createOtherProject/vendor/ceedling/lib/ceedling/rules_tests.rake:32:in `block in <top (required)>'
C:/Student/createOtherProject/vendor/ceedling/lib/ceedling/task_invoker.rb:74:in `invoke_test_results'
C:/Student/createOtherProject/vendor/ceedling/lib/ceedling/test_invoker.rb:104:in `block in setup_and_invoke'
C:/Student/createOtherProject/vendor/ceedling/lib/ceedling/test_invoker.rb:63:in `setup_and_invoke'
C:/Student/createOtherProject/vendor/ceedling/lib/ceedling/tasks_tests.rake:11:in `block (2 levels) in <top (required)>'
C:/ProgramFiles/Ruby24-x64/bin/ceedling:22:in `load'
C:/ProgramFiles/Ruby24-x64/bin/ceedling:22:in `<main>'
Tasks: TOP => build/test/results/test_OtherCreate.pass => build/test/out/test_OtherCreate.exe
(See full trace by running task with --trace)
ERROR: Ceedling Failed

**Comment by tada1765** [comment]
hmmm..... my old project seem work with command "ceedling test:all", but not for command "ceedling".
when i type "ceedling" it show as follow:

$ ceedling
rake aborted!
Don't know how to build task 'release' (see --tasks)
C:/ProgramFiles/Ruby24-x64/bin/ceedling:22:in `load'
C:/ProgramFiles/Ruby24-x64/bin/ceedling:22:in `<main>'
Tasks: TOP => default
(See full trace by running task with --trace)
ERROR: Ceedling Failed

**Comment by dpostorivo** [comment]
can you post your project.yml? It looks like it is trying to do release as the default task which you may not be set up for.
