### ISSUE TITLE
Failed to execute basic example: Shell command failed and exited with status: [1]

### ISSUE THREAD

**Issue by fahad80** [ThrowTheSwitch/Ceedling#296]
Installed ceedling through gem.

```
>>ceedling version
Ceedling:: 0.28.3
CException:: 1.3.1.18
CMock:: 2.4.6.217
Unity:: 2.4.3.122
```

Then I created the example temp_sensor.

```
D:\ZTest\temp_sensor>ceedling example temp_sensor
D:\ZTest>cd temp_sensor
D:\ZTest\temp_sensor>ceedling test:all
D:\ZTest\temp_sensor>ruby vendor\ceedling\bin\ceedling test:all


Test 'TestAdcConductor.c'
-------------------------
ERROR: Shell command failed.
> Shell executed command:
'gcc.exe -E -MM -MG -I"test" -I"test/support" -I"src" -I"D:/ZTest/temp_sensor/vendor/ceedling/vendor/unity/src" -I"D:/ZTest/temp_sensor/vendor/ceedling/vendor/cmock/src"
-I"build/test/mocks" -DTEST -DTEST -DGNU_COMPILER -w "build/temp/_TestAdcConductor.c"'
> And exited with status: [1].

rake aborted!
ShellExecutionException: ShellExecutionException
D:/ZTest/temp_sensor/vendor/ceedling/lib/ceedling/tool_executor.rb:82:in `exec'
D:/ZTest/temp_sensor/vendor/ceedling/lib/ceedling/preprocessinator_includes_handler.rb:45:in `form_shallow_dependencies_rule'
D:/ZTest/temp_sensor/vendor/ceedling/lib/ceedling/preprocessinator.rb:31:in `preprocess_shallow_includes'
D:/ZTest/temp_sensor/vendor/ceedling/lib/ceedling/preprocessinator.rb:11:in `block in setup'
D:/ZTest/temp_sensor/vendor/ceedling/lib/ceedling/preprocessinator_helper.rb:11:in `preprocess_includes'
D:/ZTest/temp_sensor/vendor/ceedling/lib/ceedling/preprocessinator.rb:17:in `preprocess_test_and_invoke_test_mocks'
D:/ZTest/temp_sensor/vendor/ceedling/lib/ceedling/test_invoker.rb:89:in `block in setup_and_invoke'
D:/ZTest/temp_sensor/vendor/ceedling/lib/ceedling/test_invoker.rb:63:in `setup_and_invoke'
D:/ZTest/temp_sensor/vendor/ceedling/lib/ceedling/tasks_tests.rake:11:in `block (2 levels) in <top (required)>'
vendor/ceedling/bin/ceedling:311:in `block in <main>'
vendor/ceedling/bin/ceedling:298:in `<main>'
Tasks: TOP => test:all
(See full trace by running task with --trace)
ERROR: Ceedling Failed
```

I am not sure what is the problem.

**Comment by mvandervoord** [comment]
gcc gave you an error, but for some reason it didn't say why. 

Can you try it this way and see if it tells you more?

```
ceedling verbosity[4] test:all
```

**Comment by fahad80** [comment]
Ran that but it is showing the same output. As you said its the gcc so I ran the gcc part and this is what I got:

```
D:\ZTest\temp_sensor>gcc.exe -E -MM -MG -I"test" -I"test/support" -I"src" -I"D:/ZTest/temp_sensor/vendor/ceedling/vendor/unity/src" -I"D:/ZTest/temp_sensor/vendor/ceedlin
g/vendor/cmock/src" -I"build/test/mocks" -DTEST -DTEST -DGNU_COMPILER -w "build/temp/_TestAdcConductor.c"
gcc.exe: error: build/temp/_TestAdcConductor.c: No such file or directory
gcc.exe: fatal error: no input files
compilation terminated.
```

**Comment by mvandervoord** [comment]
Two things worth trying:
(1) If you manually create the build/temp directory, does everything proceed as desired?
(2) I think you have preprocessing turned on. If you disable that, does everything proceed as desired?

**Comment by fahad80** [comment]
@mvandervoord I think I figured it out. When I manually created "_TestAdcConductor.c" in build/temp/ gcc threw me "libgmp-10.dll missing" error. Once I installed that, I was able to execute "ceedling test:all".

Thank you very much. I will close the issue.
