### ISSUE TITLE
Multi-threading doesn't seem to do much

### ISSUE THREAD

**Issue by Miv13** [ThrowTheSwitch/Ceedling#309]
I'm not sure if it's an actual issue, but increasing the number of threads in YAML file doesn't seem to make much difference. When running my tests with:
`  :compile_threads: 1
  :test_threads: 1`
they take approx. 4 minutes. If I switch both to 8, they take approx. 3 min 30 sec or more. I kind of expected that the difference would be more significant.
Is this normal (is multi-threading simply not very efficient in case of ceedling)?

**Comment by Miv13** [comment]
I also noticed that allowing multiple threads has an impact (and a negative one) on displaying information when something goes wrong with the tests. Here's a few lines from console in such a case:

```
Compiling mock_dbc_assert.c...
cCompiling mock_log.c...c
1.exe: fatal error: build/test/out/c/test_unit_flashdrv_runner.d: No such filcc1.exe: fatal error: build/test/out/c/test_unit_fleas hodrr vd.id:r eNco such file or directory
compoirCompiling FreeRTOS_mock.c...
ly
tcioomnp itCompiling assert_mock.c...c
clCompiling at45db_mock.c...1
.eexe: fatal error: build/test/out/c/mock_spi.d: No such file or directory
compilation termainated.
rtcmc1.exe: fatal error: build/testERROR: Shell command failed.
> Shell executed command:
'gcc.exe -DSTATIC= -o "attributes_for_tests.h" -I"test" -I"test/shared" -I"test/shared/bsw" -I"test/sources" -I"test/sources/bsw" -I"test/support/loops" -I"test/support" -I"test/support/loops" -I"../sources/os" -I".." -I"../bootloader" -I"../bootloader/cubemx" -I"../bootloader/linker" -I"../bootloader/objects" -I"../bootloader/sources" -I"../bootloader/sources/app" -I"../bootloader/sources/bsw" -I"../bootloader/sources/bsw/mcal" -I"../bootloader/sources/cubemx" -I"../bootloader/sources/cubemx/Drivers" -I"../bootloader/sources/cubemx/Drivers/CMSIS" -I"../bootloader/sources/cubemx/Drivers/CMSIS/Device" -I"../bootloader/sources/cubemx/Drivers/CMSIS/Device/ST" -I"../bootloader/sources/cubemx/Drivers/CMSIS/Device/ST/STM32F4xx" -I"../bootloader/sources/cubemx/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"../bootloader/sources/cubemx/Drivers/CMSIS/Device/ST/STM32F4xx/Source" -I"../bootloader/sources/cubemx/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates" -I"../bootloader/sources/cubemx/Drivers/CMSIS/Include" -I"../bootloader/sources/cubemx/Drivers/STM32F4xx_HAL_Driver" -I"../bootloader/sources/cubemx/Drivers/STM32F4xx_HAL_Driver/Inc" -I"../bootloader/sources/cubemx/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"../bootloader/sources/cubemx/Drivers/STM32F4xx_HAL_Driver/Src" -I"../bootloader/sources/cubemx/Inc" -I"../bootloader/sources/cubemx/Src" -I"../bootloader/sources/os" -I"../bootloader/target" -I"../bootmanager" -I"../bootmanager/cubemx" -I"../bootmanager/linker" -I"../bootmanager/objects" -I"../bootmanager/sources" -I"../bootmanager/sources/cubemx" -I"../bootmanager/sources/cubemx/Driv/oers" -I"../bootmanager/sources/cubemx/Drivers/CMSIS" -I"../bootmanager/sources/cubemx/Drivers/CMSIS/Device" -I"../bootmanager/sources/cubemx/Drivers/CMSIS/Device/ST" -I"../bootmanager/sources/cubemx/Drivers/CMSIS/Device/ST/STM32F4xx" -I"../bootmanager/sources/cubemx/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"../bootmanager/sources/cubemx/Drivers/CMSIS/Device/ST/STM32F4xx/Source" -I"../bootmanager/sources/cubemx/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates" -I"../bootmanager/sources/cubemx/Drivers/CMSIS/Include" -I"../bootmanager/sources/cubemx/Drivers/STM32F4xx_HAL_Driver" -I"../bootmanager/sources/cubemx/Drivers/STM32F4xx_HAL_Driver/Inc" -I"../bootmanager/sources/cubemx/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"../bootmanager/sources/cubemx/Drivers/STM32F4xx_HAL_Driver/Src" -I"../bootmanager/sources/cubemx/Inc" -I"../bootmanager/sources/cubemx/Src" -I"../bootmanager/target" -I"../build" -I"../cubemx" -I"../documents" -I"../documents/codestyle" -I"../documents/datasheets" -I"../documents/layout_and_schematics" -I"../documents/layout_and_schematics/V02_05" -I"../documents/specifications" -I"../linker" -I"../objects" -I"../shared" -I"../shared/app" -I"../shared/bsw" -I"../shared/bsw/com" -I"../shared/bsw/mcal" -I"../shared/free_rtos" -I"../shared/free_rtos/include" -I"../shared/free_rtos/portable" -I"../shared/utils" -I"../sources" -I"../sources/app" -I"../sources/app/http_server" -I"../sources/bsw" -I"../sources/bsw/com" -I"../sources/bsw/com/childboard" -I"../sources/bsw/com/childboard/msg_sensor_data" -I"../sources/bsw/com/cloud" -I"../sources/bsw/com/ethernet" -I"../sources/bsw/com/ethernet/w5500" -I"../sources/bsw/com/internet" -I"../sources/bsw/com/internet/dhcp" -I"../sources/bsw/com/internet/dns" -I"../sources/bsw/com/internet/sntp" -I"../sources/bsw/mcal" -I"../sources/cubemx" -I"../sources/cubemx/Drivers" -I"../sources/cubemx/Drivers/CMSIS" -I"../sources/cubemx/Drivers/CMSIS/Device" -I"../sources/cubemx/Drivers/CMSIS/Device/ST" -I"../sources/cubemx/Drivers/CMSIS/Device/ST/STM32F4xx" -I"../sources/cubemx/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"../sources/cubemx/Drivers/CMSIS/Device/ST/STM32F4xx/Source" -I"../sources/cubemx/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates" -I"../sources/cubemx/Drivers/CMSIS/Include" -I"../sources/cubemx/Drivers/STM32F4xx_HAL_Driver" -I"../sources/cubemx/Drivers/STM32F4xx_HAL_Driver/Inc" -I"../sources/cubemx/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"../sources/cubemx/Drivers/STM32F4xx_HAL_Driver/Src" -I"../sources/cubemx/Inc" -I"../sources/cubemx/Src" -I"../sources/os" -I"../target" -I"../testsources" -I"../testsources/stubs" -I"../testsources/stubs/inc" -I"../testsources/stubs/src" -I"../tools" -I"../tools/yahdlc" -I"C:/Works/EclipseC/testy/swgatewaymf4/tests/vendor/ceedling/vendor/unity/src" -I"C:/Works/EclipseC/testy/swgatewaymf4/tests/vendor/ceedlingu/vendor/c_exception/lib" -I"C:/Works/EclipseC/testy/swgatewaymf4/tests/vendor/ceedling/vendor/cmock/src" -I"build/test/mocks" -DUNIT_TESTS -DSTM32F401xE -DTEST -DGNU_COMPILER -g -c "build/test/mocks/mock_spi.c" -o "build/test/out/c/mock_spi.o" -MMD -MF "build/test/dependencies/mock_spi.d"'
> And exited with status: [1].

t/#<Thread:0x00000000063df508@C:/Works/EclipseC/testy/swgatewaymf4/tests/vendor/ceedling/lib/ceedling/par_map.rb:7 run> terminated with exception (report_on_exception is true):
ccTraceback/ (most recent call last):
m       o11: from C:/Works/EclipseC/testy/swgatewaymf4/tests/vendor/ceedling/lib/ceedling/par_map.rb:10:in `block (2 levels) in par_map'
c       10: from C:/Works/EclipseC/testy/swgatewaymf4/tests/vendor/ceedling/lib/ceedling/task_invoker.rb:80:in `block in invoke_test_objects'
k       _ 9: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:181:in `invoke'
l        8: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
og       7: from C:/Ruby25-x64/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
.        6: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
di      : 5: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
         4: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
N       o 3: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
         2: from C:/Works/EclipseC/testy/swgatewaymf4/tests/vendor/ceedling/lib/ceedling/rules_tests.rake:17:in `block in <top (required)>'
s       u 1: from C:/Works/EclipseC/testy/swgatewaymf4/tests/vendor/ceedling/lib/ceedling/generator.rb:96:in `generate_object_file'
cC:/Works/EclipseC/testy/swgatewaymf4/tests/vendor/ceedling/lib/ceedling/tool_executor.rb:82:in `exec'h:  fShellExecutionExceptioni (leShellExecutionException or)
 directoryci
comnpilation termina1ted.
oa.ERROR: Shell command failed.
```

I don't know whether you were aware of it and whether anything can be done about it, but thought I'd post it just in case...

**Comment by rasup** [comment]
Have you tried `rake`'s multitask option?

I looked a bit into it a while ago and I don't think `:test_threads:` is actually used for anything.

...just stumbled upon [this issue](https://github.com/ThrowTheSwitch/Ceedling/issues/118#issuecomment-331719290) and pJunger's patch seems to make it behave more like what you'd expect.

**Comment by Miv13** [comment]
@rasup 
Sadly, I don't think it is compatible with the current version of ceedling (I'm using 0.28.3).

**Comment by mkarlesky** [comment]
Ceedling 1.0.0 has proper support for multi-threaded builds and logs progress properly as well.
