### ISSUE TITLE
Example test_sensor does not work

### ISSUE THREAD

**Issue by Oliverleo123** [ThrowTheSwitch/Ceedling#340]
The temp_sensor example fails after a few tests.

Im getting the following error:

> Shell executed command:
'gcc.exe -E -I"test" -I"test/support" -I"src" -I"C:/Ceedling/temp_sensor/vendor/ceedling/vendor/unity/src" -I"C:/Ceedling/temp_sensor/vendor/ceedling/vendor/cmock/src" -I"build/test/mocks" -DTEST -DTEST -DGNU_COMPILER "test/TestTaskScheduler.c" -o "build/test/preprocess/files/TestTaskScheduler.c"'

Running TestTaskScheduler.exe...
> Shell executed command:
'build\test\out\TestTaskScheduler.exe 2>&1'
> And exited with status: [].

ERROR: Test executable "TestTaskScheduler.exe" failed.
> Produced no output to $stdout.
> And exited with status: [0] (count of failed tests).
> This is often a symptom of a bad memory access in source or test code.

rake aborted!

C:/Ceedling/temp_sensor/vendor/ceedling/lib/ceedling/generator_helper.rb:36:in `test_results_error_handler'
C:/Ceedling/temp_sensor/vendor/ceedling/lib/ceedling/generator.rb:163:in `generate_test_results'
C:/Ceedling/temp_sensor/vendor/ceedling/lib/ceedling/rules_tests.rake:56:in `block in <top (required)>'
C:/Ceedling/temp_sensor/vendor/ceedling/lib/ceedling/task_invoker.rb:86:in `invoke_test_results'
C:/Ceedling/temp_sensor/vendor/ceedling/lib/ceedling/test_invoker.rb:123:in `block in setup_and_invoke'
C:/Ceedling/temp_sensor/vendor/ceedling/lib/ceedling/test_invoker.rb:63:in `setup_and_invoke'
C:/Ceedling/temp_sensor/vendor/ceedling/lib/ceedling/tasks_tests.rake:11:in `block (2 levels) in <top (required)>'
vendor/ceedling/bin/ceedling:311:in `block in <main>'
vendor/ceedling/bin/ceedling:298:in `<main>'
Tasks: TOP => build/test/results/TestTaskScheduler.pass
(See full trace by running task with --trace)

--------------------
OVERALL TEST SUMMARY
--------------------
TESTED:  19
PASSED:  19
FAILED:   0
IGNORED:  0

Im using the original example. In the project.yml I changed :extension: :executable: .out to .exe
since im running on windows

**Comment by Oliverleo123** [comment]
solved by installing the newest MinGW package
