### ISSUE TITLE
FrozenError: can't modify frozen String

### ISSUE THREAD

**Issue by IvanRibakov** [ThrowTheSwitch/Ceedling#388]
Running tests without logging works as expected, however if I enable it, Ceedling test run fails with following message:

```
rake aborted!
FrozenError: can't modify frozen String
<project_root>/vendor/ceedling/lib/ceedling/tool_executor.rb:79:in `scrub!'
<project_root>/vendor/ceedling/lib/ceedling/tool_executor.rb:79:in `exec'
<project_root>/vendor/ceedling/lib/ceedling/generator.rb:166:in `generate_test_results'
<project_root>/vendor/ceedling/lib/ceedling/rules_tests.rake:55:in `block in <top (required)>'
<project_root>/vendor/ceedling/lib/ceedling/task_invoker.rb:86:in `invoke_test_results'
<project_root>/vendor/ceedling/lib/ceedling/test_invoker.rb:136:in `block in setup_and_invoke'
<project_root>/vendor/ceedling/lib/ceedling/test_invoker.rb:76:in `each'
<project_root>/vendor/ceedling/lib/ceedling/test_invoker.rb:76:in `setup_and_invoke'
<project_root>/vendor/ceedling/lib/ceedling/rules_tests.rake:70:in `block (2 levels) in <top (required)>'
vendor/ceedling/bin/ceedling:332:in `block in <main>'
vendor/ceedling/bin/ceedling:319:in `<main>'
```

Logging macros look as follows:
```
#define LM_DBG(fmt, ...) if(LOG_ON) { printf(fmt, ##__VA_ARGS__); }
#define LM_INFO(fmt, ...) if(LOG_ON) { printf(fmt, ##__VA_ARGS__); }
```

Any idea what might be causing this?

```
$ ruby -v
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
```

**Comment by congtmbg** [comment]
I have same problem.
My OS: ubuntu 18.04.3 LTS.
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
  Ceedling:: 0.28.3
CException:: 1.3.1.18
     CMock:: 2.4.6.217
     Unity:: 2.4.3.122
Dear Mark Vander Voord,
Please check it!
Thank you so much!

**Comment by IvanRibakov** [comment]
In my case the issue was caused by attempting to print non null-terminated string. Thankfully I'm in the process of migrating unit tests from Unity to Ceedling so I was able to use the old test suite for debugging and find the offending string.

**Comment by congtmbg** [comment]
Dear Ivan Ribakov,
Thank you. I'll check my source code.

**Comment by mvandervoord** [comment]
Thank you. fixed.
