### ISSUE TITLE
Test executable failed when defined UNITY_OUTPUT_COLOR

### ISSUE THREAD

**Issue by stsymbaliuk** [ThrowTheSwitch/Ceedling#401]
```
ceedling version
Welcome to Ceedling!
  Ceedling::   0.28.3
  CMock::      2.4.5
  Unity::      2.4.2
  CException:: 1.3.1
  
ruby -v
ruby 2.5.5p157 (2019-03-15 revision 67260) [x64-mingw32]
```

Want to get colored PASS and FAIL marks in Unity test result.

Steps to reproduce:
1. Create empty module.

2. Add UNITY_OUTPUT_COLOR to project.yml defines section so it starts look like:

```
:defines:
  # in order to add common defines:
  #  1) remove the trailing [] from the :common: section
  #  2) add entries to the :common: section (e.g. :test: has TEST defined)
  :commmon: &common_defines []
  :test:
    - *common_defines
    - TEST
    - UNITY_OUTPUT_COLOR
  :test_preprocess:
    - *common_defines
    - TEST
```

3. Run test. Output for Windows 10. Same results when try on Ubuntu.

```
e:\Work\Programming\test_ceedling>ruby vendor\ceedling\bin\ceedling test:all


Test 'test_some_module.c'
-------------------------
Compiling test_some_module_runner.c...
Compiling test_some_module.c...
Compiling unity.c...
Compiling some_module.c...
Compiling cmock.c...
Linking test_some_module.out...
Running test_some_module.out...

ERROR: Test executable "test_some_module.out" failed.
> Produced no final test result counts in $stdout:
test_some_module.c:16:test_some_module_NeedToImplement:IGNORE: Need to Implement some_module

-----------------------
1 Tests 0 Failures 1 Ignored
OK
> And exited with status: [0] (count of failed tests).
> This is often a symptom of a bad memory access in source or test code.

rake aborted!

e:/Work/Programming/test_ceedling/vendor/ceedling/lib/ceedling/generator_helper.rb:36:in `test_results_error_handler'
e:/Work/Programming/test_ceedling/vendor/ceedling/lib/ceedling/generator.rb:163:in `generate_test_results'
e:/Work/Programming/test_ceedling/vendor/ceedling/lib/ceedling/rules_tests.rake:56:in `block in <top (required)>'
e:/Work/Programming/test_ceedling/vendor/ceedling/lib/ceedling/task_invoker.rb:86:in `invoke_test_results'
e:/Work/Programming/test_ceedling/vendor/ceedling/lib/ceedling/test_invoker.rb:123:in `block in setup_and_invoke'
e:/Work/Programming/test_ceedling/vendor/ceedling/lib/ceedling/test_invoker.rb:63:in `setup_and_invoke'
e:/Work/Programming/test_ceedling/vendor/ceedling/lib/ceedling/tasks_tests.rake:11:in `block (2 levels) in <top (required)>'
vendor/ceedling/bin/ceedling:311:in `block in <main>'
vendor/ceedling/bin/ceedling:298:in `<main>'
Tasks: TOP => build/test/results/test_some_module.pass
(See full trace by running task with --trace)

--------------------
OVERALL TEST SUMMARY
--------------------

No tests executed.
```

When UNITY_OUTPUT_COLOR removed from defines test runs as expected:

```
e:\Work\Programming\test_ceedling>ruby vendor\ceedling\bin\ceedling test:all


Test 'test_some_module.c'
-------------------------
Generating runner for test_some_module.c...
Compiling test_some_module_runner.c...
Compiling test_some_module.c...
Compiling unity.c...
Compiling some_module.c...
Compiling cmock.c...
Linking test_some_module.out...
Running test_some_module.out...

--------------------
IGNORED TEST SUMMARY
--------------------
[test_some_module.c]
  Test: test_some_module_NeedToImplement
  At line (16): "Need to Implement some_module"

--------------------
OVERALL TEST SUMMARY
--------------------
TESTED:  1
PASSED:  0
FAILED:  0
IGNORED: 1
```
![test_failed](https://user-images.githubusercontent.com/44534615/67150436-1f0b7d00-f2c0-11e9-92a1-30efc2543043.png)

**Comment by JuPrgn** [comment]
@stsymbaliuk I have the same issue with this option activated. 

Ceedling doesn't seem to implement this colored option (only found on Unity files) but I think there is something to do with `TEST_STDOUT_STATISTICS_PATTERN  = /\n-+\s*(\d+)\s+Tests\s+(\d+)\s+Failures\s+(\d+)\s+Ignored\s+(OK|FAIL)\s*/i`

When the color output is activated, the test output files doesn't correspond to the pattern anymore. 

In `generator_test_results.rb` : 
I suppose that there is a conversion error `results[:counts][:failed]  = $2.to_i` is `>0` when failed is equal to 0 and the color syntax `"\033[42m` 0 `033[00m";` is used.

**Comment by mvandervoord** [comment]
Fixed

**Comment by stsymbaliuk** [comment]
@mvandervoord 
> If we want colors from ceedling, use ceedling's features directly

What is the right way to get colors in console when multiple tests are running with Ceedling and few of them are failed? It is much easier to find red test results as Unity can provide. Web search gives on some weird `stdout_colour_tests_report` but it isn't working. CeedlingPacket.md also gives no answer.

**Comment by mvandervoord** [comment]
You tried the :colour_report plugin and it's not working?

**Comment by stsymbaliuk** [comment]
What I've done:

1. Create new project:

`ceedling new test_ceedling1`

2. Add new nodule:

`ceedling module:create[some_module]`

3. Add `- colour_report` to `:plugins` section:

Result for `- colour_report`:

```
e:\Work\Programming\test_ceedling1>ruby vendor\ceedling\bin\ceedling
ERROR: Ceedling plugin 'colour_report' contains no rake or ruby class entry point. (Misspelled or missing files?)
Traceback (most recent call last):
        5: from vendor/ceedling/bin/ceedling:295:in `<main>'
        4: from vendor/ceedling/lib/ceedling.rb:66:in `load_project'
        3: from vendor/ceedling/lib/ceedling.rb:66:in `load'
        2: from vendor/ceedling/lib/../lib/ceedling/rakefile.rb:48:in `<top (required)>'
        1: from e:/Work/Programming/test_ceedling1/vendor/ceedling/lib/ceedling/setupinator.rb:32:in `do_setup'
e:/Work/Programming/test_ceedling1/vendor/ceedling/lib/ceedling/configurator.rb:287:in `validate': unhandled exception
```

4. Also tryed to add `- colour_reporter` as I saw `colour_reporter.rb` file in `vendor` folder but it also doesn work.
Result for `- colour_reporter`:
```
e:\Work\Programming\test_ceedling1>ruby vendor\ceedling\bin\ceedling
ERROR: Ceedling plugin 'colour_reporter' contains no rake or ruby class entry point. (Misspelled or missing files?)
Traceback (most recent call last):
        5: from vendor/ceedling/bin/ceedling:295:in `<main>'
        4: from vendor/ceedling/lib/ceedling.rb:66:in `load_project'
        3: from vendor/ceedling/lib/ceedling.rb:66:in `load'
        2: from vendor/ceedling/lib/../lib/ceedling/rakefile.rb:48:in `<top (required)>'
        1: from e:/Work/Programming/test_ceedling1/vendor/ceedling/lib/ceedling/setupinator.rb:32:in `do_setup'
e:/Work/Programming/test_ceedling1/vendor/ceedling/lib/ceedling/configurator.rb:287:in `validate': unhandled exception
```

5. Without adding that lines to `project.yml` I get normal results of test execution:
```
e:\Work\Programming\test_ceedling1>ruby vendor\ceedling\bin\ceedling

Test 'test_some_module.c'
-------------------------
Running test_some_module.out...

--------------------
IGNORED TEST SUMMARY
--------------------
[test_some_module.c]
  Test: test_some_module_NeedToImplement
  At line (14): "Need to Implement some_module"

--------------------
OVERALL TEST SUMMARY
--------------------
TESTED:  1
PASSED:  0
FAILED:  0
IGNORED: 1
```
![color_reporter_project](https://user-images.githubusercontent.com/44534615/67610159-9a29d300-f799-11e9-9c3f-41bb5370a78f.png)
![ceedling_run](https://user-images.githubusercontent.com/44534615/67610162-9e55f080-f799-11e9-8a82-bb6e06d9f002.png)

**Comment by dpostorivo** [comment]
The colour reporter is not available in the ceedling 0.28.3 release.  It
was added after that release specifically in #318.

You will also need to disable the pretty out for it to work, but it should
not crash like that if it's used. The crash just looks like it's not there
which is expected at this version.  Can you list the directories in plugin
to confirm?

**Comment by stsymbaliuk** [comment]
List of my project directory with `tree` command:
```
e:\Work\Programming\test_ceedling1>tree /F /A

Folder PATH listing
E:.
|   .gitignore
|   ceedling.cmd
|   project.yml
|   tree.txt
|   
+---build
|   +---artifacts
|   +---logs
|   +---temp
|   \---test
+---src
|       some_module.c
|       some_module.h
|       
+---test
|   |   test_some_module.c
|   |   
|   \---support
\---vendor
    \---ceedling
        +---bin
        |       ceedling
        |       
        +---docs
        |       CeedlingPacket.md
        |       CException.md
        |       CMock_Summary.md
        |       ThrowTheSwitchCodingStandard.md
        |       UnityAssertionsCheatSheetSuitableforPrintingandPossiblyFraming.pdf
        |       UnityAssertionsReference.md
        |       UnityConfigurationGuide.md
        |       UnityGettingStartedGuide.md
        |       UnityHelperScriptsGuide.md
        |       
        +---lib
        |   |   ceedling.rb
        |   |   
        |   \---ceedling
        |           build_invoker_utils.rb
        |           cacheinator.rb
        |           cacheinator_helper.rb
        |           cmock_builder.rb
        |           configurator.rb
        |           configurator_builder.rb
        |           configurator_plugins.rb
        |           configurator_setup.rb
        |           configurator_validator.rb
        |           constants.rb
        |           defaults.rb
        |           dependinator.rb
        |           erb_wrapper.rb
        |           file_finder.rb
        |           file_finder_helper.rb
        |           file_path_utils.rb
        |           file_system_utils.rb
        |           file_system_wrapper.rb
        |           file_wrapper.rb
        |           flaginator.rb
        |           generator.rb
        |           generator_helper.rb
        |           generator_test_results.rb
        |           generator_test_results_sanity_checker.rb
        |           generator_test_runner.rb
        |           loginator.rb
        |           makefile.rb
        |           objects.yml
        |           par_map.rb
        |           plugin.rb
        |           plugin_builder.rb
        |           plugin_manager.rb
        |           plugin_manager_helper.rb
        |           plugin_reportinator.rb
        |           plugin_reportinator_helper.rb
        |           preprocessinator.rb
        |           preprocessinator_extractor.rb
        |           preprocessinator_file_handler.rb
        |           preprocessinator_helper.rb
        |           preprocessinator_includes_handler.rb
        |           project_config_manager.rb
        |           project_file_loader.rb
        |           rakefile.rb
        |           rake_utils.rb
        |           rake_wrapper.rb
        |           release_invoker.rb
        |           release_invoker_helper.rb
        |           reportinator.rb
        |           rules_cmock.rake
        |           rules_preprocess.rake
        |           rules_release.rake
        |           rules_release_deep_dependencies.rake
        |           rules_tests.rake
        |           rules_tests_deep_dependencies.rake
        |           setupinator.rb
        |           streaminator.rb
        |           streaminator_helper.rb
        |           stream_wrapper.rb
        |           system_utils.rb
        |           system_wrapper.rb
        |           target_loader.rb
        |           tasks_base.rake
        |           tasks_filesystem.rake
        |           tasks_release.rake
        |           tasks_release_deep_dependencies.rake
        |           tasks_tests.rake
        |           tasks_tests_deep_dependencies.rake
        |           tasks_vendor.rake
        |           task_invoker.rb
        |           test_includes_extractor.rb
        |           test_invoker.rb
        |           test_invoker_helper.rb
        |           tool_executor.rb
        |           tool_executor_helper.rb
        |           verbosinator.rb
        |           version.rb
        |           version.rb.erb
        |           yaml_wrapper.rb
        |           _generator_test_results.rb
        |           
        +---plugins
        |   +---beep
        |   |   |   README.md
        |   |   |   
        |   |   \---lib
        |   |           beep.rb
        |   |           
        |   +---bullseye
        |   |   |   bullseye.rake
        |   |   |   readme.txt
        |   |   |   
        |   |   +---assets
        |   |   |       template.erb
        |   |   |       
        |   |   +---config
        |   |   |       defaults.yml
        |   |   |       
        |   |   \---lib
        |   |           bullseye.rb
        |   |           
        |   +---command_hooks
        |   |   |   README.md
        |   |   |   
        |   |   \---lib
        |   |           command_hooks.rb
        |   |           
        |   +---fake_function_framework
        |   |   |   Rakefile
        |   |   |   README.md
        |   |   |   
        |   |   +---examples
        |   |   |   \---fff_example
        |   |   |       |   project.yml
        |   |   |       |   rakefile.rb
        |   |   |       |   
        |   |   |       +---src
        |   |   |       |   |   bar.c
        |   |   |       |   |   bar.h
        |   |   |       |   |   custom_types.h
        |   |   |       |   |   display.c
        |   |   |       |   |   display.h
        |   |   |       |   |   event_processor.c
        |   |   |       |   |   event_processor.h
        |   |   |       |   |   foo.c
        |   |   |       |   |   foo.h
        |   |   |       |   |   
        |   |   |       |   \---subfolder
        |   |   |       |           zzz.c
        |   |   |       |           zzz.h
        |   |   |       |           
        |   |   |       \---test
        |   |   |               test_event_processor.c
        |   |   |               test_foo.c
        |   |   |               
        |   |   +---lib
        |   |   |       fake_function_framework.rb
        |   |   |       fff_mock_generator.rb
        |   |   |       
        |   |   +---spec
        |   |   |       fff_mock_header_generator_spec.rb
        |   |   |       fff_mock_source_generator_spec.rb
        |   |   |       header_generator.rb
        |   |   |       spec_helper.rb
        |   |   |       
        |   |   \---src
        |   |           fff_unity_helper.h
        |   |           
        |   +---gcov
        |   |   |   gcov.rake
        |   |   |   README.md
        |   |   |   
        |   |   +---assets
        |   |   |       template.erb
        |   |   |       
        |   |   +---config
        |   |   |       defaults.yml
        |   |   |       
        |   |   \---lib
        |   |           gcov.rb
        |   |           gcov_constants.rb
        |   |           
        |   +---junit_tests_report
        |   |   \---lib
        |   |           junit_tests_report.rb
        |   |           
        |   +---module_generator
        |   |   |   module_generator.rake
        |   |   |   
        |   |   +---config
        |   |   |       module_generator.yml
        |   |   |       
        |   |   \---lib
        |   |           module_generator.rb
        |   |           
        |   +---raw_output_report
        |   |   \---lib
        |   |           raw_output_report.rb
        |   |           
        |   +---stdout_gtestlike_tests_report
        |   |   +---assets
        |   |   |       template.erb
        |   |   |       template.erb copy
        |   |   |       
        |   |   +---config
        |   |   |       stdout_gtestlike_tests_report.yml
        |   |   |       
        |   |   \---lib
        |   |           stdout_gtestlike_tests_report.rb
        |   |           
        |   +---stdout_ide_tests_report
        |   |   +---config
        |   |   |       stdout_ide_tests_report.yml
        |   |   |       
        |   |   \---lib
        |   |           stdout_ide_tests_report.rb
        |   |           
        |   +---stdout_pretty_tests_report
        |   |   +---assets
        |   |   |       template.erb
        |   |   |       
        |   |   +---config
        |   |   |       stdout_pretty_tests_report.yml
        |   |   |       
        |   |   \---lib
        |   |           stdout_pretty_tests_report.rb
        |   |           
        |   +---subprojects
        |   |   |   README.md
        |   |   |   subprojects.rake
        |   |   |   
        |   |   +---config
        |   |   |       defaults.yml
        |   |   |       
        |   |   \---lib
        |   |           subprojects.rb
        |   |           
        |   +---teamcity_tests_report
        |   |   +---config
        |   |   |       teamcity_tests_report.yml
        |   |   |       
        |   |   \---lib
        |   |           teamcity_tests_report.rb
        |   |           
        |   +---warnings_report
        |   |   \---lib
        |   |           warnings_report.rb
        |   |           
        |   \---xml_tests_report
        |       \---lib
        |               xml_tests_report.rb
        |               
        \---vendor
            +---cmock
            |   +---config
            |   |       production_environment.rb
            |   |       test_environment.rb
            |   |       
            |   +---lib
            |   |       cmock.rb
            |   |       cmock_config.rb
            |   |       cmock_file_writer.rb
            |   |       cmock_generator.rb
            |   |       cmock_generator_plugin_array.rb
            |   |       cmock_generator_plugin_callback.rb
            |   |       cmock_generator_plugin_cexception.rb
            |   |       cmock_generator_plugin_expect.rb
            |   |       cmock_generator_plugin_expect_any_args.rb
            |   |       cmock_generator_plugin_ignore.rb
            |   |       cmock_generator_plugin_ignore_arg.rb
            |   |       cmock_generator_plugin_return_thru_ptr.rb
            |   |       cmock_generator_utils.rb
            |   |       cmock_header_parser.rb
            |   |       cmock_plugin_manager.rb
            |   |       cmock_unityhelper_parser.rb
            |   |       
            |   +---release
            |   |       build.info
            |   |       version.info
            |   |       
            |   \---src
            |           cmock.c
            |           cmock.h
            |           cmock_internals.h
            |           
            +---c_exception
            |   +---lib
            |   |       CException.c
            |   |       CException.h
            |   |       
            |   \---release
            |           build.info
            |           version.info
            |           
            +---deep_merge
            |   \---lib
            |           deep_merge.rb
            |           
            +---diy
            |   \---lib
            |       |   diy.rb
            |       |   
            |       \---diy
            |               factory.rb
            |               
            \---unity
                +---auto
                |       colour_prompt.rb
                |       colour_reporter.rb
                |       generate_config.yml
                |       generate_module.rb
                |       generate_test_runner.rb
                |       parse_output.rb
                |       stylize_as_junit.rb
                |       test_file_filter.rb
                |       type_sanitizer.rb
                |       unity_test_summary.py
                |       unity_test_summary.rb
                |       unity_to_junit.py
                |       
                +---release
                |       build.info
                |       version.info
                |       
                \---src
                        unity.c
                        unity.h
                        unity_internals.h
                        
```

Archived project folder:
[test_ceedling1.zip](https://github.com/ThrowTheSwitch/Ceedling/files/3774187/test_ceedling1.zip)

**Comment by dpostorivo** [comment]
Yeah you don't have the colour_report plugin so ceedling won't know about
it.

The next release will have it.
