### ISSUE TITLE
printf in 2nd+ tests causes failure of test count sanity check

### ISSUE THREAD

**Issue by zanedp** [ThrowTheSwitch/Ceedling#41]
Make a new project with `ceedling new`, then create a new test module containing more than one test routine. In any routine other than the first, put a printf either in the test fixture or the code under test. Sanity check will fail because the test count will not match.

Example test code:

```
#include <stdio.h>
#include "unity.h"


void setUp(void)
{

}

void tearDown(void)
{

}

void test_a(void)
{

}

// Move this before test_a or remove the printf and ceedling doesn't fail its sanity check.
void test_b(void)
{
   printf("hello\n");
}
```

Error message:

```
Test 'test_ceedling_error.c'
----------------------------
Generating runner for test_ceedling_error.c...
Compiling test_ceedling_error_runner.c...
Compiling test_ceedling_error.c...
Compiling unity.c...
Compiling cmock.c...
Linking test_ceedling_error.out...
Running test_ceedling_error.out...

ERROR: Internal sanity check for test fixture 'test_ceedling_error.out' finds that Unity's final test count (2) does not match Ceedling's summation of all test cases (1).
  Possible causes:
    1. Your test + source dereferenced a null pointer.
    2. Your test + source indexed past the end of a buffer.
    3. Your test + source committed a memory access violation.
    4. Your test fixture produced an exit code of 0 despite execution ending prematurely.
  Sanity check failures of test results are usually a symptom of interrupted test execution.

rake aborted!

.../ceedling_error/vendor/ceedling/lib/ceedling/generator_test_results_sanity_checker.rb:60:in `sanity_check_warning'
.../ceedling_error/vendor/ceedling/lib/ceedling/generator_test_results_sanity_checker.rb:41:in `verify'
.../ceedling_error/vendor/ceedling/lib/ceedling/generator_test_results.rb:49:in `process_and_write_results'
.../ceedling_error/vendor/ceedling/lib/ceedling/generator.rb:153:in `generate_test_results'
.../ceedling_error/vendor/ceedling/lib/ceedling/rules_tests.rake:41:in `block in <top (required)>'

.../ceedling_error/vendor/ceedling/lib/ceedling/task_invoker.rb:74:in `invoke_test_results'
.../ceedling_error/vendor/ceedling/lib/ceedling/test_invoker.rb:68:in `block in setup_and_invoke' .../ceedling_error/vendor/ceedling/lib/ceedling/test_invoker.rb:32:in `setup_and_invoke'
.../Code/ceedling_error/vendor/ceedling/lib/ceedling/tasks_tests.rake:8:in `block (2 levels) in <top (required)>'
Tasks: TOP => build/test/results/test_ceedling_error.pass
(See full trace by running task with --trace)

--------------------
OVERALL TEST SUMMARY
--------------------

No tests executed.

```

It looks like the stdout from the 2nd test's output is getting squished up next to the "PASS" string from Unity when ceedling is trying to interpret `result` in `generator.rb::Generator.generate_test_results`, as seen below when I inspect `shell_result`:

```
shell result => {:output=>"\ntest_printf.c:15:test_a:PASShello\n\ntest_printf.c:21:test_b:PASS\n-----------------------\n2 Tests 0 Failures 0 Ignored\nOK\n", :exit_code=>0}
```

I've seen the same behavior on Mac OS X and mingw32. Here's my mingw32 version info:

```
$ gem list

*** LOCAL GEMS ***

bigdecimal (1.1.0)
ceedling (0.15.5, 0.15.4)
io-console (0.3)
json (1.5.5)
minitest (2.5.1)
rake (10.3.2)
rdoc (3.9.5)
thor (0.19.1)

$ ruby --version
ruby 1.9.3p545 (2014-02-24) [i386-mingw32]
```

**Comment by mvandervoord** [comment]
I believe this is fixed at this point.
