### ISSUE TITLE
Ceedling 0.15.6 Fails When Path Contains Space(s)

### ISSUE THREAD

**Issue by chaosAD** [ThrowTheSwitch/Ceedling#42]
I updated from version `0.13.0`, which was working fine, to `0.15.6`. I am using Mingw32 under Windows. I did the following in a path containing a space (`c:/Project Xtreme/`):

```
> ceedling new PcControl
> cd PcControl
> rake module:create[Dummy]
> rake test:all
```

The last command dumped the following error:

```
Test 'test_Dummy.c'
-------------------
gcc.exe: error: Xtreme/PcControl/vendor/ceedling/vendor/unity/src: No such file
or directory
gcc.exe: error: Xtreme/PcControl/vendor/ceedling/vendor/cmock/src: No such file
or directory
ERROR: Shell command failed.
> Shell executed command:
'gcc.exe -E -MM -MG -Itest -Itest/support -Isrc -Ic:/Project Xtreme/PcControl/ve
ndor/ceedling/vendor/unity/src -Ic:/Project Xtreme/PcControl/vendor/ceedling/ven
dor/cmock/src -Ibuild/test/mocks -DTEST -DTEST -DGNU_COMPILER -w "build/temp/_te
st_Dummy.c"'
> And exited with status: [1].

rake aborted!
ShellExecutionException
c:/Project Xtreme/PcControl/vendor/ceedling/lib/ceedling/tool_executor.rb:74:in
`exec'
c:/Project Xtreme/PcControl/vendor/ceedling/lib/ceedling/preprocessinator_includ
es_handler.rb:39:in `form_shallow_dependencies_rule'
c:/Project Xtreme/PcControl/vendor/ceedling/lib/ceedling/preprocessinator.rb:31:
in `preprocess_shallow_includes'
c:/Project Xtreme/PcControl/vendor/ceedling/lib/ceedling/preprocessinator.rb:11:
in `block in setup'
c:/Project Xtreme/PcControl/vendor/ceedling/lib/ceedling/preprocessinator_helper
.rb:11:in `call'
c:/Project Xtreme/PcControl/vendor/ceedling/lib/ceedling/preprocessinator_helper
.rb:11:in `preprocess_includes'
c:/Project Xtreme/PcControl/vendor/ceedling/lib/ceedling/preprocessinator.rb:17:
in `preprocess_test_and_invoke_test_mocks'
c:/Project Xtreme/PcControl/vendor/ceedling/lib/ceedling/test_invoker.rb:42:in `
block in setup_and_invoke'
c:/Project Xtreme/PcControl/vendor/ceedling/lib/ceedling/test_invoker.rb:32:in `
setup_and_invoke'
c:/Project Xtreme/PcControl/vendor/ceedling/lib/ceedling/tasks_tests.rake:8:in `
block (2 levels) in <top (required)>'
Tasks: TOP => test:all
(See full trace by running task with --trace)

--------------------
OVERALL TEST SUMMARY
--------------------

No tests executed.
```

I works fine with path without space, though.

**Comment by jimmanz** [comment]
+1 on this issue. I am showing my paths below and if any of them have a space (like CAN Library does currently), it complains.

:paths:
  :include:
    - "C:/microchip/xc16/v1.21/support/DSPIC33E/h/"
    - "C:/microchip/xc16/v1.21/support/generic/h/"
    - "../../../../USB_Library/"
    - "../../../../Shared/Software/Firmware/"
    - "../../../../CAN Library/"
    - vendor/ceedling/vendor/unity/src
  :test:
    - +:test/**
    - -:test/support
  :source:
    - "../../../../Shared/Software/Firmware/"
  :support:
    - test/support

I upgraded to 0.18.0 and it seems to have the same problem.

Thanks,
Jim

**Comment by raasoft** [comment]
Same exact problem as jimmanz

**Comment by art-of-dom** [comment]
Could not reproduce on master. Is anyone still having this issue?

**Comment by mvandervoord** [comment]
I am not

**Comment by JuPrgn** [comment]
I have this issue with 0.29.1 when setting : 
```
:project:
  :use_test_preprocessor: TRUE
:environment:
  - :XC16P: 'C:\Program Files (x86)\Microchip\xc16\v1.35\bin'
:tools:
  :test_includes_preprocessor:
    :executable: xc16-gcc
  :test_file_preprocessor:
    :executable: xc16-gcc
  :test_compiler:
    :executable: xc16-gcc
```
> Test 'test_foo.c'
> ............................
> Program: Files: No such file or directory
> Program: (x86)\Microchip\xc16\v1.35\bin\bin/elf-gcc.exe: No such file or directory
> Program: no input files
> ERROR: Shell command failed.
> Shell executed command:
> 'xc16-gcc'
> And exited with status: [255].

When I disable `:use_test_preprocessor: FALSE` and remove : 
```
:tools:
  :test_includes_preprocessor:
    :executable: xc16-gcc
  :test_file_preprocessor:
    :executable: xc16-gcc
```
Ceedling is working without issue calling xc16-gcc from XC16P path

I am currently trying to configure preprocessor for my project and I don't know how to do this at the moment so my current configuration for tools preprocessor may be incomplete. This is also related to #452.

**Comment by JuPrgn** [comment]
I have another example and it seems this is linked with arguments : when arguments are specified I do not have space issue with my file path : 
```
:tools:
  :test_file_preprocessor:
    :executable: xc16-gcc
    :name: 'XC 16 Test File Preprocessor'
    :arguments:
      - -mcpu=#{ENV['MCPU']}
      - "${1}"
      - -o "${2}"
```
Gives : 
> test/test_foo.c:11:19: fatal error: unity.h: No such file or directory
> compilation terminated.
> ERROR: Shell command failed.
> > Shell executed command:
> 'xc16-gcc -mcpu=33EP256MC506 test/test_foo.c -o "build_test/test/preprocess/files/test_foo.c"'
> > And exited with status: [255].

But without arguments : 
```
:tools:
  :test_file_preprocessor:
    :executable: xc16-gcc
    :name: 'XC 16 Test File Preprocessor'
```
Gives : 

> Program: Files: No such file or directory
> Program: (x86)\Microchip\xc16\v1.35\bin\bin/elf-gcc.exe: No such file or directory
> Program: no input files
> ERROR: Shell command failed.
> > Shell executed command:
> 'xc16-gcc'
> > And exited with status: [255].

**Comment by JuPrgn** [comment]
I did not succeeded fixing this yet. Any hint is welcome =)

**Comment by CezaryGapinski** [comment]
Can you try to execute `xc16-gcc` command from the windows terminal?

When I was trying to run the `xc16-gcc` from the command line on Windows 10, I've got this message:
```
Program: Files: No such file or directory
Program: (x86)\Microchip\xc16\v1.35\bin\bin/elf-gcc.exe: No such file or directory
Program: no input files
```
So I think it doesn't have to be particularly related to the Ceedling, but maybe something is wrong with xc16-gcc installation when install path contains spaces or parenthesis.

**Comment by mkarlesky** [comment]
I believe we licked spaces in paths a long while ago now.
