### ISSUE TITLE
Most tests fail with Ruby 2.7.0 on macOS

### ISSUE THREAD

**Issue by felipebalbi** [ThrowTheSwitch/Ceedling#472]
Hi,

I noticed a few problems with `ceedling` which I wanted to help sort out, but at least on macOS and ruby 2.7.0, most tests are failing, see below:

```
Finished in 1 minute 7.1 seconds (files took 0.50836 seconds to load)
221 examples, 113 failures, 8 pending

Failed examples:

rspec ./spec/gcov/gcov_deployment_spec.rb:27 # Ceedling Gcov basic operations 
rspec ./spec/gcov/gcov_deployment_spec.rb:28 # Ceedling Gcov basic operations 
rspec ./spec/gcov/gcov_deployment_spec.rb:29 # Ceedling Gcov basic operations 
rspec ./spec/gcov/gcov_deployment_spec.rb:30 # Ceedling Gcov basic operations 
rspec ./spec/gcov/gcov_deployment_spec.rb:31 # Ceedling Gcov basic operations 
rspec ./spec/gcov/gcov_deployment_spec.rb:32 # Ceedling Gcov basic operations 
rspec ./spec/gcov/gcov_deployment_spec.rb:33 # Ceedling Gcov basic operations 
rspec ./spec/gcov/gcov_deployment_spec.rb:46 # Ceedling Gcov command: `ceedling example [example]` temp_sensor should be testable
rspec ./spec/system/deployment_spec.rb:25 # Ceedling deployed in a project's `vendor` directory. 
rspec ./spec/system/deployment_spec.rb:26 # Ceedling deployed in a project's `vendor` directory. 
rspec ./spec/system/deployment_spec.rb:27 # Ceedling deployed in a project's `vendor` directory. 
rspec ./spec/system/deployment_spec.rb:28 # Ceedling deployed in a project's `vendor` directory. should match 0
rspec ./spec/system/deployment_spec.rb:29 # Ceedling deployed in a project's `vendor` directory. 
rspec ./spec/system/deployment_spec.rb:30 # Ceedling deployed in a project's `vendor` directory. 
rspec ./spec/system/deployment_spec.rb:31 # Ceedling deployed in a project's `vendor` directory. 
rspec ./spec/system/deployment_spec.rb:32 # Ceedling deployed in a project's `vendor` directory. 
rspec ./spec/system/deployment_spec.rb:33 # Ceedling deployed in a project's `vendor` directory. 
rspec ./spec/system/deployment_spec.rb:34 # Ceedling deployed in a project's `vendor` directory. 
rspec ./spec/system/deployment_spec.rb:35 # Ceedling deployed in a project's `vendor` directory. 
rspec ./spec/system/deployment_spec.rb:36 # Ceedling deployed in a project's `vendor` directory. 
rspec ./spec/system/deployment_spec.rb:37 # Ceedling deployed in a project's `vendor` directory. 
rspec ./spec/system/deployment_spec.rb:38 # Ceedling deployed in a project's `vendor` directory. 
rspec ./spec/system/deployment_spec.rb:39 # Ceedling deployed in a project's `vendor` directory. 
rspec ./spec/system/deployment_spec.rb:40 # Ceedling deployed in a project's `vendor` directory. 
rspec ./spec/system/deployment_spec.rb:41 # Ceedling deployed in a project's `vendor` directory. 
rspec ./spec/system/deployment_spec.rb:42 # Ceedling deployed in a project's `vendor` directory. 
rspec ./spec/system/deployment_spec.rb:43 # Ceedling deployed in a project's `vendor` directory. 
rspec ./spec/system/deployment_spec.rb:44 # Ceedling deployed in a project's `vendor` directory. 
rspec ./spec/system/deployment_spec.rb:45 # Ceedling deployed in a project's `vendor` directory. 
rspec ./spec/system/deployment_spec.rb:55 # Ceedling deployed in a project's `vendor` directory with gitignore. 
rspec ./spec/system/deployment_spec.rb:56 # Ceedling deployed in a project's `vendor` directory with gitignore. 
rspec ./spec/system/deployment_spec.rb:57 # Ceedling deployed in a project's `vendor` directory with gitignore. 
rspec ./spec/system/deployment_spec.rb:58 # Ceedling deployed in a project's `vendor` directory with gitignore. 
rspec ./spec/system/deployment_spec.rb:59 # Ceedling deployed in a project's `vendor` directory with gitignore. 
rspec ./spec/system/deployment_spec.rb:60 # Ceedling deployed in a project's `vendor` directory with gitignore. 
rspec ./spec/system/deployment_spec.rb:72 # Ceedling deployed in a project's `vendor` directory without docs. 
rspec ./spec/system/deployment_spec.rb:73 # Ceedling deployed in a project's `vendor` directory without docs. 
rspec ./spec/system/deployment_spec.rb:74 # Ceedling deployed in a project's `vendor` directory without docs. 
rspec ./spec/system/deployment_spec.rb:75 # Ceedling deployed in a project's `vendor` directory without docs. should match 0
rspec ./spec/system/deployment_spec.rb:76 # Ceedling deployed in a project's `vendor` directory without docs. 
rspec ./spec/system/deployment_spec.rb:77 # Ceedling deployed in a project's `vendor` directory without docs. 
rspec ./spec/system/deployment_spec.rb:78 # Ceedling deployed in a project's `vendor` directory without docs. 
rspec ./spec/system/deployment_spec.rb:79 # Ceedling deployed in a project's `vendor` directory without docs. 
rspec ./spec/system/deployment_spec.rb:80 # Ceedling deployed in a project's `vendor` directory without docs. 
rspec ./spec/system/deployment_spec.rb:81 # Ceedling deployed in a project's `vendor` directory without docs. 
rspec ./spec/system/deployment_spec.rb:82 # Ceedling deployed in a project's `vendor` directory without docs. 
rspec ./spec/system/deployment_spec.rb:83 # Ceedling deployed in a project's `vendor` directory without docs. 
rspec ./spec/system/deployment_spec.rb:84 # Ceedling deployed in a project's `vendor` directory without docs. 
rspec ./spec/system/deployment_spec.rb:85 # Ceedling deployed in a project's `vendor` directory without docs. 
rspec ./spec/system/deployment_spec.rb:86 # Ceedling deployed in a project's `vendor` directory without docs. 
rspec ./spec/system/deployment_spec.rb:87 # Ceedling deployed in a project's `vendor` directory without docs. 
rspec ./spec/system/deployment_spec.rb:88 # Ceedling deployed in a project's `vendor` directory without docs. 
rspec ./spec/system/deployment_spec.rb:89 # Ceedling deployed in a project's `vendor` directory without docs. 
rspec ./spec/system/deployment_spec.rb:90 # Ceedling deployed in a project's `vendor` directory without docs. 
rspec ./spec/system/deployment_spec.rb:100 # Ceedling ugrade a project's `vendor` directory 
rspec ./spec/system/deployment_spec.rb:101 # Ceedling ugrade a project's `vendor` directory 
rspec ./spec/system/deployment_spec.rb:102 # Ceedling ugrade a project's `vendor` directory 
rspec ./spec/system/deployment_spec.rb:103 # Ceedling ugrade a project's `vendor` directory should match 0
rspec ./spec/system/deployment_spec.rb:104 # Ceedling ugrade a project's `vendor` directory 
rspec ./spec/system/deployment_spec.rb:105 # Ceedling ugrade a project's `vendor` directory 
rspec ./spec/system/deployment_spec.rb:106 # Ceedling ugrade a project's `vendor` directory 
rspec ./spec/system/deployment_spec.rb:107 # Ceedling ugrade a project's `vendor` directory 
rspec ./spec/system/deployment_spec.rb:108 # Ceedling ugrade a project's `vendor` directory 
rspec ./spec/system/deployment_spec.rb:109 # Ceedling ugrade a project's `vendor` directory 
rspec ./spec/system/deployment_spec.rb:110 # Ceedling ugrade a project's `vendor` directory 
rspec ./spec/system/deployment_spec.rb:111 # Ceedling ugrade a project's `vendor` directory 
rspec ./spec/system/deployment_spec.rb:112 # Ceedling ugrade a project's `vendor` directory 
rspec ./spec/system/deployment_spec.rb:113 # Ceedling ugrade a project's `vendor` directory 
rspec ./spec/system/deployment_spec.rb:114 # Ceedling ugrade a project's `vendor` directory 
rspec ./spec/system/deployment_spec.rb:115 # Ceedling ugrade a project's `vendor` directory 
rspec ./spec/system/deployment_spec.rb:116 # Ceedling ugrade a project's `vendor` directory 
rspec ./spec/system/deployment_spec.rb:117 # Ceedling ugrade a project's `vendor` directory 
rspec ./spec/system/deployment_spec.rb:118 # Ceedling ugrade a project's `vendor` directory 
rspec ./spec/system/deployment_spec.rb:119 # Ceedling ugrade a project's `vendor` directory 
rspec ./spec/system/deployment_spec.rb:121 # Ceedling ugrade a project's `vendor` directory should match 0
rspec ./spec/system/deployment_spec.rb:122 # Ceedling ugrade a project's `vendor` directory 
rspec ./spec/system/deployment_spec.rb:123 # Ceedling ugrade a project's `vendor` directory 
rspec ./spec/system/deployment_spec.rb:124 # Ceedling ugrade a project's `vendor` directory should match 0
rspec ./spec/system/deployment_spec.rb:125 # Ceedling ugrade a project's `vendor` directory 
rspec ./spec/system/deployment_spec.rb:126 # Ceedling ugrade a project's `vendor` directory 
rspec ./spec/system/deployment_spec.rb:127 # Ceedling ugrade a project's `vendor` directory 
rspec ./spec/system/deployment_spec.rb:128 # Ceedling ugrade a project's `vendor` directory 
rspec ./spec/system/deployment_spec.rb:129 # Ceedling ugrade a project's `vendor` directory 
rspec ./spec/system/deployment_spec.rb:130 # Ceedling ugrade a project's `vendor` directory 
rspec ./spec/system/deployment_spec.rb:131 # Ceedling ugrade a project's `vendor` directory 
rspec ./spec/system/deployment_spec.rb:132 # Ceedling ugrade a project's `vendor` directory 
rspec ./spec/system/deployment_spec.rb:133 # Ceedling ugrade a project's `vendor` directory 
rspec ./spec/system/deployment_spec.rb:134 # Ceedling ugrade a project's `vendor` directory 
rspec ./spec/system/deployment_spec.rb:135 # Ceedling ugrade a project's `vendor` directory 
rspec ./spec/system/deployment_spec.rb:136 # Ceedling ugrade a project's `vendor` directory 
rspec ./spec/system/deployment_spec.rb:137 # Ceedling ugrade a project's `vendor` directory 
rspec ./spec/system/deployment_spec.rb:138 # Ceedling ugrade a project's `vendor` directory 
rspec ./spec/system/deployment_spec.rb:139 # Ceedling ugrade a project's `vendor` directory 
rspec ./spec/system/deployment_spec.rb:140 # Ceedling ugrade a project's `vendor` directory 
rspec ./spec/system/deployment_spec.rb:150 # Ceedling deployed as a gem 
rspec ./spec/system/deployment_spec.rb:151 # Ceedling deployed as a gem 
rspec ./spec/system/deployment_spec.rb:152 # Ceedling deployed as a gem should match 0
rspec ./spec/system/deployment_spec.rb:153 # Ceedling deployed as a gem 
rspec ./spec/system/deployment_spec.rb:154 # Ceedling deployed as a gem 
rspec ./spec/system/deployment_spec.rb:155 # Ceedling deployed as a gem 
rspec ./spec/system/deployment_spec.rb:156 # Ceedling deployed as a gem 
rspec ./spec/system/deployment_spec.rb:157 # Ceedling deployed as a gem 
rspec ./spec/system/deployment_spec.rb:158 # Ceedling deployed as a gem 
rspec ./spec/system/deployment_spec.rb:159 # Ceedling deployed as a gem 
rspec ./spec/system/deployment_spec.rb:160 # Ceedling deployed as a gem 
rspec ./spec/system/deployment_spec.rb:161 # Ceedling deployed as a gem 
rspec ./spec/system/deployment_spec.rb:162 # Ceedling deployed as a gem 
rspec ./spec/system/deployment_spec.rb:163 # Ceedling deployed as a gem 
rspec ./spec/system/deployment_spec.rb:164 # Ceedling deployed as a gem 
rspec ./spec/system/deployment_spec.rb:165 # Ceedling deployed as a gem 
rspec ./spec/system/deployment_spec.rb:166 # Ceedling deployed as a gem 
rspec ./spec/system/deployment_spec.rb:176 # Ceedling command: `ceedling examples` should list out all the examples
rspec ./spec/system/deployment_spec.rb:191 # Ceedling command: `ceedling example [example]` temp_sensor should be testable

/usr/local/Cellar/ruby/2.7.0/bin/ruby -I/usr/local/lib/ruby/gems/2.7.0/gems/rspec-core-3.8.0/lib:/usr/local/lib/ruby/gems/2.7.0/gems/rspec-support-3.8.0/lib /usr/local/lib/ruby/gems/2.7.0/gems/rspec-core-3.8.0/exe/rspec --pattern spec/\*\*/\*_spec.rb failed
```

I can help debug this, but any hints would be appreciated :-) There's a message showing up very frequently:

```
There was an error while loading `ceedling.gemspec`: uninitialized constant Ceedling::Version::CEEDLING_VENDOR. Bundler cannot continue.
```

And here's a run of `gcov` deployment tests only:

```
> rspec spec/gcov/gcov_deployment_spec.rb
[DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set path '/var/folders/px/646w_0d17517xz52r_nvzg540000gn/T/d20200313-48849-15wtw4d/gems'`, and stop using this flag

[!] There was an error while loading `ceedling.gemspec`: uninitialized constant Ceedling::Version::CEEDLING_VENDOR. Bundler cannot continue.

 #  from /Users/felipebalbi/workspace/ceedling/ceedling.gemspec:3
 #  -------------------------------------------
 #  $LOAD_PATH << File.expand_path(File.join(File.dirname(__FILE__), 'lib'))
 >  require "ceedling/version"
 #  require 'date'
 #  -------------------------------------------
FFFFFFFF

Failures:

  1) Ceedling Gcov basic operations 
     Failure/Error:
             Dir.chdir @proj_name do
               FileUtils.cp test_asset_path("project_with_guts_gcov.yml"), "project.yml"
               FileUtils.cp test_asset_path("example_file.h"), 'src/'
               FileUtils.cp test_asset_path("example_file.c"), 'src/'
               FileUtils.cp test_asset_path("test_example_file_success.c"), 'test/'
       
               output = `bundle exec ruby -S ceedling gcov:all`
               expect($?.exitstatus).to match(0) # Since a test either pass or are ignored, we return success here
               expect(output).to match(/TESTED:\s+\d/)
               expect(output).to match(/PASSED:\s+\d/)
     
     Errno::ENOENT:
       No such file or directory @ dir_chdir - fake_project
     # ./spec/gcov/gcov_test_cases_spec.rb:12:in `chdir'
     # ./spec/gcov/gcov_test_cases_spec.rb:12:in `block in can_test_projects_with_gcov_with_success'
     # ./spec/spec_system_helper.rb:162:in `block (2 levels) in with_context'
     # ./spec/spec_system_helper.rb:193:in `with_constrained_env'
     # ./spec/spec_system_helper.rb:158:in `block in with_context'
     # ./spec/spec_system_helper.rb:157:in `chdir'
     # ./spec/spec_system_helper.rb:157:in `with_context'
     # ./spec/gcov/gcov_test_cases_spec.rb:11:in `can_test_projects_with_gcov_with_success'
     # ./spec/gcov/gcov_deployment_spec.rb:27:in `block (4 levels) in <top (required)>'

  2) Ceedling Gcov basic operations 
     Failure/Error:
             Dir.chdir @proj_name do
               FileUtils.cp test_asset_path("project_with_guts_gcov.yml"), "project.yml"
               FileUtils.cp test_asset_path("example_file.h"), 'src/'
               FileUtils.cp test_asset_path("example_file.c"), 'src/'
               FileUtils.cp test_asset_path("test_example_file.c"), 'test/'
       
               output = `bundle exec ruby -S ceedling gcov:all 2>&1`
               expect($?.exitstatus).to match(1) # Since a test fails, we return error here
               expect(output).to match(/TESTED:\s+\d/)
               expect(output).to match(/PASSED:\s+\d/)
     
     Errno::ENOENT:
       No such file or directory @ dir_chdir - fake_project
     # ./spec/gcov/gcov_test_cases_spec.rb:30:in `chdir'
     # ./spec/gcov/gcov_test_cases_spec.rb:30:in `block in can_test_projects_with_gcov_with_fail'
     # ./spec/spec_system_helper.rb:162:in `block (2 levels) in with_context'
     # ./spec/spec_system_helper.rb:193:in `with_constrained_env'
     # ./spec/spec_system_helper.rb:158:in `block in with_context'
     # ./spec/spec_system_helper.rb:157:in `chdir'
     # ./spec/spec_system_helper.rb:157:in `with_context'
     # ./spec/gcov/gcov_test_cases_spec.rb:29:in `can_test_projects_with_gcov_with_fail'
     # ./spec/gcov/gcov_deployment_spec.rb:28:in `block (4 levels) in <top (required)>'

  3) Ceedling Gcov basic operations 
     Failure/Error:
             Dir.chdir @proj_name do
               FileUtils.cp test_asset_path("project_with_guts_gcov_abortonuncovered.yml"), "project.yml"
               FileUtils.cp test_asset_path("example_file.h"), 'src/'
               FileUtils.cp test_asset_path("example_file.c"), 'src/'
               FileUtils.cp test_asset_path("uncovered_example_file.c"), 'src/'
               FileUtils.cp test_asset_path("test_example_file_success.c"), 'test/'
       
               output = `bundle exec ruby -S ceedling gcov:all 2>&1`
               expect($?.exitstatus).to match(255) # Since a test fails, we return error here
               expect(output).to match(/TESTED:\s+\d/)
     
     Errno::ENOENT:
       No such file or directory @ dir_chdir - fake_project
     # ./spec/gcov/gcov_test_cases_spec.rb:48:in `chdir'
     # ./spec/gcov/gcov_test_cases_spec.rb:48:in `block in can_test_projects_with_gcov_with_fail_because_of_uncovered_files'
     # ./spec/spec_system_helper.rb:162:in `block (2 levels) in with_context'
     # ./spec/spec_system_helper.rb:193:in `with_constrained_env'
     # ./spec/spec_system_helper.rb:158:in `block in with_context'
     # ./spec/spec_system_helper.rb:157:in `chdir'
     # ./spec/spec_system_helper.rb:157:in `with_context'
     # ./spec/gcov/gcov_test_cases_spec.rb:47:in `can_test_projects_with_gcov_with_fail_because_of_uncovered_files'
     # ./spec/gcov/gcov_deployment_spec.rb:29:in `block (4 levels) in <top (required)>'

  4) Ceedling Gcov basic operations 
     Failure/Error:
             Dir.chdir @proj_name do
               FileUtils.cp test_asset_path("project_with_guts_gcov_abortonuncovered.yml"), "project.yml"
               FileUtils.cp test_asset_path("example_file.h"), "src/"
               FileUtils.cp test_asset_path("example_file.c"), "src/"
               FileUtils.cp test_asset_path("uncovered_example_file.c"), "src/foo_file.c" # "src/foo_file.c" is in the ignore uncovered list
               FileUtils.cp test_asset_path("test_example_file_success.c"), "test/"
       
               output = `bundle exec ruby -S ceedling gcov:all 2>&1`
               expect($?.exitstatus).to match(0)
               expect(output).to match(/TESTED:\s+\d/)
     
     Errno::ENOENT:
       No such file or directory @ dir_chdir - fake_project
     # ./spec/gcov/gcov_test_cases_spec.rb:67:in `chdir'
     # ./spec/gcov/gcov_test_cases_spec.rb:67:in `block in can_test_projects_with_gcov_with_success_because_of_ignore_uncovered_list'
     # ./spec/spec_system_helper.rb:162:in `block (2 levels) in with_context'
     # ./spec/spec_system_helper.rb:193:in `with_constrained_env'
     # ./spec/spec_system_helper.rb:158:in `block in with_context'
     # ./spec/spec_system_helper.rb:157:in `chdir'
     # ./spec/spec_system_helper.rb:157:in `with_context'
     # ./spec/gcov/gcov_test_cases_spec.rb:66:in `can_test_projects_with_gcov_with_success_because_of_ignore_uncovered_list'
     # ./spec/gcov/gcov_deployment_spec.rb:30:in `block (4 levels) in <top (required)>'

  5) Ceedling Gcov basic operations 
     Failure/Error:
             Dir.chdir @proj_name do
               FileUtils.cp test_asset_path("project_with_guts_gcov.yml"), "project.yml"
               FileUtils.cp test_asset_path("example_file.h"), 'src/'
               FileUtils.cp test_asset_path("example_file.c"), 'src/'
               FileUtils.cp test_asset_path("test_example_file_boom.c"), 'test/'
       
               output = `bundle exec ruby -S ceedling gcov:all 2>&1`
               expect($?.exitstatus).to match(1) # Since a test explodes, we return error here
               expect(output).to match(/ERROR: Ceedling Failed/)
             end
     
     Errno::ENOENT:
       No such file or directory @ dir_chdir - fake_project
     # ./spec/gcov/gcov_test_cases_spec.rb:86:in `chdir'
     # ./spec/gcov/gcov_test_cases_spec.rb:86:in `block in can_test_projects_with_gcov_with_compile_error'
     # ./spec/spec_system_helper.rb:162:in `block (2 levels) in with_context'
     # ./spec/spec_system_helper.rb:193:in `with_constrained_env'
     # ./spec/spec_system_helper.rb:158:in `block in with_context'
     # ./spec/spec_system_helper.rb:157:in `chdir'
     # ./spec/spec_system_helper.rb:157:in `with_context'
     # ./spec/gcov/gcov_test_cases_spec.rb:85:in `can_test_projects_with_gcov_with_compile_error'
     # ./spec/gcov/gcov_deployment_spec.rb:31:in `block (4 levels) in <top (required)>'

  6) Ceedling Gcov basic operations 
     Failure/Error:
       Dir.chdir @proj_name do
         FileUtils.cp test_asset_path("project_with_guts_gcov.yml"), "project.yml"
         output = `bundle exec ruby -S ceedling help`
         expect($?.exitstatus).to match(0)
         expect(output).to match(/ceedling gcov:\*/i)
         expect(output).to match(/ceedling gcov:all/i)
         expect(output).to match(/ceedling gcov:delta/i)
         expect(output).to match(/ceedling utils:gcov/i)
       end
     
     Errno::ENOENT:
       No such file or directory @ dir_chdir - fake_project
     # ./spec/gcov/gcov_test_cases_spec.rb:101:in `chdir'
     # ./spec/gcov/gcov_test_cases_spec.rb:101:in `block in can_fetch_project_help_for_gcov'
     # ./spec/spec_system_helper.rb:162:in `block (2 levels) in with_context'
     # ./spec/spec_system_helper.rb:193:in `with_constrained_env'
     # ./spec/spec_system_helper.rb:158:in `block in with_context'
     # ./spec/spec_system_helper.rb:157:in `chdir'
     # ./spec/spec_system_helper.rb:157:in `with_context'
     # ./spec/gcov/gcov_test_cases_spec.rb:100:in `can_fetch_project_help_for_gcov'
     # ./spec/gcov/gcov_deployment_spec.rb:32:in `block (4 levels) in <top (required)>'

  7) Ceedling Gcov basic operations 
     Failure/Error:
             Dir.chdir @proj_name do
               FileUtils.cp test_asset_path("project_with_guts_gcov.yml"), "project.yml"
               FileUtils.cp test_asset_path("example_file.h"), 'src/'
               FileUtils.cp test_asset_path("example_file.c"), 'src/'
               FileUtils.cp test_asset_path("test_example_file_success.c"), 'test/'
       
               output = `bundle exec ruby -S ceedling gcov:all`
               output = `bundle exec ruby -S ceedling utils:gcov`
               expect(output).to match(/Creating gcov results report\(s\) in 'build\/artifacts\/gcov'\.\.\. Done/)
               expect(File.exists?('build/artifacts/gcov/GcovCoverageResults.html')).to eq true
     
     Errno::ENOENT:
       No such file or directory @ dir_chdir - fake_project
     # ./spec/gcov/gcov_test_cases_spec.rb:115:in `chdir'
     # ./spec/gcov/gcov_test_cases_spec.rb:115:in `block in can_create_html_report'
     # ./spec/spec_system_helper.rb:162:in `block (2 levels) in with_context'
     # ./spec/spec_system_helper.rb:193:in `with_constrained_env'
     # ./spec/spec_system_helper.rb:158:in `block in with_context'
     # ./spec/spec_system_helper.rb:157:in `chdir'
     # ./spec/spec_system_helper.rb:157:in `with_context'
     # ./spec/gcov/gcov_test_cases_spec.rb:114:in `can_create_html_report'
     # ./spec/gcov/gcov_deployment_spec.rb:33:in `block (4 levels) in <top (required)>'

  8) Ceedling Gcov command: `ceedling example [example]` temp_sensor should be testable
     Failure/Error: expect(output).to match(/created!/)
     
       expected "/usr/local/opt/ruby/bin/ruby: No such file or directory -- ceedling (LoadError)\n" to match /created!/
       Diff:
       @@ -1,2 +1,2 @@
       -/created!/
       +/usr/local/opt/ruby/bin/ruby: No such file or directory -- ceedling (LoadError)
       
     # ./spec/gcov/gcov_deployment_spec.rb:42:in `block (6 levels) in <top (required)>'
     # ./spec/spec_system_helper.rb:162:in `block (2 levels) in with_context'
     # ./spec/spec_system_helper.rb:193:in `with_constrained_env'
     # ./spec/spec_system_helper.rb:158:in `block in with_context'
     # ./spec/spec_system_helper.rb:157:in `chdir'
     # ./spec/spec_system_helper.rb:157:in `with_context'
     # ./spec/gcov/gcov_deployment_spec.rb:40:in `block (5 levels) in <top (required)>'

Finished in 4.64 seconds (files took 0.40579 seconds to load)
8 examples, 8 failures

Failed examples:

rspec ./spec/gcov/gcov_deployment_spec.rb:27 # Ceedling Gcov basic operations 
rspec ./spec/gcov/gcov_deployment_spec.rb:28 # Ceedling Gcov basic operations 
rspec ./spec/gcov/gcov_deployment_spec.rb:29 # Ceedling Gcov basic operations 
rspec ./spec/gcov/gcov_deployment_spec.rb:30 # Ceedling Gcov basic operations 
rspec ./spec/gcov/gcov_deployment_spec.rb:31 # Ceedling Gcov basic operations 
rspec ./spec/gcov/gcov_deployment_spec.rb:32 # Ceedling Gcov basic operations 
rspec ./spec/gcov/gcov_deployment_spec.rb:33 # Ceedling Gcov basic operations 
rspec ./spec/gcov/gcov_deployment_spec.rb:46 # Ceedling Gcov command: `ceedling example [example]` temp_sensor should be testable
```

**Comment by dpostorivo** [comment]
How are you running the tests and do you have gcov installed for  the gcov specific tests?

I'd like to take the first steps of this by adding ruby 2.7 to the matrix to confirm it's not a ruby comparability issue, but that probably won't be for a few more days.

**Comment by felipebalbi** [comment]
Running tests with `bundle exec rake`. gcov is installed. The only tests that fail are `gcov` and `system`. I think the problem is related to trying to to install the gem in a temporary directory.

There's also an annoying error about not having CEEDLING_VENDOR constant initialised. Seems like it's looking for it in the wrong place:

```
[!] There was an error while loading `ceedling.gemspec`: uninitialized constant Ceedling::Version::CEEDLING_VENDOR. Bundler cannot continue.

 #  from /Users/felipebalbi/workspace/ceedling/ceedling.gemspec:3
 #  -------------------------------------------
 #  $LOAD_PATH << File.expand_path(File.join(File.dirname(__FILE__), 'lib'))
 >  require "ceedling/version"
 #  require 'date'
 #  -------------------------------------------
```

gcov:

```
> gcov --version
Apple LLVM version 11.0.0 (clang-1100.0.33.8)
  Optimized build.
  Default target: x86_64-apple-darwin19.3.0
  Host CPU: skylake
```

ruby:

```
> ruby --version
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]
```

**Comment by felipebalbi** [comment]
If I ignore the subdirectories, everything works fine:

```
> find spec -type f -maxdepth 1 | xargs rspec
...........*........*..........**.............****..........................................................

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) FileFinderHelper#find_file_in_collection handles duplicate files
     # Temporarily skipped with xit
     # ./spec/file_finder_helper_spec.rb:26

  2) uncategorized set_verbosity needs to be defined
     # Temporarily skipped with xit
     # ./spec/uncatagorized_specs_spec.rb:6

  3) ConfiguratorBuilder is scary
     # Temporarily skipped with xit
     # ./spec/configurator_builder_spec.rb:6

  4) ConfiguratorHelper doesn't exist...
     # Temporarily skipped with xit
     # ./spec/configurator_helper_spec.rb:4

  5) Configurator#standardize_paths should standardize [:project][:build_root]
     # Temporarily skipped with xit
     # ./spec/configurator_spec.rb:5

  6) Configurator#standardize_paths should standardize [:paths]
     # Temporarily skipped with xit
     # ./spec/configurator_spec.rb:6

  7) Configurator#standardize_paths should standardize [:files]
     # Temporarily skipped with xit
     # ./spec/configurator_spec.rb:7

  8) Configurator#standardize_paths should standardize [:tools]
     # Temporarily skipped with xit
     # ./spec/configurator_spec.rb:8


Finished in 0.93279 seconds (files took 1.16 seconds to load)
108 examples, 0 failures, 8 pending
```

**Comment by felipebalbi** [comment]
I ran `rspec --bisect` and it confirms what I mentioned before:

```
Bisect complete! Reduced necessary non-failing examples from 108 to 0 in 47.5 seconds.

The minimal reproduction command is:
  rspec ./spec/gcov/gcov_deployment_spec.rb[1:1:1:1,1:1:1:2,1:1:1:3,1:1:1:4,1:1:1:5,1:1:1:6,1:1:1:7,1:1:2:1:1] ./spec/system/deployment_spec.rb[1:1:1,1:1:2,1:1:3,1:1:4,1:1:5,1:1:6,1:1:7,1:1:8,1:1:9,1:1:10,1:1:11,1:1:12,1:1:13,1:1:14,1:1:15,1:1:16,1:1:17,1:1:18,1:1:19,1:1:20,1:1:21,1:2:1,1:2:2,1:2:3,1:2:4,1:2:5,1:2:6,1:3:1,1:3:2,1:3:3,1:3:4,1:3:5,1:3:6,1:3:7,1:3:8,1:3:9,1:3:10,1:3:11,1:3:12,1:3:13,1:3:14,1:3:15,1:3:16,1:3:17,1:3:18,1:3:19,1:4:1,1:4:2,1:4:3,1:4:4,1:4:5,1:4:6,1:4:7,1:4:8,1:4:9,1:4:10,1:4:11,1:4:12,1:4:13,1:4:14,1:4:15,1:4:16,1:4:17,1:4:18,1:4:19,1:4:20,1:4:21,1:4:22,1:4:23,1:4:24,1:4:25,1:4:26,1:4:27,1:4:28,1:4:29,1:4:30,1:4:31,1:4:32,1:4:33,1:4:34,1:4:35,1:4:36,1:4:37,1:4:38,1:4:39,1:4:40,1:5:1,1:5:2,1:5:3,1:5:4,1:5:5,1:5:6,1:5:7,1:5:8,1:5:9,1:5:10,1:5:11,1:5:12,1:5:13,1:5:14,1:5:15,1:5:16,1:5:17,1:6:1,1:7:1:1]
```

**Comment by felipebalbi** [comment]
I tested this same thing on Arch Linux and got the same results. So it's either ruby version (2.7.0p0) or bundler version (2.1.4) causing problems.

**Comment by art-of-dom** [comment]
https://travis-ci.org/github/art-of-dom/Ceedling/jobs/662478708?utm_medium=notification&utm_source=github_status

This quick CI test shows that 2.7 has more warnings running the tests, but they do all pass the CI. I'm currently working on restoring the OSX CI then I think I'll try to clean up the warnings which may help your case.

**Comment by felipebalbi** [comment]
Interesting. I have this failing on both macOS and Arch Linux. Ruby and Bundle versions match.

/me reads TravisCI output

There's a `git submodule update --init --recursive` running on TravisCI which is not documented on README.md. After running that, I get all tests passing with the same warnings as TravisCI. I guess that should be patched.
