### ISSUE TITLE
NoMethodError: undefined method `values_at' for false:FalseClass

### ISSUE THREAD

**Issue by JanErikFoss** [ThrowTheSwitch/Ceedling#513]
Hi,

I suddenly ran into this problem that I can't figure out.
I've tried commenting out test code and source code, but the problem is still there.
Does anyone know how to resolve this?

```
> ceedling test:all


Test 'test_ble_adv.c'
---------------------
rake aborted!
NoMethodError: undefined method `values_at' for false:FalseClass
/Users/jani/.gem/ruby/2.6.0/gems/ceedling-0.30.0/lib/ceedling/cacheinator_helper.rb:25:in `diff_cached_defines?'
/Users/jani/.gem/ruby/2.6.0/gems/ceedling-0.30.0/lib/ceedling/cacheinator.rb:38:in `diff_cached_test_defines?'
/Users/jani/.gem/ruby/2.6.0/gems/ceedling-0.30.0/lib/ceedling/project_config_manager.rb:46:in `process_test_defines_change'
/Users/jani/.gem/ruby/2.6.0/gems/ceedling-0.30.0/lib/ceedling/preprocessinator.rb:24:in `preprocess_test_and_invoke_test_mocks'
/Users/jani/.gem/ruby/2.6.0/gems/ceedling-0.30.0/lib/ceedling/test_invoker.rb:83:in `block in setup_and_invoke'
/Users/jani/.gem/ruby/2.6.0/gems/ceedling-0.30.0/lib/ceedling/test_invoker.rb:51:in `setup_and_invoke'
/Users/jani/.gem/ruby/2.6.0/gems/ceedling-0.30.0/lib/ceedling/tasks_tests.rake:11:in `block (2 levels) in <top (required)>'
/Users/jani/.gem/ruby/2.6.0/gems/ceedling-0.30.0/bin/ceedling:346:in `block in <top (required)>'
/Users/jani/.gem/ruby/2.6.0/gems/ceedling-0.30.0/bin/ceedling:333:in `<top (required)>'
/usr/local/bin/ceedling:23:in `load'
/usr/local/bin/ceedling:23:in `<main>'
Tasks: TOP => test:all
(See full trace by running task with --trace)

--------------------
OVERALL TEST SUMMARY
--------------------

No tests executed.

**Comment by JanErikFoss** [comment]
This only happens on macos, not on my windows machine.

**Comment by JuPrgn** [comment]
Hi did you try ceedling clobber to clean everything and try again ?

**Comment by JanErikFoss** [comment]
That worked, thank you so much.
I found the clean command when reading the docs but somehow skipped the clobber command.
