### ISSUE TITLE
Don't know how to build task '.../unity.h'

### ISSUE THREAD

**Issue by bcsavas** [ThrowTheSwitch/Ceedling#558]
Hello,

I've encountered a strange ceedling behavior, and couldn't manage to find a solution so far.

I've used ceedling successfully with the Ruby Devkit 2.7.1 + MinGW installed from MSYS coming with the devkit.
Now I moved my project to a new laptop, this time I installed ruby 2.7.2 and MinGW latest version from chocolatey.org

When I run ceedling now, the following error occurs:
`Test 'test_AntiBouncer.c'
-------------------------
Generating dependencies for test_AntiBouncer.c...
Generating dependencies for unity.c...
Generating dependencies for AntiBouncer.c...
Generating runner for test_AntiBouncer.c...
Compiling test_AntiBouncer_runner.c...
#<Thread:0x0000000007043c68 C:/Company/temp/git-clone/emob-sw/unittest/vendor/ceedling/lib/ceedling/par_map.rb:7 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        11: from C:/Company/temp/git-clone/emob-sw/unittest/vendor/ceedling/lib/ceedling/par_map.rb:10:in `block (2 levels) in par_map'
        10: from C:/Company/temp/git-clone/emob-sw/unittest/vendor/ceedling/lib/ceedling/task_invoker.rb:97:in `block in invoke_test_objects'
         9: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
         8: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
         7: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `synchronize'
         6: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
         5: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:241:in `invoke_prerequisites'
         4: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:62:in `prerequisite_tasks'
         3: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:62:in `map'
         2: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:62:in `block in prerequisite_tasks'
         1: from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:66:in `lookup_prerequisite'
C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task_manager.rb:59:in `[]': Don't know how to build task 'C\\:/Company/temp/git-clone/emob-sw/unittest/vendor/ceedling/vendor/unity/src/unity.h' (See the list of available tasks with `rake --tasks`) (RuntimeError)
Did you mean?  C:/Company/temp/git-clone/emob-sw/unittest/vendor/ceedling/vendor/unity/src/unity.c
ERROR: Rake could not find file referenced in source or test: 'C\:/Company/temp/git-clone/emob-sw/unittest/vendor/ceedling/vendor/unity/src/unity.h'. Possible stale dependency.
Try fixing #include statements or adding missing file. Then run 'refresh:test' task and try again.
rake aborted!`

Every test fails like this.
The **temp_sensor** example works fine running from the same commad prompt, so ruby and gcc is set up correctly.
If I copy my test to the temp_sensor example, it runs from there without error!
What am I missing?

Thank you for your feedback

**Comment by bcsavas** [comment]
Setting `:use_deep_dependencies: FALSE` from TRUE solves the problem, s othe question is what went wrong with use_deep_dependencies
