### ISSUE TITLE
"gem install ceedling" and running old project always fails with TypeError after 0.31.0 release

### ISSUE THREAD

**Issue by Fetiu** [ThrowTheSwitch/Ceedling#559]
I found this while running the CI of my project.
```
$ gem install ceedling
Fetching: deep_merge-1.2.1.gem (100%)
Successfully installed deep_merge-1.2.1
Fetching: ceedling-0.31.0.gem (100%)
Successfully installed ceedling-0.31.0
Parsing documentation for deep_merge-1.2.1
Installing ri documentation for deep_merge-1.2.1
Parsing documentation for ceedling-0.31.0
Installing ri documentation for ceedling-0.31.0
Done installing documentation for deep_merge, ceedling after 1 seconds
2 gems installed
$ ceedling                  
Traceback (most recent call last):
	16: from /usr/local/bin/ceedling:23:in `<main>'
	15: from /usr/local/bin/ceedling:23:in `load'
	14: from /usr/local/lib/ruby/gems/2.5.0/gems/ceedling-0.31.0/bin/ceedling:329:in `<top (required)>'
	13: from /usr/local/lib/ruby/gems/2.5.0/gems/ceedling-0.31.0/lib/ceedling.rb:66:in `load_project'
	12: from /usr/local/lib/ruby/gems/2.5.0/gems/ceedling-0.31.0/lib/ceedling.rb:66:in `load'
	11: from /usr/local/lib/ruby/gems/2.5.0/gems/ceedling-0.31.0/lib/ceedling/rakefile.rb:47:in `<top (required)>'
	10: from /usr/local/lib/ruby/gems/2.5.0/gems/ceedling-0.31.0/lib/ceedling/setupinator.rb:25:in `do_setup'
	 9: from /usr/local/lib/ruby/gems/2.5.0/gems/ceedling-0.31.0/lib/ceedling/configurator.rb:120:in `populate_cmock_defaults'
	 8: from /usr/local/lib/ruby/gems/2.5.0/gems/ceedling-0.31.0/lib/ceedling/cmock_builder.rb:12:in `manufacture'
	 7: from /usr/local/lib/ruby/gems/2.5.0/gems/ceedling-0.31.0/lib/ceedling/cmock_builder.rb:12:in `new'
	 6: from /usr/local/lib/ruby/gems/2.5.0/gems/ceedling-0.31.0/vendor/cmock/lib/cmock.rb:18:in `initialize'
	 5: from /usr/local/lib/ruby/gems/2.5.0/gems/ceedling-0.31.0/vendor/cmock/lib/cmock.rb:18:in `new'
	 4: from /usr/local/lib/ruby/gems/2.5.0/gems/ceedling-0.31.0/vendor/cmock/lib/cmock_config.rb:83:in `initialize'
	 3: from /usr/local/lib/ruby/gems/2.5.0/gems/ceedling-0.31.0/vendor/cmock/lib/cmock_config.rb:83:in `map'
	 2: from /usr/local/lib/ruby/gems/2.5.0/gems/ceedling-0.31.0/vendor/cmock/lib/cmock_config.rb:84:in `block in initialize'
	 1: from /usr/local/lib/ruby/gems/2.5.0/gems/ceedling-0.31.0/vendor/cmock/lib/cmock_config.rb:84:in `Pathname'
/usr/local/lib/ruby/gems/2.5.0/gems/ceedling-0.31.0/vendor/cmock/lib/cmock_config.rb:84:in `initialize': no implicit conversion of nil into String (TypeError)
```
Seems like the update happened 16 hours before, so I thought this could be the bug of this release.
I could find `gem uninstall ceedling` and then `gem install -v 0.30.0` resolves this problem.

**Comment by CezaryGapinski** [comment]
I've noticed this behavior appears after this commit b063510652f217b24071f2a038e14b2d84708a35
Can you show your `cmock` section in `project.yml` file? I can reproduce traceback you noticed when my cmock `unity_helper_path` section has empty list entry:
```yml
:cmock:
  :unity_helper_path:
    -
```
which is not necessarily correct, so maybe you have something wrong in your `project.yml`.

**Comment by Fetiu** [comment]
Thank you. You were perfectly right. I was using an empty string here.
```
  :unity_helper_path:
    # for Unity memory assert macro, put headers that define incomplete type
    -
```
I guess then this must be deleted? I wanted to keep this as a placeholder incase I need to add something in the future...

**Comment by CezaryGapinski** [comment]
I think it is better to remove this empty string from yml file than do something special with `cmock` or `ceedling` to support empty list entries.
Maybe ceedling grandmaster @mvandervoord can help and show the right direction :).

**Comment by mvandervoord** [comment]
Hahaha... grandmaster? Seems like a fancy title to me! ;)

This seems like a good place for a multi-phase fix. Ultimately, Ceedling shouldn't crash on something like this... it should politely complain and/or just run with the assumption there IS no unity helper.

In the meantime, if you'd like to keep this around in case you need it, maybe just put a `#` before both lines so they don't give you any trouble? It'd also be interesting to know if you can get away with `:unity_helper_path: [ ]`

**Comment by beckerzito** [comment]
Hey @mvandervoord I guess that issue doesn't happen only for the unity helpers. But for any YML configuration that receives an empty line. I've already faced an issue like this one on the define section, where I wanted to let the 'defines' sections empty to use only when needed, but placed there to remember where the defines should be created. For example:

![image](https://user-images.githubusercontent.com/26304432/108886851-3b23da80-75e8-11eb-9441-769cc206d165.png)

To solve that, I had to add that comment on line 19 with the IMPORTANT statement, but it would be great if ceedling understands that if an empty value and continues to run normally.
