### ISSUE TITLE
Unable to run ceedling

### ISSUE THREAD

**Issue by rnicolas** [ThrowTheSwitch/Ceedling#567]
After installation of ceedling (ruby version 3.0.0), I can create an example project issuing `ceedling example temp_sensor`, but when I go inside the project, and I run `ceedling test:all` I get this error:

```
$ ceedling test:all
rake aborted!
ArgumentError: wrong number of arguments (given 2, expected 1)
C:/Ruby30-x64/bin/ceedling:23:in `load'
C:/Ruby30-x64/bin/ceedling:23:in `<main>'
Tasks: TOP => test:all => test_deps => directories => build/test/mocks
(See full trace by running task with --trace)
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ceedling-0.31.0/lib/ceedling/yaml_wrapper.rb:12:in `initialize': No such file or directory @ rb_sysopen - build/test/cache/input.yml (Errno::ENOENT)
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ceedling-0.31.0/lib/ceedling/yaml_wrapper.rb:12:in `open'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ceedling-0.31.0/lib/ceedling/yaml_wrapper.rb:12:in `dump'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ceedling-0.31.0/lib/ceedling/cacheinator.rb:7:in `cache_test_config'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ceedling-0.31.0/lib/ceedling/rakefile.rb:66:in `block in <top (required)>'
```

Ceedling version is the following ones:

```
   Ceedling:: 0.31.0
      Unity:: 2.5.2
      CMock:: 2.5.3
 CException:: 1.3.3
```

And the OS is MS Windows 10. Any idea of what's going on?

**Comment by rnicolas** [comment]
I have an answer. Ceedling does not work with Ruby 3.0.0, to get it running I had to downgrade Ruby to 2.7.2

**Comment by rnicolas** [comment]
Duplicate of #551
