### ISSUE TITLE
"create:module" with ":includes:"  in "project.yml" goes implicit conversion

### ISSUE THREAD

**Issue by MrRedKite** [ThrowTheSwitch/Ceedling#568]
Hello,
in my project I want to use the ceedling module generator and it works fine as long as I dont use ":includes" in the "project.yml".
For testing I created the example project "temp_sensor" and used "ceedling module:create[foo]" to create the corresponding files.
It worked as expected.
Now I added to the "project.yml" the following lines:

```
:module_generator:
  :includes:
    - board.h
    - defs.h
```

I removed the foo files and ran "ceedling module:create[foo]" again.
Now I got the following message:

```
rake aborted!
TypeError: no implicit conversion of Symbol into Integer
/var/lib/gems/2.7.0/gems/ceedling-0.31.0/vendor/unity/auto/generate_module.rb:159:in `block (2 levels) in files_to_operate_on'
/var/lib/gems/2.7.0/gems/ceedling-0.31.0/vendor/unity/auto/generate_module.rb:150:in `each_pair'
/var/lib/gems/2.7.0/gems/ceedling-0.31.0/vendor/unity/auto/generate_module.rb:150:in `block in files_to_operate_on'
/var/lib/gems/2.7.0/gems/ceedling-0.31.0/vendor/unity/auto/generate_module.rb:149:in `each'
/var/lib/gems/2.7.0/gems/ceedling-0.31.0/vendor/unity/auto/generate_module.rb:149:in `files_to_operate_on'
/var/lib/gems/2.7.0/gems/ceedling-0.31.0/vendor/unity/auto/generate_module.rb:192:in `generate'
/var/lib/gems/2.7.0/gems/ceedling-0.31.0/plugins/module_generator/lib/module_generator.rb:17:in `create'
/var/lib/gems/2.7.0/gems/ceedling-0.31.0/plugins/module_generator/module_generator.rake:24:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.7.0/gems/ceedling-0.31.0/plugins/module_generator/module_generator.rake:13:in `each'
/var/lib/gems/2.7.0/gems/ceedling-0.31.0/plugins/module_generator/module_generator.rake:13:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.7.0/gems/ceedling-0.31.0/bin/ceedling:345:in `block in <top (required)>'
/var/lib/gems/2.7.0/gems/ceedling-0.31.0/bin/ceedling:332:in `<top (required)>'
/usr/local/bin/ceedling:23:in `load'
/usr/local/bin/ceedling:23:in `<main>'
Tasks: TOP => module:create
(See full trace by running task with --trace)
ERROR: Ceedling Failed
```

Am I using the module generator in the wrong way?

thank you

**Comment by CezaryGapinski** [comment]
It is not stated in the readme , but I think this plugin has three subsections where you can specify includes for source, include and test files. You can try something like below and adapt it to your needs.

```yml
:module_generator:
  :includes:
    :inc:
      - board.h
      - defs.h
    :src:
      - board.h
      - defs.h
    :tst:
      - board.h
      - defs.h
 ```

**Comment by MrRedKite** [comment]
Thank you, this works great.
I did a pull request with the updated readme in the module_generator plugin.
