### ISSUE TITLE
Compiling does not work after changning project.yml, but does after second compile call

### ISSUE THREAD

**Issue by ErdlingProductions** [ThrowTheSwitch/Ceedling#625]
Hello,

when I change the compiler options in the `project.yml` file, the first time I call `ceedling release` or `ceedling test:all`, I get the attached error message. However, if I just call `ceedling release` or `ceedling test:all`again, it works just fine.
Why do I have this issue? Thanks and best regards.

```
Release build 'MyPicApp.out'
----------------------------
#<Thread:0x000056445b79a478@/var/lib/gems/2.5.0/gems/ceedling-0.31.1/lib/ceedling/par_map.rb:7 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	11: from /var/lib/gems/2.5.0/gems/ceedling-0.31.1/lib/ceedling/par_map.rb:10:in \`block (2 levels) in par_map'
	10: from /var/lib/gems/2.5.0/gems/ceedling-0.31.1/lib/ceedling/task_invoker.rb:118:in \`block in invoke_release_objects'
	 9: from /var/lib/gems/2.5.0/gems/rake-13.0.6/lib/rake/task.rb:188:in \`invoke'
	 8: from /var/lib/gems/2.5.0/gems/rake-13.0.6/lib/rake/task.rb:199:in \`invoke_with_call_chain'
	 7: from /usr/lib/ruby/2.5.0/monitor.rb:226:in \`mon_synchronize'
	 6: from /var/lib/gems/2.5.0/gems/rake-13.0.6/lib/rake/task.rb:218:in \`block in invoke_with_call_chain'
	 5: from /var/lib/gems/2.5.0/gems/rake-13.0.6/lib/rake/task.rb:241:in \`invoke_prerequisites'
	 4: from /var/lib/gems/2.5.0/gems/rake-13.0.6/lib/rake/task.rb:62:in \`prerequisite_tasks'
	 3: from /var/lib/gems/2.5.0/gems/rake-13.0.6/lib/rake/task.rb:62:in \`map'
	 2: from /var/lib/gems/2.5.0/gems/rake-13.0.6/lib/rake/task.rb:62:in \`block in prerequisite_tasks'
	 1: from /var/lib/gems/2.5.0/gems/rake-13.0.6/lib/rake/task.rb:66:in \`lookup_prerequisite'
/var/lib/gems/2.5.0/gems/rake-13.0.6/lib/rake/task_manager.rb:59:in \`[]': Don't know how to build task 'build/release/dependencies/force_build' (See the list of available tasks with \`rake --tasks\`) (RuntimeError)
Did you mean?  build/test/dependencies/force_build
ERROR: Rake could not find file referenced in source: 'build/release/dependencies/force_build'. Possible stale dependency.
rake aborted!

/var/lib/gems/2.5.0/gems/ceedling-0.31.1/lib/ceedling/build_invoker_utils.rb:33:in \`process_exception'
/var/lib/gems/2.5.0/gems/ceedling-0.31.1/lib/ceedling/release_invoker.rb:18:in \`rescue in setup_and_invoke_c_objects'
/var/lib/gems/2.5.0/gems/ceedling-0.31.1/lib/ceedling/release_invoker.rb:12:in \`setup_and_invoke_c_objects'
/var/lib/gems/2.5.0/gems/ceedling-0.31.1/lib/ceedling/tasks_release.rake:17:in \`block in <top (required)>'
/var/lib/gems/2.5.0/gems/ceedling-0.31.1/bin/ceedling:345:in \`block in <top (required)>'
/var/lib/gems/2.5.0/gems/ceedling-0.31.1/bin/ceedling:332:in \`<top (required)>'
/usr/local/bin/ceedling:23:in \`load'
/usr/local/bin/ceedling:23:in \`<main>'

Caused by:
Don't know how to build task 'build/release/dependencies/force_build' (See the list of available tasks with \`rake --tasks\`)
Did you mean?  build/test/dependencies/force_build
/var/lib/gems/2.5.0/gems/ceedling-0.31.1/lib/ceedling/task_invoker.rb:118:in \`block in invoke_release_objects'
/var/lib/gems/2.5.0/gems/ceedling-0.31.1/lib/ceedling/par_map.rb:10:in \`block (2 levels) in par_map'
Tasks: TOP => release
(See full trace by running task with --trace)
```

**Comment by ic-twist** [comment]
I'm observing the same issue here.

Here's how I reproduced the problem in 4 steps:
1. I changed the output name of my release build in `project.yml`
![image](https://user-images.githubusercontent.com/89994664/151467648-431f208a-e103-469a-a68d-4cc03d7241ff.png)
2. I run `ceedling release` and get this error:
```
me$ ceedling release


Release build 'myProgram.out'
-----------------------------
#<Thread:0x000055c21f9a1960 /var/lib/gems/2.7.0/gems/ceedling-0.31.1/lib/ceedling/par_map.rb:7 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        11: from /var/lib/gems/2.7.0/gems/ceedling-0.31.1/lib/ceedling/par_map.rb:10:in `block (2 levels) in par_map'
        10: from /var/lib/gems/2.7.0/gems/ceedling-0.31.1/lib/ceedling/task_invoker.rb:118:in `block in invoke_release_objects'
         9: from /usr/share/rubygems-integration/all/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
         8: from /usr/share/rubygems-integration/all/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
         7: from /usr/share/rubygems-integration/all/gems/rake-13.0.1/lib/rake/task.rb:199:in `synchronize'
         6: from /usr/share/rubygems-integration/all/gems/rake-13.0.1/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
         5: from /usr/share/rubygems-integration/all/gems/rake-13.0.1/lib/rake/task.rb:241:in `invoke_prerequisites'
         4: from /usr/share/rubygems-integration/all/gems/rake-13.0.1/lib/rake/task.rb:62:in `prerequisite_tasks'
         3: from /usr/share/rubygems-integration/all/gems/rake-13.0.1/lib/rake/task.rb:62:in `map'
         2: from /usr/share/rubygems-integration/all/gems/rake-13.0.1/lib/rake/task.rb:62:in `block in prerequisite_tasks'
         1: from /usr/share/rubygems-integration/all/gems/rake-13.0.1/lib/rake/task.rb:66:in `lookup_prerequisite'
/usr/share/rubygems-integration/all/gems/rake-13.0.1/lib/rake/task_manager.rb:59:in `[]': Don't know how to build task 'build/release/dependencies/force_build' (See the list of available tasks with `rake --tasks`) (RuntimeError)
Did you mean?  build/test/dependencies/force_build
ERROR: Rake could not find file referenced in source: 'build/release/dependencies/force_build'. Possible stale dependency.
rake aborted!

/var/lib/gems/2.7.0/gems/ceedling-0.31.1/lib/ceedling/build_invoker_utils.rb:33:in `process_exception'
/var/lib/gems/2.7.0/gems/ceedling-0.31.1/lib/ceedling/release_invoker.rb:18:in `rescue in setup_and_invoke_c_objects'
/var/lib/gems/2.7.0/gems/ceedling-0.31.1/lib/ceedling/release_invoker.rb:12:in `setup_and_invoke_c_objects'
/var/lib/gems/2.7.0/gems/ceedling-0.31.1/lib/ceedling/tasks_release.rake:17:in `block in <top (required)>'
/var/lib/gems/2.7.0/gems/ceedling-0.31.1/bin/ceedling:345:in `block in <top (required)>'
/var/lib/gems/2.7.0/gems/ceedling-0.31.1/bin/ceedling:332:in `<top (required)>'
/usr/local/bin/ceedling:23:in `load'
/usr/local/bin/ceedling:23:in `<main>'

Caused by:
Don't know how to build task 'build/release/dependencies/force_build' (See the list of available tasks with `rake --tasks`)
Did you mean?  build/test/dependencies/force_build
/var/lib/gems/2.7.0/gems/ceedling-0.31.1/lib/ceedling/task_invoker.rb:118:in `block in invoke_release_objects'
/var/lib/gems/2.7.0/gems/ceedling-0.31.1/lib/ceedling/par_map.rb:10:in `block (2 levels) in par_map'
Tasks: TOP => release
(See full trace by running task with --trace)
```
3. I run `ceedling test` or `ceedling clean`. It was successful.
4. I run `ceedling release` again and now it's successful.


The release build in project.yml has all the default configurations (except that I changed the output name). What is causing this?
