### ISSUE TITLE
current and parent directories fail in single-line path specs in .yml

### ISSUE THREAD

**Issue by hmijail** [ThrowTheSwitch/Ceedling#63]
(I don't think this is the same as #55)

This works:

```
:paths:
  :test: 
    - .
```

This doesn't:

```
:paths:
    :test: .
```

Same thing with ".." or any other path containing them.

The full error is:

```
rake aborted!
NoMethodError: undefined method `flatten' for ".":String
/Users/mija/.gem/ruby/2.0.0/gems/ceedling-0.20.3/lib/ceedling/configurator.rb:327:in `eval_path_list'
/Users/mija/.gem/ruby/2.0.0/gems/ceedling-0.20.3/lib/ceedling/configurator.rb:217:in `block in eval_paths'
/Users/mija/.gem/ruby/2.0.0/gems/ceedling-0.20.3/lib/ceedling/configurator.rb:217:in `each_pair'
/Users/mija/.gem/ruby/2.0.0/gems/ceedling-0.20.3/lib/ceedling/configurator.rb:217:in `eval_paths'
/Users/mija/.gem/ruby/2.0.0/gems/ceedling-0.20.3/lib/ceedling/setupinator.rb:28:in `do_setup'
/Users/mija/.gem/ruby/2.0.0/gems/ceedling-0.20.3/lib/ceedling/rakefile.rb:46:in `<top (required)>'
/Users/mija/.gem/ruby/2.0.0/gems/ceedling-0.20.3/lib/ceedling.rb:66:in `load'
/Users/mija/.gem/ruby/2.0.0/gems/ceedling-0.20.3/lib/ceedling.rb:66:in `load_project'
<snip>/test/ceedling/rakefile.rb:3:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by mvandervoord** [comment]
Thanks.

They are two very different things in YAML language. In the first, you are
telling in that you have a single element array with one string. In the
second, you are telling it you have a string.

Usually in Ceedling we try to make it smart and, if you specify a string,
it automatically converts it to a single element array with a string for
internal use. Obviously we missed some cases. I'll add this to our list of
things to fix. Thanks for the help!

Mark
