### ISSUE TITLE
Would be nice if Ceedling said where it is having problems digesting the .yml

### ISSUE THREAD

**Issue by hmijail** [ThrowTheSwitch/Ceedling#64]
In the error 

```
rake aborted!
NoMethodError: undefined method `flatten' for ".":String
/Users/mija/.gem/ruby/2.0.0/gems/ceedling-0.20.3/lib/ceedling/configurator.rb:327:in `eval_path_list'
/Users/mija/.gem/ruby/2.0.0/gems/ceedling-0.20.3/lib/ceedling/configurator.rb:217:in `block in eval_paths'
/Users/mija/.gem/ruby/2.0.0/gems/ceedling-0.20.3/lib/ceedling/configurator.rb:217:in `each_pair'
/Users/mija/.gem/ruby/2.0.0/gems/ceedling-0.20.3/lib/ceedling/configurator.rb:217:in `eval_paths'
/Users/mija/.gem/ruby/2.0.0/gems/ceedling-0.20.3/lib/ceedling/setupinator.rb:28:in `do_setup'
/Users/mija/.gem/ruby/2.0.0/gems/ceedling-0.20.3/lib/ceedling/rakefile.rb:46:in `<top (required)>'
/Users/mija/.gem/ruby/2.0.0/gems/ceedling-0.20.3/lib/ceedling.rb:66:in `load'
/Users/mija/.gem/ruby/2.0.0/gems/ceedling-0.20.3/lib/ceedling.rb:66:in `load_project'
<snip>/test/ceedling/rakefile.rb:3:in `<top (required)>'
(See full trace by running task with --trace)
```

It would be good if Ceedling said that the problem was found while parsing such-and-such variable, or the line in the yml file if possible.
Note that --trace doesn't help.

**Comment by mvandervoord** [comment]
Yeah, I wish the yaml ruby class would report that for us nicely too. ;)

I've been thinking we should capture the YAML parsing errors and see if
there is anything we can do to make clearer suggestions. This is a good
supporting case for that.

**Comment by mkarlesky** [comment]
Thankfully, YAML parsing problems are now logged as of a long time ago, though not necessarily always with exhaustive detail.
