### ISSUE TITLE
command_hooks plugin array of executables causes error

### ISSUE THREAD

**Issue by riestmo** [ThrowTheSwitch/Ceedling#647]
When I'm trying to run an array of executables in a pre_build hook, I get the following error:

Traceback (most recent call last):
        9: from /opt/ruby/2.6.3-rh7_64/bin/ceedling:23:in `<main>'
        8: from /opt/ruby/2.6.3-rh7_64/bin/ceedling:23:in `load'
        7: from /opt/ruby/2.6.3-rh7_64/lib/ruby/gems/2.6.0/gems/ceedling-0.31.0/bin/ceedling:329:in `<top (required)>'
        6: from /opt/ruby/2.6.3-rh7_64/lib/ruby/gems/2.6.0/gems/ceedling-0.31.0/lib/ceedling.rb:66:in `load_project'
        5: from /opt/ruby/2.6.3-rh7_64/lib/ruby/gems/2.6.0/gems/ceedling-0.31.0/lib/ceedling.rb:66:in `load'
        4: from /opt/ruby/2.6.3-rh7_64/lib/ruby/gems/2.6.0/gems/ceedling-0.31.0/lib/ceedling/rakefile.rb:47:in `<top (required)>'
        3: from /opt/ruby/2.6.3-rh7_64/lib/ruby/gems/2.6.0/gems/ceedling-0.31.0/lib/ceedling/setupinator.rb:29:in `do_setup'
        2: from /opt/ruby/2.6.3-rh7_64/lib/ruby/gems/2.6.0/gems/ceedling-0.31.0/lib/ceedling/configurator.rb:132:in `tools_setup'
        1: from /opt/ruby/2.6.3-rh7_64/lib/ruby/gems/2.6.0/gems/ceedling-0.31.0/lib/ceedling/configurator.rb:132:in `each_key'
/opt/ruby/2.6.3-rh7_64/lib/ruby/gems/2.6.0/gems/ceedling-0.31.0/lib/ceedling/configurator.rb:136:in `block in tools_setup': no implicit conversion of Symbol into Integer (TypeError)

I followed the description in plugin_command_hooks.md and setup my project.yml as follows:

:tools:
  :pre_build:
    -  :executable: echo
       :arguments: "${1} was glorious!"
    -  :executable: echo
       :arguments:
         - it kinda made me cry a little.
         - you?

Any ideas how to fix the setup to run more than one executable in a pre_build step?

**Comment by riestmo** [comment]
Duplicate to #459 
Therefore closed again
