### ISSUE TITLE
Ceedling randomly crashing with FrozenError: can't modify frozen String

### ISSUE THREAD

**Issue by Klievan** [ThrowTheSwitch/Ceedling#660]
I'm running Ceedling using the docker image provided. Ceedling randomly crashes with "can't modify frozen String" error on scrubbing the output given by the test itself. This is running ceedling-0.31.1. Rerunning the test solves the issue 90% of the time. 

```
Compiling cmock.c...
Linking test_nordic9160_init.out...
Running test_nordic9160_init.out...
 ************** Restored defines and build path
rake aborted!
FrozenError: can't modify frozen String: "[REDACTED TEST OUTPUT]-----------------------\n1 Tests 1 Failures 0 Ignored \nFAIL\n"
/app/testing/vendor/ceedling/lib/ceedling/tool_executor.rb:76:in `scrub!'
/app/testing/vendor/ceedling/lib/ceedling/tool_executor.rb:76:in `exec'
/app/testing/vendor/ceedling/lib/ceedling/generator.rb:161:in `generate_test_results'
/app/testing/vendor/ceedling/lib/ceedling/rules_tests.rake:56:in `block in <top (required)>'
/app/testing/vendor/ceedling/lib/ceedling/task_invoker.rb:86:in `invoke_test_results'
/app/testing/vendor/ceedling/lib/ceedling/test_invoker.rb:123:in `block in setup_and_invoke'
/app/testing/vendor/ceedling/lib/ceedling/test_invoker.rb:63:in `each'
/app/testing/vendor/ceedling/lib/ceedling/test_invoker.rb:63:in `setup_and_invoke'
/app/testing/vendor/ceedling/lib/ceedling/rules_tests.rake:71:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/ceedling-0.31.1/bin/ceedling:345:in `block in <top (required)>'
/usr/local/bundle/gems/ceedling-0.31.1/bin/ceedling:332:in `<top (required)>'
/usr/local/bundle/bin/ceedling:23:in `load'
/usr/local/bundle/bin/ceedling:23:in `<main>'
Tasks: TOP => build/test/results/test_nordic9160_init.pass
(See full trace by running task with --trace)
```

**Comment by Letme** [comment]
we are going to need a bit more than that. Since you are running initialization I assume you do some memory initialization (with  CPU defines/variables)- could that be the reason? This sounds at first glance as bad memory access.

**Comment by Klievan** [comment]
Correct, it was an invalid memory access. Thanks for pointing us in the right direction!
