### ISSUE TITLE
CEEDLING_MAIN_PROJECT_FILE is ignored

### ISSUE THREAD

**Issue by hmijail** [ThrowTheSwitch/Ceedling#67]
The docs say that setting this environment variable should change where Ceedling looks for the project.yml file. Doesn't seem to be working.

**Comment by hmijail** [comment]
(incidentally, wouldn't it be better to do this through the command line? I would say that that's the typical way of doing this kind of thing...)

**Comment by hmijail** [comment]
Looks like CEEDLING_MAIN_PROJECT_FILE is not totally ignored, just very broken. 

Some more detail: 
- If I'm in a directory which contains a project.yml file AND the CEEDLING_MAIN_PROJECT_FILE points to a directory, then I get this error trace:
```
$ceedling verbosity[4] test:all --trace
rake aborted!
Errno::EISDIR: Is a directory - /Users/mija/programming/Trinity/trinity_v3/library/TCommon/ceedling/
/Users/mija/.gem/ruby/2.0.0/gems/ceedling-0.20.3/lib/ceedling/yaml_wrapper.rb:8:in `read'
/Users/mija/.gem/ruby/2.0.0/gems/ceedling-0.20.3/lib/ceedling/yaml_wrapper.rb:8:in `load'
/Users/mija/.gem/ruby/2.0.0/gems/ceedling-0.20.3/lib/ceedling/project_file_loader.rb:54:in `load_project_config'
/Users/mija/.gem/ruby/2.0.0/gems/ceedling-0.20.3/lib/ceedling/setupinator.rb:14:in `load_project_files'
/Users/mija/.gem/ruby/2.0.0/gems/ceedling-0.20.3/lib/ceedling/rakefile.rb:38:in `<top (required)>'
/Users/mija/.gem/ruby/2.0.0/gems/ceedling-0.20.3/lib/ceedling.rb:66:in `load'
/Users/mija/.gem/ruby/2.0.0/gems/ceedling-0.20.3/lib/ceedling.rb:66:in `load_project'
/Users/mija/programming/Trinity/trinity_v3/library/TCommon/ceedling/rakefile.rb:3:in `<top (required)>'
/Users/mija/.gem/ruby/2.0.0/gems/rake-11.1.2/lib/rake/rake_module.rb:28:in `load'
/Users/mija/.gem/ruby/2.0.0/gems/rake-11.1.2/lib/rake/rake_module.rb:28:in `load_rakefile'
/Users/mija/.gem/ruby/2.0.0/gems/rake-11.1.2/lib/rake/application.rb:689:in `raw_load_rakefile'
/Users/mija/.gem/ruby/2.0.0/gems/rake-11.1.2/lib/rake/application.rb:94:in `block in load_rakefile'
/Users/mija/.gem/ruby/2.0.0/gems/rake-11.1.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/mija/.gem/ruby/2.0.0/gems/rake-11.1.2/lib/rake/application.rb:93:in `load_rakefile'
/Users/mija/.gem/ruby/2.0.0/gems/rake-11.1.2/lib/rake/application.rb:77:in `block in run'
/Users/mija/.gem/ruby/2.0.0/gems/rake-11.1.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/mija/.gem/ruby/2.0.0/gems/rake-11.1.2/lib/rake/application.rb:75:in `run'
/Users/mija/.gem/ruby/2.0.0/gems/rake-11.1.2/bin/rake:33:in `<top (required)>'
/Users/mija/.gem/ruby/2.0.0/bin/rake:23:in `load'
/Users/mija/.gem/ruby/2.0.0/bin/rake:23:in `<main>'

```
- In any other situation, CEEDLING_MAIN_PROJECT_FILE doesn't seem to have any effect.

**Comment by mkarlesky** [comment]
As of 1.0.0 this has been fixed and much improved upon.  The environment variable `CEEDLING_MAIN_PROJECT_FILE` has become `CEEDLING_PROJECT_FILE` and now works properly. A project configuration file can be specified via a command line flag. The new Mixins feature provides a great deal of flexibility in what a project configuration contains through an ability to control how settings are merged into a final configuration from environment variables, command line flags, and configuration blocks.
