### ISSUE TITLE
Disable internal sanity check for test fixture.

### ISSUE THREAD

**Issue by lcavalli** [ThrowTheSwitch/Ceedling#693]
Hi,

I'm executing my cross-compiled unit test in a SPARC LEON simulator that makes the internal sanity check fails:

```
> Shell executed command:
'sparc-rtems6-sis -leon3 -c test/support/run_cmd "build/test/out/test_add.elf" &'
> Produced output:
SIS - SPARC/RISCV instruction simulator 2.29,  copyright Jiri Gaisler 2020
 Bug-reports to jiri@gaisler.se

 LEON3 emulation enabled, 1 cpus online, delta 50 clocks

 Loaded build/test/out/test_add.elf, entry 0x40000000
sis> run
test_add.c:27:test_add_one:PASS
test_add.c:40:test_add_two:FAIL: Expected 0 Was 3
test_add.c:48:test_add_three:FAIL: Expected 0 Was 3
test_add.c:56:test_add_four:FAIL: Expected 0 Was 3
test_add.c:61:test_add_five:IGNORE: Skipped test

-----------------------
5 Tests 3 Failures 1 Ignored
FAIL


ERROR: Internal sanity check for test fixture 'test_add.elf' finds that Unity's final test count (5) does not match Ceedling's summation of all test cases (4).
  Possible causes:
    1. Your test + source dereferenced a null pointer.
    2. Your test + source indexed past the end of a buffer.
    3. Your test + source committed a memory access violation.
    4. Your test fixture produced an exit code of 0 despite execution ending prematurely.
  Sanity check failures of test results are usually a symptom of interrupted test execution.

rake aborted!
```

This is the portion of the project yaml configuration file:

```yaml
# Cross toolchain
:tools:
  :test_compiler:
    :executable: sparc-gaisler-elf-gcc
    :name: 'SPARC gcc compiler'
    :arguments:
      - -qbsp=leon3
      - -mcpu=leon3
      - -O0
      - -I"$": COLLECTION_PATHS_TEST_TOOLCHAIN_INCLUDE
      - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
      - -c
      - -o "${2}"
      - '"${1}"'

  :test_linker:
    :executable: sparc-gaisler-elf-gcc
    :name: 'SPARC ld linker'
    :arguments:
      - -qbsp=leon3
      - -mcpu=leon3
      - -o "${2}"
      - '"${1}"'

  :test_fixture:
    :executable: sparc-rtems6-sis
    :name: 'SPARC emulator'
    :arguments:
      - -leon3
      - -c test/support/run_cmd
      - '"${1}"'
      - '&'
```

The script file test/support/run_cmd contains a single line with `run` command.
Looking at source code here https://github.com/ThrowTheSwitch/Ceedling/blob/master/lib/ceedling/generator_test_results_sanity_checker.rb it seems that sanity check can be disabled, but I don't know how. I tried several combinations of `:sanity_checks: none` in different places without success.

Thanks.

**Comment by lcavalli** [comment]
As reported in PR https://github.com/ThrowTheSwitch/Ceedling/pull/32 I tried to define `CEEDLING_IGNORE_SANITY_CHECK` in my project yaml configuration file:

```yaml
:defines:
  # in order to add common defines:
  #  1) remove the trailing [] from the :common: section
  #  2) add entries to the :common: section (e.g. :test: has TEST defined)
  :common: &common_defines
    - CEEDLING_IGNORE_SANITY_CHECK
  :test:
    - *common_defines
    - TEST
  :test_preprocess:
    - *common_defines
    - TEST
```

But my problem is still present.

**Comment by lcavalli** [comment]
Further investigations revealed that there is a mismatch between unity tests count and ceedling tests count (as stated in the error message) because the passed tests are not taken into account.

```
Test 'test_add.c'
-----------------
> Shell executed command:
'gcc -E -MM -MG -I"/var/lib/gems/2.7.0/gems/ceedling-0.31.1/vendor/unity/src" -I"/var/lib/gems/2.7.0/gems/ceedling-0.31.1/vendor/cmock/src" -I"build/test/mocks" -I"test" -I"test/support" -I"../test/src" -I"../test/include" -DTEST -DTEST -DGNU_COMPILER "build/temp/_test_add.c"'
> Produced output:
_test_add.o: build/temp/_test_add.c \
 /var/lib/gems/2.7.0/gems/ceedling-0.31.1/vendor/unity/src/unity.h \
 /var/lib/gems/2.7.0/gems/ceedling-0.31.1/vendor/unity/src/unity_internals.h \
 @@@@unity.h ../test/include/add.h @@@@add.h

> Shell executed command:
'gcc -E -I"/var/lib/gems/2.7.0/gems/ceedling-0.31.1/vendor/unity/src" -I"/var/lib/gems/2.7.0/gems/ceedling-0.31.1/vendor/cmock/src" -I"build/test/mocks" -I"test" -I"test/support" -I"../test/src" -I"../test/include" -DTEST -DTEST -DGNU_COMPILER "test/test_add.c" -o "build/test/preprocess/files/test_add.c"'

Generating runner for test_add.c...
Compiling test_add_runner.c...
> Shell executed command:
'sparc-gaisler-elf-gcc -qbsp=leon3 -mcpu=leon3 -O0 -I"/var/lib/gems/2.7.0/gems/ceedling-0.31.1/vendor/unity/src" -I"/var/lib/gems/2.7.0/gems/ceedling-0.31.1/vendor/cmock/src" -I"build/test/mocks" -I"test" -I"test/support" -I"../test/src" -I"../test/include" -c -o "build/test/out/c/test_add_runner.o" "build/test/runners/test_add_runner.c"'

Compiling test_add.c...
> Shell executed command:
'sparc-gaisler-elf-gcc -qbsp=leon3 -mcpu=leon3 -O0 -I"/var/lib/gems/2.7.0/gems/ceedling-0.31.1/vendor/unity/src" -I"/var/lib/gems/2.7.0/gems/ceedling-0.31.1/vendor/cmock/src" -I"build/test/mocks" -I"test" -I"test/support" -I"../test/src" -I"../test/include" -c -o "build/test/out/c/test_add.o" "test/test_add.c"'

Linking test_add.elf...
> Shell executed command:
'sparc-gaisler-elf-gcc -qbsp=leon3 -mcpu=leon3 -o "build/test/out/test_add.elf" "build/test/out/c/test_add_runner.o" "build/test/out/c/test_add.o" "build/test/out/c/unity.o" "build/test/out/c/add.o" "build/test/out/c/cmock.o"'

Running test_add.elf...
> Shell executed command:
'sparc-rtems6-sis -leon3 -c test/support/run_cmd "build/test/out/test_add.elf" &'
> Produced output:
SIS - SPARC/RISCV instruction simulator 2.29,  copyright Jiri Gaisler 2020
 Bug-reports to jiri@gaisler.se

 LEON3 emulation enabled, 1 cpus online, delta 50 clocks

 Loaded build/test/out/test_add.elf, entry 0x40000000
sis> run
test_add.c:27:test_add_one:PASS
test_add.c:35:test_add_two:PASS

-----------------------
2 Tests 0 Failures 0 Ignored
OK


ERROR: Internal sanity check for test fixture 'test_add.elf' finds that Unity's final test count (2) does not match Ceedling's summation of all test cases (0).
  Possible causes:
    1. Your test + source dereferenced a null pointer.
    2. Your test + source indexed past the end of a buffer.
    3. Your test + source committed a memory access violation.
    4. Your test fixture produced an exit code of 0 despite execution ending prematurely.
  Sanity check failures of test results are usually a symptom of interrupted test execution.

rake aborted!

/var/lib/gems/2.7.0/gems/ceedling-0.31.1/lib/ceedling/generator_test_results_sanity_checker.rb:61:in `sanity_check_warning'
/var/lib/gems/2.7.0/gems/ceedling-0.31.1/lib/ceedling/generator_test_results_sanity_checker.rb:42:in `verify'
/var/lib/gems/2.7.0/gems/ceedling-0.31.1/lib/ceedling/generator_test_results.rb:53:in `process_and_write_results'
/var/lib/gems/2.7.0/gems/ceedling-0.31.1/lib/ceedling/generator.rb:175:in `generate_test_results'
/var/lib/gems/2.7.0/gems/ceedling-0.31.1/lib/ceedling/rules_tests.rake:55:in `block in <top (required)>'
/var/lib/gems/2.7.0/gems/ceedling-0.31.1/lib/ceedling/task_invoker.rb:107:in `invoke_test_results'
/var/lib/gems/2.7.0/gems/ceedling-0.31.1/lib/ceedling/test_invoker.rb:125:in `block in setup_and_invoke'
/var/lib/gems/2.7.0/gems/ceedling-0.31.1/lib/ceedling/test_invoker.rb:51:in `setup_and_invoke'
/var/lib/gems/2.7.0/gems/ceedling-0.31.1/lib/ceedling/tasks_tests.rake:13:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.7.0/gems/ceedling-0.31.1/bin/ceedling:345:in `block in <top (required)>'
/var/lib/gems/2.7.0/gems/ceedling-0.31.1/bin/ceedling:332:in `<top (required)>'
/usr/local/bin/ceedling:23:in `load'
/usr/local/bin/ceedling:23:in `<main>'
Tasks: TOP => build/test/results/test_add.pass
(See full trace by running task with --trace)

--------------------
OVERALL TEST SUMMARY
--------------------

No tests executed.
```

If I produce a test case with only failed or ignored tests ceedling runs smoothly.

```
Test 'test_add.c'
-----------------
> Shell executed command:
'gcc -E -MM -MG -I"/var/lib/gems/2.7.0/gems/ceedling-0.31.1/vendor/unity/src" -I"/var/lib/gems/2.7.0/gems/ceedling-0.31.1/vendor/cmock/src" -I"build/test/mocks" -I"test" -I"test/support" -I"../test/src" -I"../test/include" -DTEST -DTEST -DGNU_COMPILER "build/temp/_test_add.c"'
> Produced output:
_test_add.o: build/temp/_test_add.c \
 /var/lib/gems/2.7.0/gems/ceedling-0.31.1/vendor/unity/src/unity.h \
 /var/lib/gems/2.7.0/gems/ceedling-0.31.1/vendor/unity/src/unity_internals.h \
 @@@@unity.h ../test/include/add.h @@@@add.h

> Shell executed command:
'gcc -E -I"/var/lib/gems/2.7.0/gems/ceedling-0.31.1/vendor/unity/src" -I"/var/lib/gems/2.7.0/gems/ceedling-0.31.1/vendor/cmock/src" -I"build/test/mocks" -I"test" -I"test/support" -I"../test/src" -I"../test/include" -DTEST -DTEST -DGNU_COMPILER "test/test_add.c" -o "build/test/preprocess/files/test_add.c"'

Generating runner for test_add.c...
Compiling test_add_runner.c...
> Shell executed command:
'sparc-gaisler-elf-gcc -qbsp=leon3 -mcpu=leon3 -O0 -I"/var/lib/gems/2.7.0/gems/ceedling-0.31.1/vendor/unity/src" -I"/var/lib/gems/2.7.0/gems/ceedling-0.31.1/vendor/cmock/src" -I"build/test/mocks" -I"test" -I"test/support" -I"../test/src" -I"../test/include" -c -o "build/test/out/c/test_add_runner.o" "build/test/runners/test_add_runner.c"'

Compiling test_add.c...
> Shell executed command:
'sparc-gaisler-elf-gcc -qbsp=leon3 -mcpu=leon3 -O0 -I"/var/lib/gems/2.7.0/gems/ceedling-0.31.1/vendor/unity/src" -I"/var/lib/gems/2.7.0/gems/ceedling-0.31.1/vendor/cmock/src" -I"build/test/mocks" -I"test" -I"test/support" -I"../test/src" -I"../test/include" -c -o "build/test/out/c/test_add.o" "test/test_add.c"'

Linking test_add.elf...
> Shell executed command:
'sparc-gaisler-elf-gcc -qbsp=leon3 -mcpu=leon3 -o "build/test/out/test_add.elf" "build/test/out/c/test_add_runner.o" "build/test/out/c/test_add.o" "build/test/out/c/unity.o" "build/test/out/c/add.o" "build/test/out/c/cmock.o"'

Running test_add.elf...
> Shell executed command:
'sparc-rtems6-sis -leon3 -c test/support/run_cmd "build/test/out/test_add.elf" &'
> Produced output:
SIS - SPARC/RISCV instruction simulator 2.29,  copyright Jiri Gaisler 2020
 Bug-reports to jiri@gaisler.se

 LEON3 emulation enabled, 1 cpus online, delta 50 clocks

 Loaded build/test/out/test_add.elf, entry 0x40000000
sis> run
test_add.c:34:test_add_three:FAIL: Expected 0 Was 3
test_add.c:39:test_add_four:IGNORE: Skipped test

-----------------------
2 Tests 1 Failures 1 Ignored
FAIL


-----------
TEST OUTPUT
-----------
[test_add.c]
  - ""
  - " SIS - SPARC/RISCV instruction simulator 2.29,  copyright Jiri Gaisler 2020"
  - " Bug-reports to jiri@gaisler.se"
  - ""
  - " LEON3 emulation enabled, 1 cpus online, delta 50 clocks"
  - ""
  - " Loaded build/test/out/test_add.elf, entry 0x40000000"
  - "sis> run"
  - ""

--------------------
IGNORED TEST SUMMARY
--------------------
[test_add.c]
  Test: test_add_four
  At line (39): "Skipped test"

-------------------
FAILED TEST SUMMARY
-------------------
[test_add.c]
  Test: test_add_three
  At line (34): "Expected 0 Was 3"

--------------------
OVERALL TEST SUMMARY
--------------------
TESTED:  2
PASSED:  0
FAILED:  1
IGNORED: 1

---------------------
BUILD FAILURE SUMMARY
---------------------
Unit test failures.
```

**Comment by lcavalli** [comment]
The problem comes from the regular expression used to parse unity output:

```ruby
    output_string.lines do |line|
      # process unity output
      case line
      when /(:IGNORE)/
        elements = extract_line_elements(line, results[:source][:file])
        results[:ignores] << elements[0]
        results[:stdout] << elements[1] if (!elements[1].nil?)
      when /(:PASS$)/
        elements = extract_line_elements(line, results[:source][:file])
        results[:successes] << elements[0]
        results[:stdout] << elements[1] if (!elements[1].nil?)
      when /(:PASS \(.* ms\)$)/
        elements = extract_line_elements(line, results[:source][:file])
        results[:successes] << elements[0]
        results[:stdout] << elements[1] if (!elements[1].nil?)
      when /(:FAIL)/
        elements = extract_line_elements(line, results[:source][:file])
        results[:failures] << elements[0]
        results[:stdout] << elements[1] if (!elements[1].nil?)
      else # collect up all other
        results[:stdout] << line.chomp
      end
    end
```

Removing the two $ from the PASS cases produces the correct test execution.
The lines seems to be printed with \r\n terminators. Is there any configuration option that can be used to obtain the correct parsing?

Thanks.

**Comment by lcavalli** [comment]
Not sure this may be a problem or not, but although the EOL in generally \n, it seems that the EOL of the parsed execution output is \r\n:

![image](https://user-images.githubusercontent.com/6123641/186680478-a2af3538-d834-43ed-ae7e-e5ef0a5f9d80.png)

```

test_add.c:27:test_add_one:PASS
test_add.c:35:test_add_two:PASS
test_add.c:48:test_add_three:FAIL: Expected 0 Was 3
test_add.c:53:test_add_four:IGNORE: Skipped test

-----------------------
4 Tests 1 Failures 1 Ignored 
FAIL
```

**Comment by lcavalli** [comment]
PR #698 has been merged. Closing the issue.

**Comment by laurensmiers** [comment]
Not trying to necro-bump, but for anyone coming across this and wondering how to disable it:
I got it working (meaning disabled) by specifying a variable inside a rakefile.rb which calls ceedling:
```
require "ceedling"

# Disable ceedling test run sanity check
CEEDLING_IGNORE_SANITY_CHECK = 1

Ceedling.load_project
```
it seems ceedling is checking an actual variable, not an environment variable to disable the sanity check?
