### ISSUE TITLE
Ceedling unit tests will not execute on windows

### ISSUE THREAD

**Issue by ajpenner** [ThrowTheSwitch/Ceedling#798]
We I follow the instructions in the README to run the unit tests they abort with 'please try gem install win32api' which I do try and the gem fails to install. I would have expected this to be installed as part of bundle installer, but if there is a dependency on a gem that no longer exists there may be a larger issue at hand

**Comment by mvandervoord** [comment]
Hi. We're working on the next release which resolves this (and a number of other bugs). You can see that gem in the releases folder. At the moment, you'd have to download the gem and install it manually... but it will be fixing the issues mentioned.

**Comment by ajpenner** [comment]
Looking forward to the new release!

When I install win32api, I now get the following errors:

`PS C:\dev\GitRepos\Ceedling> bundle exec rake
C:/ruby30-x64/bin/ruby.exe -I'C:/ruby30-x64/lib/ruby/gems/3.0.0/gems/rspec-core-3.8.0/lib';'C:/ruby30-x64/lib/ruby/gems/
3.0.0/gems/rspec-support-3.8.0/lib' 'C:/ruby30-x64/lib/ruby/gems/3.0.0/gems/rspec-core-3.8.0/exe/rspec' --pattern 'spec/
**/*_spec.rb'
..............******.*......F.....................F............................................FF.......................
........................................................................................................................
............*

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) ConfiguratorBuilder is scary
     # Temporarily skipped with xit
     # ./spec/configurator_builder_spec.rb:6

  2) ConfiguratorHelper doesn't exist...
     # Temporarily skipped with xit
     # ./spec/configurator_helper_spec.rb:4

  3) Configurator#standardize_paths should standardize [:project][:build_root]
     # Temporarily skipped with xit
     # ./spec/configurator_spec.rb:5

  4) Configurator#standardize_paths should standardize [:paths]
     # Temporarily skipped with xit
     # ./spec/configurator_spec.rb:6

  5) Configurator#standardize_paths should standardize [:files]
     # Temporarily skipped with xit
     # ./spec/configurator_spec.rb:7

  6) Configurator#standardize_paths should standardize [:tools]
     # Temporarily skipped with xit
     # ./spec/configurator_spec.rb:8

  7) FileFinderHelper#find_file_in_collection handles duplicate files
     # Temporarily skipped with xit
     # ./spec/file_finder_helper_spec.rb:26

  8) uncategorized set_verbosity needs to be defined
     # Temporarily skipped with xit
     # ./spec/uncatagorized_specs_spec.rb:6


Failures:

  1) Ceedling Gcov basic operations should match 255
     Failure/Error: expect($?.exitstatus).to match(255) # Since a test fails, we return error here
       expected nil to match 255
     # ./spec/gcov/gcov_test_cases_spec.rb:100:in `block (2 levels) in can_test_projects_with_gcov_with_fail_because_of_
uncovered_files'
     # ./spec/gcov/gcov_test_cases_spec.rb:91:in `chdir'
     # ./spec/gcov/gcov_test_cases_spec.rb:91:in `block in can_test_projects_with_gcov_with_fail_because_of_uncovered_fi
les'
     # ./spec/spec_system_helper.rb:108:in `block (2 levels) in with_context'
     # ./spec/spec_system_helper.rb:141:in `with_constrained_env'
     # ./spec/spec_system_helper.rb:104:in `block in with_context'
     # ./spec/spec_system_helper.rb:103:in `chdir'
     # ./spec/spec_system_helper.rb:103:in `with_context'
     # ./spec/gcov/gcov_test_cases_spec.rb:90:in `can_test_projects_with_gcov_with_fail_because_of_uncovered_files'
     # ./spec/gcov/gcov_deployment_spec.rb:29:in `block (4 levels) in <top (required)>'

  2) GeneratorTestResults#process_and_write_results handles a mangled test output as gracefully as it can
     Failure/Error: expect(IO.read(TEST_OUT_FILE)).to eq(IO.read('spec/support/test_example_mangled.pass'))

       expected: "---\n:source:\n  :file: some/place/test_example.c\n  :dirname: some/place\n  :basename: test_example..
.red: 0\n:stdout:\n- Verbose output one\n- test_example.c:269:test_tVerbous output two\n:time: 0.0\n"
            got: "---\n:source:\n  :file: some/place/test_example.c\n  :dirname: some/place\n  :basename: test_example..
.red: 0\n:stdout:\n- Verbose output one\n- test_example.c:269:test_tVerbous output two\n:time: 0.0\n"

       (compared using ==)

       Diff:
       @@ -8,7 +8,7 @@
          :line: 257
          :message: ''
          :unity_test_time: 0
       --
       +-
        :failures: []
        :ignores: []
        :counts:

     # ./spec/generator_test_results_spec.rb:103:in `block (3 levels) in <top (required)>'

  3) Ceedling deployed in a project's `vendor` directory. should match /Segmentation fault \(core dumped\)/
     Failure/Error: expect(output).to match(/Segmentation fault \(core dumped\)/)

       expected "NOTICE: \nThe option[s]:  \ncannot be applied.To enable it, please add `:cmdline_args` under :test_r...
race)\n\n--------------------\nOVERALL TEST SUMMARY\n--------------------\n\nNo tests executed.\n\n" to match /Segmentat
ion fault \(core dumped\)/
       Diff:
       @@ -1,2 +1,44 @@
       -/Segmentation fault \(core dumped\)/
       +NOTICE:
       +The option[s]:
       +cannot be applied.To enable it, please add `:cmdline_args` under :test_runner option in your project.yml.
       +
       +
       +Test 'test/test_example_file_sigsegv.c'
       +---------------------------------------
       +Generating runner for test_example_file_sigsegv.c...
       +Compiling test_example_file_sigsegv_runner.c...
       +Compiling test_example_file_sigsegv.c...
       +Compiling unity.c...
       +Compiling example_file.c...
       +Compiling cmock.c...
       +Linking test_example_file_sigsegv.out...
       +Running test_example_file_sigsegv.out...
       +
       +ERROR: Test executable "test_example_file_sigsegv.out" failed.
       +> Produced no final test result counts in $stdout:
       +test_example_file_sigsegv.c:9:test_add_numbers_adds_numbers:PASS
       +> And exited with status: [0] (count of failed tests).
       +> This is often a symptom of a bad memory access in source or test code.
       +
       +rake aborted!
       +
       +C:/Users/ADMINI~1/AppData/Local/Temp/2/d20230731-6660-wjrz6t/fake_project/vendor/ceedling/lib/ceedling/generator
_helper.rb:36:in `test_results_error_handler'
       +C:/Users/ADMINI~1/AppData/Local/Temp/2/d20230731-6660-wjrz6t/fake_project/vendor/ceedling/lib/ceedling/generator
.rb:188:in `generate_test_results'
       +C:/Users/ADMINI~1/AppData/Local/Temp/2/d20230731-6660-wjrz6t/fake_project/vendor/ceedling/lib/ceedling/rules_tes
ts.rake:55:in `block in <top (required)>'
       +C:/Users/ADMINI~1/AppData/Local/Temp/2/d20230731-6660-wjrz6t/fake_project/vendor/ceedling/lib/ceedling/task_invo
ker.rb:107:in `invoke_test_results'
       +C:/Users/ADMINI~1/AppData/Local/Temp/2/d20230731-6660-wjrz6t/fake_project/vendor/ceedling/lib/ceedling/test_invo
ker.rb:125:in `block in setup_and_invoke'
       +C:/Users/ADMINI~1/AppData/Local/Temp/2/d20230731-6660-wjrz6t/fake_project/vendor/ceedling/lib/ceedling/test_invo
ker.rb:51:in `setup_and_invoke'
       +C:/Users/ADMINI~1/AppData/Local/Temp/2/d20230731-6660-wjrz6t/fake_project/vendor/ceedling/lib/ceedling/tasks_tes
ts.rake:13:in `block (2 levels) in <top (required)>'
       +C:/dev/GitRepos/Ceedling/bin/ceedling:359:in `block in <top (required)>'
       +C:/dev/GitRepos/Ceedling/bin/ceedling:346:in `<top (required)>'
       +C:/Users/ADMINI~1/AppData/Local/Temp/2/d20230731-6660-wjrz6t/gems/ruby/3.0.0/bin/ceedling:25:in `load'
       +C:/Users/ADMINI~1/AppData/Local/Temp/2/d20230731-6660-wjrz6t/gems/ruby/3.0.0/bin/ceedling:25:in `<main>'
       +Tasks: TOP => build/test/results/test_example_file_sigsegv.pass
       +(See full trace by running task with --trace)
       +
       +--------------------
       +OVERALL TEST SUMMARY
       +--------------------
       +
       +No tests executed.

     # ./spec/spec_system_helper.rb:842:in `block (2 levels) in test_run_of_projects_fail_because_of_sigsegv_without_rep
ort'
     # ./spec/spec_system_helper.rb:835:in `chdir'
     # ./spec/spec_system_helper.rb:835:in `block in test_run_of_projects_fail_because_of_sigsegv_without_report'
     # ./spec/spec_system_helper.rb:108:in `block (2 levels) in with_context'
     # ./spec/spec_system_helper.rb:141:in `with_constrained_env'
     # ./spec/spec_system_helper.rb:104:in `block in with_context'
     # ./spec/spec_system_helper.rb:103:in `chdir'
     # ./spec/spec_system_helper.rb:103:in `with_context'
     # ./spec/spec_system_helper.rb:834:in `test_run_of_projects_fail_because_of_sigsegv_without_report'
     # ./spec/system/deployment_spec.rb:51:in `block (3 levels) in <top (required)>'

  4) Ceedling deployed in a project's `vendor` directory. should match /Program received signal SIGSEGV, Segmentation fa
ult./
     Failure/Error: expect(output).to match(/Program received signal SIGSEGV, Segmentation fault./)

       expected "NOTICE: \nThe option[s]:  \ncannot be applied.To enable it, please add `:cmdline_args` under :test_r...
race)\n\n--------------------\nOVERALL TEST SUMMARY\n--------------------\n\nNo tests executed.\n\n" to match /Program r
eceived signal SIGSEGV, Segmentation fault./
       Diff:
       @@ -1,2 +1,44 @@
       -/Program received signal SIGSEGV, Segmentation fault./
       +NOTICE:
       +The option[s]:
       +cannot be applied.To enable it, please add `:cmdline_args` under :test_runner option in your project.yml.
       +
       +
       +Test 'test/test_example_file_sigsegv.c'
       +---------------------------------------
       +Generating runner for test_example_file_sigsegv.c...
       +Compiling test_example_file_sigsegv_runner.c...
       +Compiling test_example_file_sigsegv.c...
       +Compiling unity.c...
       +Compiling example_file.c...
       +Compiling cmock.c...
       +Linking test_example_file_sigsegv.out...
       +Running test_example_file_sigsegv.out...
       +
       +ERROR: Test executable "test_example_file_sigsegv.out" failed.
       +> Produced no final test result counts in $stdout:
       +test_example_file_sigsegv.c:9:test_add_numbers_adds_numbers:PASS
       +> And exited with status: [0] (count of failed tests).
       +> This is often a symptom of a bad memory access in source or test code.
       +
       +rake aborted!
       +
       +C:/Users/ADMINI~1/AppData/Local/Temp/2/d20230731-6660-wjrz6t/fake_project/vendor/ceedling/lib/ceedling/generator
_helper.rb:36:in `test_results_error_handler'
       +C:/Users/ADMINI~1/AppData/Local/Temp/2/d20230731-6660-wjrz6t/fake_project/vendor/ceedling/lib/ceedling/generator
.rb:188:in `generate_test_results'
       +C:/Users/ADMINI~1/AppData/Local/Temp/2/d20230731-6660-wjrz6t/fake_project/vendor/ceedling/lib/ceedling/rules_tes
ts.rake:55:in `block in <top (required)>'
       +C:/Users/ADMINI~1/AppData/Local/Temp/2/d20230731-6660-wjrz6t/fake_project/vendor/ceedling/lib/ceedling/task_invo
ker.rb:107:in `invoke_test_results'
       +C:/Users/ADMINI~1/AppData/Local/Temp/2/d20230731-6660-wjrz6t/fake_project/vendor/ceedling/lib/ceedling/test_invo
ker.rb:125:in `block in setup_and_invoke'
       +C:/Users/ADMINI~1/AppData/Local/Temp/2/d20230731-6660-wjrz6t/fake_project/vendor/ceedling/lib/ceedling/test_invo
ker.rb:51:in `setup_and_invoke'
       +C:/Users/ADMINI~1/AppData/Local/Temp/2/d20230731-6660-wjrz6t/fake_project/vendor/ceedling/lib/ceedling/tasks_tes
ts.rake:13:in `block (2 levels) in <top (required)>'
       +C:/dev/GitRepos/Ceedling/bin/ceedling:359:in `block in <top (required)>'
       +C:/dev/GitRepos/Ceedling/bin/ceedling:346:in `<top (required)>'
       +C:/Users/ADMINI~1/AppData/Local/Temp/2/d20230731-6660-wjrz6t/gems/ruby/3.0.0/bin/ceedling:25:in `load'
       +C:/Users/ADMINI~1/AppData/Local/Temp/2/d20230731-6660-wjrz6t/gems/ruby/3.0.0/bin/ceedling:25:in `<main>'
       +Tasks: TOP => build/test/results/test_example_file_sigsegv.pass
       +(See full trace by running task with --trace)
       +
       +--------------------
       +OVERALL TEST SUMMARY
       +--------------------
       +
       +No tests executed.

     # ./spec/spec_system_helper.rb:875:in `block (2 levels) in test_run_of_projects_fail_because_of_sigsegv_with_report
'
     # ./spec/spec_system_helper.rb:851:in `chdir'
     # ./spec/spec_system_helper.rb:851:in `block in test_run_of_projects_fail_because_of_sigsegv_with_report'
     # ./spec/spec_system_helper.rb:108:in `block (2 levels) in with_context'
     # ./spec/spec_system_helper.rb:141:in `with_constrained_env'
     # ./spec/spec_system_helper.rb:104:in `block in with_context'
     # ./spec/spec_system_helper.rb:103:in `chdir'
     # ./spec/spec_system_helper.rb:103:in `with_context'
     # ./spec/spec_system_helper.rb:850:in `test_run_of_projects_fail_because_of_sigsegv_with_report'
     # ./spec/system/deployment_spec.rb:52:in `block (3 levels) in <top (required)>'

Finished in 12 minutes 7 seconds (files took 0.47357 seconds to load)
253 examples, 4 failures, 8 pending

Failed examples:

rspec ./spec/gcov/gcov_deployment_spec.rb:29 # Ceedling Gcov basic operations should match 255
rspec ./spec/generator_test_results_spec.rb:101 # GeneratorTestResults#process_and_write_results handles a mangled test
output as gracefully as it can
rspec ./spec/system/deployment_spec.rb:51 # Ceedling deployed in a project's `vendor` directory. should match /Segmentat
ion fault \(core dumped\)/
rspec ./spec/system/deployment_spec.rb:52 # Ceedling deployed in a project's `vendor` directory. should match /Program r
eceived signal SIGSEGV, Segmentation fault./

C:/ruby30-x64/bin/ruby.exe -I'C:/ruby30-x64/lib/ruby/gems/3.0.0/gems/rspec-core-3.8.0/lib';'C:/ruby30-x64/lib/ruby/gems/
3.0.0/gems/rspec-support-3.8.0/lib' 'C:/ruby30-x64/lib/ruby/gems/3.0.0/gems/rspec-core-3.8.0/exe/rspec' --pattern 'spec/
**/*_spec.rb' failed
PS C:\dev\GitRepos\Ceedling>`
