### ISSUE TITLE
TypeError: no implicit conversion of String into Array

### ISSUE THREAD

**Issue by kafkaaaa** [ThrowTheSwitch/Ceedling#827]
# TypeError: no implicit conversion of String into Array

Hello I would like to introduce my C legacy project Unit Testing and i want to use Ceedling.
But there were some problems and the test code failed to execute.
I'm trying base64 encoding test.

- - -
and my project structure is...
├── build
│   ├── (skip)
├── project.yml
├── src
│   └── b64_encode.c
└── test
　　├── support
　　│   └── .gitkeep
　　└── test_b64_encode.c

- - -
`output`
```
stdout:


Test 'test_b64_encode.c'
------------------------

--------------------
OVERALL TEST SUMMARY
--------------------

No tests executed.


stderr:
rake aborted!
TypeError: no implicit conversion of String into Array
/var/lib/gems/3.0.0/gems/ceedling-0.31.1/lib/ceedling/test_invoker.rb:30:in `+'
/var/lib/gems/3.0.0/gems/ceedling-0.31.1/lib/ceedling/test_invoker.rb:30:in `convert_libraries_to_arguments'
/var/lib/gems/3.0.0/gems/ceedling-0.31.1/lib/ceedling/rules_tests.rake:37:in `block in <top (required)>'
/var/lib/gems/3.0.0/gems/ceedling-0.31.1/lib/ceedling/task_invoker.rb:107:in `invoke_test_results'
/var/lib/gems/3.0.0/gems/ceedling-0.31.1/lib/ceedling/test_invoker.rb:125:in `block in setup_and_invoke'
/var/lib/gems/3.0.0/gems/ceedling-0.31.1/lib/ceedling/test_invoker.rb:51:in `each'
/var/lib/gems/3.0.0/gems/ceedling-0.31.1/lib/ceedling/test_invoker.rb:51:in `setup_and_invoke'
/var/lib/gems/3.0.0/gems/ceedling-0.31.1/lib/ceedling/rules_tests.rake:70:in `block (2 levels) in <top (required)>'
/var/lib/gems/3.0.0/gems/ceedling-0.31.1/bin/ceedling:345:in `block in <top (required)>'
/var/lib/gems/3.0.0/gems/ceedling-0.31.1/bin/ceedling:332:in `<top (required)>'
/usr/local/bin/ceedling:25:in `load'
/usr/local/bin/ceedling:25:in `<main>'
Tasks: TOP => build/test/results/test_b64_encode.pass => build/test/out/test_b64_encode.out
(See full trace by running task with --trace)
```
- - -
`$ ceedling version`
```
   Ceedling:: 0.31.1
      Unity:: 2.5.4
      CMock:: 2.5.4
 CException:: 1.3.3
```
Ubuntu 22.04.3
VSCode Extension: Ceedling Test Explorer
- - -
`project.yml`
```
# Notes:
# Sample project C code is not presently written to produce a release artifact.
# As such, release build options are disabled.
# This sample, therefore, only demonstrates running a collection of unit tests.

:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: TRUE
  :use_auxiliary_dependencies: TRUE
  :build_root: build
#  :release_build: TRUE
  :test_file_prefix: test_
  :which_ceedling: gem
  :ceedling_version: 0.31.1
  :default_tasks:
    - test:all

#:test_build:
#  :use_assembly: TRUE

#:release_build:
#  :output: MyApp.out
#  :use_assembly: FALSE

:environment:

:extension:
  :executable: .out

:paths:
  :test:
    - +:test/**
    - -:test/support
  :source:
    - src/**
  :support:
    - test/support
  :libraries: []

:defines:
  # in order to add common defines:
  #  1) remove the trailing [] from the :common: section
  #  2) add entries to the :common: section (e.g. :test: has TEST defined)
  :common: &common_defines []
  :test:
    - *common_defines
    - TEST
  :test_preprocess:
    - *common_defines
    - TEST

:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :plugins:
    - :ignore
    - :callback
  :treat_as:
    uint8:    HEX8
    uint16:   HEX16
    uint32:   UINT32
    int8:     INT8
    bool:     UINT8

# Add -gcov to the plugins list to make sure of the gcov plugin
# You will need to have gcov and gcovr both installed to make it work.
# For more information on these options, see docs in plugins/gcov
:gcov:
  :reports:
    - HtmlDetailed
  :gcovr:
    :html_medium_threshold: 75
    :html_high_threshold: 90

#:tools:
# Ceedling defaults to using gcc for compiling, linking, etc.
# As [:tools] is blank, gcc will be used (so long as it's in your system path)
# See documentation to configure a given toolchain for use

# LIBRARIES
# These libraries are automatically injected into the build process. Those specified as
# common will be used in all types of builds. Otherwise, libraries can be injected in just
# tests or releases. These options are MERGED with the options in supplemental yaml files.
:libraries:
  :placement: :end
  :flag: "-l${1}"
  :path_flag: "-L ${1}"
  :system: "-m"    # for example, you might list 'm' to grab the math library
  :test: []
  :release: []

:plugins:
  :load_paths:
    - "#{Ceedling.load_path}"
  :enabled:
    - stdout_pretty_tests_report
    - module_generator
    - xml_tests_report
...
```

**Comment by mvandervoord** [comment]
Update your libraries section to look like this:

```:libraries:
  :placement: :end
  :flag: "-l${1}"
  :path_flag: "-L ${1}"
  :system: 
    - m    # note the space between the dash and the 'm'. also note the indent.
  :test: []
  :release: []
```

I suspect what is happening is that the library system library list is supposed to be an array and you've given it a string.

**Comment by kafkaaaa** [comment]
Oh, that is my mistake. Thank you for your reply. 😊

Could I post it here if I have any questions while doing another test? Or could you give me another link?

**Comment by mvandervoord** [comment]
@kafkaaaa -- you're welcome to ask further question as new issues. :)
