### ISSUE TITLE
Executing Ceedling in a previously initialized project directory fails after switching the user account

### ISSUE THREAD

**Issue by kozmotronik** [ThrowTheSwitch/Ceedling#869]
When I execute Ceedling inside the project folder gives me the following error:
```
$ ceedling
NoMethodError ==> undefined method `load_path' for module Ceedling
(eval at /usr/lib64/ruby/gems/3.3.0/gems/ceedling-0.32.0/lib/ceedling/system_wrapper.rb:28):1:in `module_eval': undefined method `load_path' for module Ceedling (NoMethodError)
Did you mean?  load_project
        from /usr/lib64/ruby/gems/3.3.0/gems/ceedling-0.32.0/lib/ceedling/system_wrapper.rb:28:in `module_eval'
        from /usr/lib64/ruby/gems/3.3.0/gems/ceedling-0.32.0/lib/ceedling/system_wrapper.rb:28:in `module_eval'
        from /usr/lib64/ruby/gems/3.3.0/gems/ceedling-0.32.0/lib/ceedling/configurator.rb:494:in `block in eval_path_entries'
        from /usr/lib64/ruby/gems/3.3.0/gems/ceedling-0.32.0/lib/ceedling/configurator.rb:493:in `each'
        from /usr/lib64/ruby/gems/3.3.0/gems/ceedling-0.32.0/lib/ceedling/configurator.rb:493:in `eval_path_entries'
        from /usr/lib64/ruby/gems/3.3.0/gems/ceedling-0.32.0/lib/ceedling/configurator.rb:336:in `block in eval_paths'
        from /usr/lib64/ruby/gems/3.3.0/gems/ceedling-0.32.0/lib/ceedling/configurator.rb:336:in `each_pair'
        from /usr/lib64/ruby/gems/3.3.0/gems/ceedling-0.32.0/lib/ceedling/configurator.rb:336:in `eval_paths'
        from /usr/lib64/ruby/gems/3.3.0/gems/ceedling-0.32.0/lib/ceedling/setupinator.rb:37:in `do_setup'
        from /usr/lib64/ruby/gems/3.3.0/gems/ceedling-0.32.0/lib/ceedling/rakefile.rb:76:in `<top (required)>'
        from /usr/lib64/ruby/gems/3.3.0/gems/ceedling-0.32.0/lib/ceedling.rb:67:in `load'
        from /usr/lib64/ruby/gems/3.3.0/gems/ceedling-0.32.0/lib/ceedling.rb:67:in `load_project'
        from /usr/lib64/ruby/gems/3.3.0/gems/ceedling-0.32.0/bin/ceedling:380:in `<main>'

```
But if I execute ceedling one step out of the project directory it works normal:
```
$ ceedling
Welcome to Ceedling!
Commands:
  ceedling example PROJ_NAME [DEST]  # new specified example project (in DEST, if specified)
  ceedling examples                  # list available example projects
  ceedling help [COMMAND]            # Describe available commands or one specific command
  ceedling new PROJECT_NAME          # create a new ceedling project
  ceedling upgrade PROJECT_NAME      # upgrade ceedling for a project (not req'd if gem used)
  ceedling version                   # return the version of the tools installed

```
Here is the directory of the project that I've initiated with ceedling before.
```
hkbmv2
├── belgelendirme
│   ├── Doxyfile
│   └── hkbmv2_doc.dox
├── build
├── project.yml
├── release.yml
├── src
│   ├── donanim
│   │   ├── devcfg.c
│   │   ├── devcfg.h
│   │   ├── eusart1.c
│   │   ├── eusart1.h
│   │   ├── eusart2.c
│   │   ├── eusart2.h
│   │   ├── interrupt.c
│   │   ├── interrupt.h
│   │   ├── memory.c
│   │   ├── memory.h
│   │   ├── osilator.c
│   │   ├── osilator.h
│   │   ├── pin.c
│   │   ├── pin.h
│   │   ├── sistimer.c
│   │   └── sistimer.h
│   ├── gorevci
│   │   ├── gorev.c
│   │   ├── include
│   │   │   ├── bayrak.h
│   │   │   ├── gorev.h
│   │   │   ├── sn.h
│   │   │   └── uckuyruk.h
│   │   ├── LICENSE
│   │   ├── LISANS_tr.md
│   │   ├── portlar
│   │   │   └── mplabx
│   │   │       └── xc8
│   │   │           └── pic18
│   │   │               ├── port.c
│   │   │               ├── port.h
│   │   │               └── portmacro.h
│   │   ├── README.md
│   │   └── uckuyruk.c
│   ├── gorevciypl.h
│   ├── hkbmv2.c
│   ├── hkbmv2.h
│   └── uygulama
│       ├── araclar.c
│       ├── araclar.h
│       ├── atio.c
│       ├── atio.h
│       ├── btio.c
│       ├── btio.h
│       ├── duduk.c
│       ├── duduk.h
│       ├── eepromio.c
│       ├── eepromio.h
│       ├── eylem.c
│       ├── eylem.h
│       ├── gosterge.c
│       ├── gosterge.h
│       ├── kanallar.c
│       ├── kanallar.h
│       ├── kayit.c
│       ├── kayit.h
│       ├── kontrol.c
│       ├── kontrol.h
│       ├── tilt.c
│       ├── tilt.h
│       ├── tus.c
│       ├── tus.h
│       ├── yetki.c
│       └── yetki.h
└── test
    ├── include
    │   ├── mcu_yazmaclar.h
    │   ├── sht_eeprom.h
    │   ├── xc.h
    │   └── yerellestirme.h
    ├── sht_eeprom.c
    ├── support
    ├── test_hkbmv2.c
    └── uygulama
        ├── test_araclar.c
        ├── test_atio.c
        ├── test_btio.c
        ├── test_duduk.c
        ├── test_eepromio.c
        ├── test_eylem.c
        ├── test_gosterge.c
        ├── test_kanallar.c
        ├── test_kayit.c
        ├── test_kontrol.c
        ├── test_tilt.c
        ├── test_tus.c
        └── test_yetki.c

```
This started to happen when I had to switch the user account on the same Linux workstation. It was working in the old account. What would be the reason behind this?
Here is some version information on ruby and Ceedling:
```bash
$ ruby --version
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-linux-gnu]

$ ceedling version
Welcome to Ceedling!
    Ceedling:: 0.32.0
       CMock:: 2.5.4
       Unity:: 2.5.4
  CException:: 1.3.3
```
I installed this prerelease version of ceedling: https://github.com/ThrowTheSwitch/Ceedling/releases/tag/0.32.0-9b8d8a9

## Finally Got It Working...
After some failed trials, I decided to execute `ceedling new project` command on the same -already initialized- project directory. The command replaced the project.yml with new one. Then I tried executing ceedling commands in the project directory and this time it worked.
Here I leave the old project.yml file content so that it helps for further diagnostic:
```yaml
---

# Notes:
# Sample project C code is not presently written to produce a release artifact.
# As such, release build options are disabled.
# This sample, therefore, only demonstrates running a collection of unit tests.

:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: TRUE
  :use_auxiliary_dependencies: TRUE
  :build_root: build
  :release_build: TRUE
  :test_file_prefix: test_
  :which_ceedling: gem
  :ceedling_version: 0.32.0
  :test_threads: :auto
  :compile_threads: :auto
  :default_tasks:
    - test:all

#:test_build:
#  :use_assembly: TRUE

:release_build:
 :output: hkbmv2.out
 :use_assembly: FALSE

:environment:
  - :prjname: hkbmv2
  - :mcu: 18F46K22
  - :mplabx_root: "/opt/microchip/mplabx/v6.15"
  - :path:
    - "/opt/microchip/xc8/v2.46/bin"
    - "#{ENV['PATH']}"
    - build

:extension:
  :object: .o
  :executable: .out
  :assembly: .s

:paths:
  :test:
    - +:test/**
    - -:test/support
  :source:
    - src/**
  :support:
    - test/support
  :libraries: []
  :include:
    - src
    - src/donanim
    - src/uygulama
    - src/gorevci/include
    - src/gorevci/portlar/mplabx/xc8/pic18

:defines:
  # in order to add common defines:
  #  1) remove the trailing [] from the :common: section
  #  2) add entries to the :common: section (e.g. :test: has TEST defined)
  :common: &common_defines
    [
       UNITY_SUPPORT_64,
       UNITY_INCLUDE_PRINT_FORMATTED,
       UNITY_INCLUDE_EXEC_TIME
    ]
  :test:
    - *common_defines
    - TEST
  :test_preprocess:
    - *common_defines
    - TEST_PP

:flags:
  :test:
    :compile:
      - -Wall
      - -O1
      - -DSTATIC=""

:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :plugins:
    - :ignore
    - :callback
    - :ignore_arg
    - :return_thru_ptr
  :treat_as:
    uint8:    HEX8
    uint16:   HEX16
    uint32:   UINT32
    int8:     INT8
    bool:     UINT8

# Add -gcov to the plugins list to make sure of the gcov plugin
# You will need to have gcov and gcovr both installed to make it work.
# For more information on these options, see docs in plugins/gcov
:gcov:
  :utilities:
    - gcovr
  :reports:
    - HtmlDetailed
  :gcovr:
    :html_medium_threshold: 75
    :html_high_threshold: 90
    :report_include: "^src.*"


# LIBRARIES
# These libraries are automatically injected into the build process. Those specified as
# common will be used in all types of builds. Otherwise, libraries can be injected in just
# tests or releases. These options are MERGED with the options in supplemental yaml files.
:libraries:
  :placement: :end
  :flag: "-l${1}"
  :path_flag: "-L ${1}"
  :system: []    # for example, you might list 'm' to grab the math library
  :test: []
  :release: []


#:tools:
# Ceedling defaults to using gcc for compiling, linking, etc.
# As [:tools] is blank, gcc will be used (so long as it's in your system path)
# See documentation to configure a given toolchain for use

:plugins:
  :load_paths:
    - "#{Ceedling.load_path}"
  :enabled:
    - stdout_pretty_tests_report
    - module_generator
    - gcov
...
```

**Comment by deltalejo** [comment]
It seems to me that the project was initially created with a previous version of Ceedling and now you are using 0.32 that is under development. One change that is relevant to your issue is the `load_paths` item inside `plugins` in your **project.yml**, on 0.32 `Ceedling.load_path` was removed, it is no longer needed so now you can simply omit it.
e.g.:

```yaml
:plugins:
  :enabled:
    - stdout_pretty_tests_report
    - module_generator
    - gcov
```

**Comment by kozmotronik** [comment]
> It seems to me that the project was initially created with a previous version of Ceedling...
Yes, you are right. I forgot to mention that.

>  One change that is relevant to your issue is the load_paths item inside plugins in your project.yml, on 0.32 Ceedling.load_path was removed, it is no longer needed so now you can simply omit it.

Interesting, I was using it with the earlier prerelease versions of ceedling 0.32 and it was working. Maybe they dropped it since the last several prerelease of 0.32. Thank you for the point @deltalejo.
