### ISSUE TITLE
Non-US-ASCII characters stop ceedling's rake in an unhelpful way

### ISSUE THREAD

**Issue by jnz86** [ThrowTheSwitch/Ceedling#888]
I copied a string from the browser, a made it into a C const, my tests stopped working. I commented out all changes, but that wasn't enough, a non-US-ASCII character existing in the file even as a comment was enough to stop tests from working.

Turns out, the curly apostrophe `’` is a killer. I found people complaining about this with Ruby, and Rake. The error that could be more helpful:

```
--------------------
OVERALL TEST SUMMARY
--------------------

No tests executed.


stderr:
rake aborted!
ArgumentError: invalid byte sequence in US-ASCII
/var/lib/gems/3.0.0/gems/ceedling-0.31.1/lib/ceedling/test_includes_extractor.rb:80:in `gsub'
/var/lib/gems/3.0.0/gems/ceedling-0.31.1/lib/ceedling/test_includes_extractor.rb:80:in `extract_source_include_from_file'
/var/lib/gems/3.0.0/gems/ceedling-0.31.1/lib/ceedling/test_includes_extractor.rb:24:in `parse_test_file_source_include'
...
```

While not a Ceedling "issue", there may be solutions. There are specified encodings and a "magic encoding' option for people using Ruby with other languages, among others I'm sure.

Even if not addressed in Ceedling, this is at least a head's up for anyone with the same issue.

**Comment by mvandervoord** [comment]
Fixed in 1.0.1

**Comment by mvandervoord** [comment]
Hi @twaldecker . I'm reopening this if you're still seeing it in 1.0.1. Can you run it with verbosity turned up so I can see which part of the code is reporting the issue? I'd like to make sure it's covered.

**Comment by twaldecker** [comment]
Thanks for your work! There you go:

```
bash-5.2# ceedling test:all --verbosity=debug
🚧 Loaded project configuration from working directory.
 > Using: /service/ceedling/project.yml
 > Working directory: /service/ceedling
 > Set which Ceedling from config :project ↳ :which_ceedling => gem
 > Launching Ceedling from /nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/

🚧 Application & Build Frameworks
   Ceedling => 1.0.1-fb1ce6c
      CMock => 2.6.0
      Unity => 2.6.1
 CException => 1.3.4

🚧 Validating configuration contains minimum required sections...

🚧 Base configuration handling...
Processing environment variables...

🚧 Plugin Handling
------------------
Discovering all plugins...
 > Rake plugins: module_generator, gcov
 > Programmatic plugins: module_generator, gcov, report_tests_log_factory, report_tests_pretty_stdout
 > Config plugins: module_generator, report_tests_pretty_stdout
Merging configuration from plugin module_generator...
{:module_generator=>{:naming=>:snake, :boilerplates=>{:src=>"", :inc=>"", :tst=>""}}}
Merging configuration from plugin report_tests_pretty_stdout...
{:plugins=>{:display_raw_test_results=>false}}

🚧 Assembling Default Settings
------------------------------
Collecting default tool configurations...
Collecting CMock defaults...
Collecting Plugin YAML defaults...
 - gcov >> {:gcov=>{:summaries=>true, :report_task=>false, :utilities=>["gcovr"], :reports=>[], :gcovr=>{:report_root=>".", :merge_mode_function=>"merge-use-line-max"}, :report_generator=>{:verbosity=>"Warning", :collection_paths_source=>[], :custom_args=>[], :gcov_exclude=>[]}}}
 - report_tests_log_factory >> {:report_tests_log_factory=>{:reports=>[]}}
Collecting Plugin Ruby hash defaults...
 - gcov >> {:tools=>{:gcov_compiler=>{:executable=>"gcc", :name=>"default_gcov_compiler", :optional=>false, :arguments=>["-g", "-fprofile-arcs", "-ftest-coverage", "-I\"${5}\"", "-D\"${6}\"", "-DGCOV_COMPILER", "-DCODE_COVERAGE", "-c \"${1}\"", "-o \"${2}\"", "-MMD", "-MF \"${4}\""]}, :gcov_linker=>{:executable=>"gcc", :name=>"default_gcov_linker", :optional=>false, :arguments=>["-g", "-fprofile-arcs", "-ftest-coverage", "${1}", "${5}", "-o \"${2}\"", "${4}"]}, :gcov_fixture=>{:executable=>"${1}", :name=>"default_gcov_fixture", :optional=>false, :arguments=>[]}, :gcov_summary=>{:executable=>"gcov", :name=>"default_gcov_summary", :optional=>true, :arguments=>["-n", "-p", "-b", "-o \"${2}\"", "\"${1}\""]}, :gcov_report=>{:executable=>"gcov", :name=>"default_gcov_report", :optional=>true, :arguments=>["-b", "-c", "-r", "-x", "${1}"]}, :gcov_gcovr_report=>{:executable=>"gcovr", :name=>"default_gcov_gcovr_report", :optional=>true, :arguments=>["${1}"]}, :gcov_reportgenerator_report=>{:executable=>"reportgenerator", :name=>"default_gcov_reportgenerator_report", :optional=>true, :arguments=>["${1}"]}}}
Populating project configuration with collected default values...

🚧 Completing Project Configuration
-----------------------------------
Processing Unity configuration...
Unity configuration >> {:defines=>["UNITY_EXCLUDE_FLOAT"], :vendor_path=>"/nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/vendor", :use_param_tests=>false}
CMock configuration >> {:plugins=>[:ignore, :callback], :verbosity=>2, :when_no_prototypes=>:warn, :skeleton_path=>"", :mock_prefix=>"mock_", :mock_suffix=>"", :strippables=>["(?:__attribute__\\s*\\([ (]*.*?[ )]*\\)+)"], :attributes=>["__ramfunc", "__irq", "__fiq", "register", "extern"], :c_calling_conventions=>["__stdcall", "__cdecl", "__fastcall"], :treat_externs=>:exclude, :treat_inlines=>:exclude, :treat_as=>{"uint8"=>"HEX8", "uint16"=>"HEX16", "uint32"=>"UINT32", "int8"=>"INT8", "bool"=>"UINT8"}, :memcmp_if_unknown=>true, :when_ptr=>:compare_data, :weak=>"", :enforce_strict_ordering=>true, :fail_on_unexpected_calls=>true, :callback_include_count=>true, :callback_after_arg_check=>false, :exclude_setjmp_h=>false, :vendor_path=>"/nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/vendor", :includes=>[], :defines=>[], :unity_helper_path=>[], :mock_path=>"build/test/mocks"}
Populating test runner generation settings...
Test Runner configuration >> {:cmdline_args=>true, :includes=>[], :defines=>["UNITY_EXCLUDE_FLOAT"], :file_suffix=>"_runner", :mock_prefix=>"mock_", :mock_suffix=>"", :enforce_strict_ordering=>true, :use_param_tests=>false}
CException configuration >> {:vendor_path=>"/nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/vendor", :defines=>[]}
Processing environment variables...
Processing path entries and expanding any string replacements...
Expanding any string replacements in :flags entries...
Expanding any string replacements in :defines entries...
Standardizing all paths...
Populating tool definition settings and expanding any string replacements...
Processing tool definition shortcuts...

🚧 Validating final project configuration...
Build paths:
 - build/artifacts
 - build/test
 - build/vendor
 - build/artifacts/test
 - build/test/runners
 - build/test/results
 - build/test/out
 - build/test/cache
 - build/test/dependencies
 - build/vendor/unity/src
 - build/logs

🚧 Loading Plugins
------------------
Adding plugin module_generator to Rake load list...
Adding plugin gcov to Rake load list...
Instantiating plugin class ModuleGenerator...
Instantiating plugin class Gcov...
Instantiating plugin class ReportTestsLogFactory...
Instantiating plugin class ReportTestsPrettyStdout...

Ceedling set up completed in 90 milliseconds

👟 Preparing Build Paths...

👟 Collecting Test Context
--------------------------
Parsing test_event.c for build directive macros, #includes, and test case names...
#<Thread:0x000074d337d1f450 /nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/lib/ceedling/build_batchinator.rb:54 run> terminated with exception (report_on_exception is true):
/nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/lib/ceedling/parsing_parcels.rb:21:in `match': invalid byte sequence in US-ASCII (ArgumentError)

        m = line.match /(.*)\\\s*$/
                       ^^^^^^^^^^^^
        from /nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/lib/ceedling/parsing_parcels.rb:21:in `match'
        from /nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/lib/ceedling/parsing_parcels.rb:21:in `block in code_lines'
        from /nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/lib/ceedling/parsing_parcels.rb:20:in `each_line'
        from /nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/lib/ceedling/parsing_parcels.rb:20:in `code_lines'
        from /nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/lib/ceedling/test_context_extractor.rb:56:in `collect_simple_context'
        from /nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/lib/ceedling/test_invoker.rb:108:in `block (3 levels) in setup_and_invoke'
        from /nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/lib/ceedling/file_wrapper.rb:92:in `block in open'
        from /nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/lib/ceedling/file_wrapper.rb:91:in `open'
        from /nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/lib/ceedling/file_wrapper.rb:91:in `open'
        from /nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/lib/ceedling/test_invoker.rb:107:in `block (2 levels) in setup_and_invoke'
        from /nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/lib/ceedling/build_batchinator.rb:61:in `block (5 levels) in exec'
        from <internal:kernel>:187:in `loop'
        from /nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/lib/ceedling/build_batchinator.rb:59:in `block (4 levels) in exec'
        from /nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/lib/ceedling/build_batchinator.rb:57:in `handle_interrupt'
        from /nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/lib/ceedling/build_batchinator.rb:57:in `block (3 levels) in exec'
        from /nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/lib/ceedling/build_batchinator.rb:55:in `handle_interrupt'
        from /nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/lib/ceedling/build_batchinator.rb:55:in `block (2 levels) in exec'
🧨 EXCEPTION: invalid byte sequence in US-ASCII

Debug Backtrace ==>
/nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/lib/ceedling/parsing_parcels.rb:21:in `match': (ArgumentError)
        /nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/lib/ceedling/parsing_parcels.rb:21:in `match'
        /nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/lib/ceedling/parsing_parcels.rb:21:in `block in code_lines'
        /nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/lib/ceedling/parsing_parcels.rb:20:in `each_line'
        /nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/lib/ceedling/parsing_parcels.rb:20:in `code_lines'
        /nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/lib/ceedling/test_context_extractor.rb:56:in `collect_simple_context'
        /nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/lib/ceedling/test_invoker.rb:108:in `block (3 levels) in setup_and_invoke'
        /nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/lib/ceedling/file_wrapper.rb:92:in `block in open'
        /nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/lib/ceedling/file_wrapper.rb:91:in `open'
        /nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/lib/ceedling/file_wrapper.rb:91:in `open'
        /nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/lib/ceedling/test_invoker.rb:107:in `block (2 levels) in setup_and_invoke'
        /nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/lib/ceedling/build_batchinator.rb:61:in `block (5 levels) in exec'
        <internal:kernel>:187:in `loop'
        /nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/lib/ceedling/build_batchinator.rb:59:in `block (4 levels) in exec'
        /nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/lib/ceedling/build_batchinator.rb:57:in `handle_interrupt'
        /nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/lib/ceedling/build_batchinator.rb:57:in `block (3 levels) in exec'
        /nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/lib/ceedling/build_batchinator.rb:55:in `handle_interrupt'
        /nix/store/y5pq1iib689dvgjipgl8ypcw5n7w2rdw-ruby3.3-ceedling-1.0.1/lib/ruby/gems/3.3.0/gems/ceedling-1.0.1/lib/ceedling/build_batchinator.rb:55:in `block (2 levels) in exec'
🌱 Ceedling could not complete operations because of errors
bash-5.2#
```

**Comment by mvandervoord** [comment]
Ah, that one! Good news, bad news... the good news is that it HAS been fixed. The bad news is that it's not in an official release yet. It's in the preview release of 1.0.2 at the moment. :)
