### ISSUE TITLE
Release task error

### ISSUE THREAD

**Issue by deltalejo** [ThrowTheSwitch/Ceedling#903]
I'm getting the following error when running the release task:

```shell
🧨 EXCEPTION: undefined local variable or method `loginator' for main
Backtrace ==>
/home/alejo/Workspaces/Ceedling/ceedling/lib/ceedling/tasks_release.rake:38:in `rescue in block in <top (required)>': undefined local variable or method `loginator' for main (NameError)
	/home/alejo/Workspaces/Ceedling/ceedling/lib/ceedling/tasks_release.rake:30:in `block in <top (required)>'
	/home/alejo/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rake-13.1.0/lib/rake/task.rb:281:in `block in execute'
	/home/alejo/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rake-13.1.0/lib/rake/task.rb:281:in `each'
	/home/alejo/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rake-13.1.0/lib/rake/task.rb:281:in `execute'
	/home/alejo/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rake-13.1.0/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
	/home/alejo/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rake-13.1.0/lib/rake/task.rb:199:in `synchronize'
	/home/alejo/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rake-13.1.0/lib/rake/task.rb:199:in `invoke_with_call_chain'
	/home/alejo/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rake-13.1.0/lib/rake/task.rb:188:in `invoke'
	/home/alejo/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:182:in `invoke_task'
	/home/alejo/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:138:in `block (2 levels) in top_level'
	/home/alejo/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:138:in `each'
	/home/alejo/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:138:in `block in top_level'
	/home/alejo/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:147:in `run_with_threads'
	/home/alejo/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:132:in `top_level'
	/home/alejo/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/ceedling-0.32.0/bin/cli_helper.rb:217:in `run_rake_tasks'
	/home/alejo/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/ceedling-0.32.0/bin/cli_handler.rb:206:in `build'
	/home/alejo/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/ceedling-0.32.0/bin/cli.rb:312:in `build'
	/home/alejo/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/thor-1.3.0/lib/thor/command.rb:28:in `run'
	/home/alejo/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/thor-1.3.0/lib/thor/invocation.rb:127:in `invoke_command'
	/home/alejo/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/thor-1.3.0/lib/thor.rb:527:in `dispatch'
	/home/alejo/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/ceedling-0.32.0/bin/cli.rb:92:in `start'
	/home/alejo/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/ceedling-0.32.0/bin/ceedling:125:in `<top (required)>'
	/home/alejo/.rbenv/versions/3.3.0/bin/ceedling:25:in `load'
	/home/alejo/.rbenv/versions/3.3.0/bin/ceedling:25:in `<main>'
```

Looking into `lib/ceedling/tasks_release.rake` it seems that lines 38 and 39 should be:

```ruby
@ceedling[:loginator].log( "#{ex.backtrace.first}: #{ex.message} (#{ex.class})", Verbosity::DEBUG )
@ceedling[:loginator].log( ex.backtrace.drop(1).map{|s| "\t#{s}"}.join("\n"), Verbosity::DEBUG )
```

**Comment by mkarlesky** [comment]
Thank you, @deltalejo. This is definitely a bug. The complex release project we use for validation has not been updated to use mixins in favor of the previous import feature. As such, release builds have not been properly exercised for prerelease versions of Ceedling in a little bit. We'll get it fixed for the next prerelease build.

**Comment by deltalejo** [comment]
There still an error with logging in release task.
