### ISSUE TITLE
Undefined method 'load_path' for Ceedling:Module

### ISSUE THREAD

**Issue by magnushedin** [ThrowTheSwitch/Ceedling#939]
I have a ceedling project or setup that have been working. For some reason (after updating to Ubuntu 24.04) I had to update ruby. After the Ruby update I run in to this exakt issue: [undefined method 'exists?'](https://github.com/ThrowTheSwitch/Ceedling/issues/865)

After installing (what I think is) latest pre-release _1.0.0-2e94ec6_ I get the following error:
![image](https://github.com/user-attachments/assets/977c9698-f0e4-47da-b2b8-1171ea1a1d80)

The Project.yml file have the same lines for the load_path as the example file, looking like this
![image](https://github.com/user-attachments/assets/c9ccd503-5c0c-453b-b8d5-fb1f5792b371)

**Comment by mvandervoord** [comment]
I believe the line that you've included from a previous example is no longer necessary and has been removed from Ceedling's usage. If you don't have any additional `load_paths` to add, you can simply give it an empty array:

```
:plugins:
  :load_paths: []
```

**Comment by magnushedin** [comment]
When I try to give it an empty array, I get this error instead:
![image](https://github.com/user-attachments/assets/11d12075-7d30-4f35-a3b5-4197f3fb9882)

**Comment by Letme** [comment]
Yeah, error reporting is not the best, but are you sure it fails on the line where empty `load_paths: []` is?

Reason I am asking is because there are few more changes to project.yml and I suggest you rather generate a freshly started one for 1.0.0 and then compare with your existing. That way it is a bit more manageable.

**Comment by magnushedin** [comment]
Yes, you are right, it seems to fail somewhere else. By generating a new project, Ceedling runs fine with that one. I haven't tried to convert the old project (I don't have the time right now, and it will affect other users).

Thanks for the support!

**Comment by mkarlesky** [comment]
@magnushedin So sorry about this. If you run with `--verbosity debug` you will get a full stack trace that explains what the actual issue is. There have been lots of changes in the newest Ceedling. The `load_paths` entry you have must be from a very old project configuration example. It's referencing something that never should have been exposed in a project configuration. That said, an empty `[]` should not be causing a bad reference. I would appreciate knowing the offending line of code from the debug stack trace so we can fix that. In the meantime, you should not need `load_paths` at all for your plugin configuration if you're not loading your own plugins from outside of Ceedling's built-in options.

**Comment by mkarlesky** [comment]
@magnushedin I've tried to reproduce your issue and so far am unable to do so. Certainly, the `"#{Ceedling.load_path}"` reference is unneeded. And, in fact, you can entirely omit `:load_paths` if you are not providing custom plugins from outside of Ceedling's built-in options. If you could kindly report back with the results of running with `--verbosity debug` that would be most helpful.

Please reopen this issue when you are able to report back.

Incidentally, in the prerelease version of Ceedling you are using, some plugins have been renamed and some have been combined. In my tests, Ceedling is reporting unrecognized plugin names without issue. Once you're past the originally reported problem, Ceedling will complain about `xml_tests_report` and `stdout_pretty_tests_report`. Please see the [list of plugin name changes in _BreakingChanges_](https://github.com/ThrowTheSwitch/Ceedling/blob/test/ceedling_0_32_rc/docs/BreakingChanges.md#built-in-plugin-name-changes).

**Comment by magnushedin** [comment]
@mkarlesky Sorry for the late responce.
Using my old project.yml file, omitting the complete "#{Ceedling.load_path}" entry and running with --verbosity debug, I get this output. Hope it helps.

🚧 Loaded project configuration from working directory.
 > Using: /home/magnus.hedin/workspace/220_02_190/unit_tests/project.yml
 > Working directory: /home/magnus.hedin/workspace/220_02_190/unit_tests
 > Set which Ceedling from config :project ↳ :which_ceedling => gem
 > Launching Ceedling from /var/lib/gems/3.2.0/gems/ceedling-1.0.0/

🚧 Application & Build Frameworks
   Ceedling => 1.0.0-2e94ec6
      CMock => 2.6.0
      Unity => 2.6.0
 CException => 1.3.4

🚧 Validating configuration contains minimum required sections...

🚧 Project Configuration Handling
---------------------------------
Processing Unity configuration...

🧨 EXCEPTION: undefined method `<<' for nil:NilClass
Backtrace ==>
/var/lib/gems/3.2.0/gems/ceedling-1.0.0/lib/ceedling/configurator.rb:216:in `populate_unity_config': undefined method `<<' for nil:NilClass (NoMethodError)
	/var/lib/gems/3.2.0/gems/ceedling-1.0.0/lib/ceedling/setupinator.rb:81:in `do_setup'
	/var/lib/gems/3.2.0/gems/ceedling-1.0.0/lib/ceedling/rakefile.rb:65:in `<top (required)>'
	<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:86:in `require'
	<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:86:in `require'
	/var/lib/gems/3.2.0/gems/ceedling-1.0.0/bin/cli_helper.rb:133:in `load_ceedling'
	/var/lib/gems/3.2.0/gems/ceedling-1.0.0/bin/cli_handler.rb:223:in `build'
	/var/lib/gems/3.2.0/gems/ceedling-1.0.0/bin/cli.rb:346:in `build'
	/var/lib/gems/3.2.0/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
	/var/lib/gems/3.2.0/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
	/var/lib/gems/3.2.0/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'
	/var/lib/gems/3.2.0/gems/ceedling-1.0.0/bin/cli.rb:93:in `start'
	/var/lib/gems/3.2.0/gems/ceedling-1.0.0/bin/ceedling:125:in `<top (required)>'
	/usr/local/bin/ceedling:25:in `load'
	/usr/local/bin/ceedling:25:in `<main>'

**Comment by mkarlesky** [comment]
@magnushedin Ah ha! Thank you. Now I know what's wrong. You found a configuration handling bug following a significant refactoring in recent months. This will be fixed in the next prerelease build. It appears you are using paramaterized tests. As a workaround, please add `:defines: []` to your ` :unity` configuration.

**Comment by magnushedin** [comment]
@mkarlesky Yes, that solved the problem and now I need to change names for plugins. Doing that I get a bunch of other errors, but I guess that is a different topic :).
Thank you!

**Comment by mkarlesky** [comment]
@magnushedin The [latest prerelease (1.0.0-13d0e3d)](https://github.com/ThrowTheSwitch/Ceedling/releases/tag/1.0.0-13d0e3d) should have this bug fixed and is available for testing. Just for sake of housekeeping I am going to close this issue. If you are able to try the new prerelease, please report back in this issue. If `:unity` or `:cmock` project configuration bugs persist for you, please reopen this issue.
